### ISSUE TITLE
Feature request: allow globs/globbing for out_static_libs

### ISSUE THREAD

**Issue by chrisirhc** [bazelbuild/rules_foreign_cc#1004]
I'm compiling duckdb which outputs multiple libraries from cmake:
```
    out_static_libs = [
        "libduckdb_fmt.a",
        "libduckdb_hyperloglog.a",
        "libduckdb_miniz.a",
        "libduckdb_re2.a",
        "libduckdb_static.a",
        "libduckdb_utf8proc.a",
        "libhttpfs_extension.a",
        "libparquet_extension.a",
        "libduckdb_fastpforlib.a",
        "libduckdb_fsst.a",
        "libduckdb_mbedtls.a",
        "libduckdb_pg_query.a",
        "libjemalloc_extension.a",
    ],
```

I'd like to request for the ability to do something like `out_static_libs = [ "*.a" ]`.
I'm new to bazel so I'm not sure if there's already an established globbing pattern for generated files. Please let me know if so.

**Comment by jsharpe** [comment]
Unfortunately this isn't something that bazel can support as it needs to know all outputs ahead of time to build its dependency graph and so you can't glob on generated files.

Having said that what you might need is the `output_group` `gen_dir` which is a directory artifact containing the install tree i.e. the output of running the install step of the cmake build.
