### ISSUE TITLE
binfmt_misc confuses configure about cross-compilation

### ISSUE THREAD

**Issue by novas0x2a** [bazelbuild/rules_foreign_cc#1082]
This specifically has to do with cross-compilation. autoconf has a cross-compilation check that's normally capable of automatically enabling cross-compilation mode (this is the check I mean): 
```
configure:4434: checking whether we are cross compiling
```

Unfortunately, it's extremely common on linux machines now to have `binfmt_misc` mounted, which permits linux to automatically pass non-native binaries to another process for execution (usually qemu). This can allow static binaries for (e.g.) arm64 platforms to run on (e.g.) amd64 hosts transparently.

Unfortunately, this does not work for dynamic binaries without a bunch of extra setup, because they look for (and can't find) the loader. This is a (redacted) example config.log from when that happens:

```
configure:4434: checking whether we are cross compiling
configure:4442: $CACHEDIR/execroot/$WORKSPACE/external/toolchain-linux-x86_64--linux-arm64/bin/gcc -o conftest --sysroot $CACHEDIR/execroot/$WORKSPACE/external/toolchain-linux-x86_64--linux-arm64_files/aarch64-stage2-linux-gnu/sysroot [TRUNCATED] conftest.c  >&5
configure:4446: $? = 0
configure:4453: ./conftest
aarch64-binfmt-P: Could not open '/lib/ld-linux-aarch64.so.1': No such file or directory
configure:4457: $? = 255
configure:4464: error: in `$CACHEDIR/execroot/$WORKSPACE/bazel-out/k8-fastbuild/bin/external/make/make.build_tmpdir':
configure:4466: error: cannot run C compiled programs.
If you meant to cross compile, use `--host'.
```

Unfortunately, autoconf doesn't handle this case very well, and just breaks. The usual workaround for this is to pass `--host` to `configure` (as the message says) but I'm relatively new to bazel and I'm not sure how to wire this up to automatically detect if the bazel `--platform` (the target platform) is compatible with the bazel `--host_platform` (the execution platform).

I was hoping that someone would see this and know exactly how to add this to `configure_make` so it works automatically :)

**Comment by matt-sm** [comment]
@jsharpe we are interested in submitting a PR to fix this, as it's a blocker to us cross-compiling.

Is this something you would consider merging?

**Comment by jsharpe** [comment]
Yes, definitely will be happy to merge somethign to help support this usecase, seems a tricky one though to resolve correctly, although guess macOS also potentially has similar challenges with Rosetta being present on Apple Silicon machines.

**Comment by novas0x2a** [comment]
This has landed now; to use this:
- Set up cross-compilation in [bazel natively](https://bazel.build/extending/platforms#specifying-build-platform)
- pass `configure_xcompile=True` to `configure_make`

The platforms that work are defined in https://github.com/bazelbuild/rules_foreign_cc/blob/main/foreign_cc/private/framework/platform.bzl.
