### ISSUE TITLE
Error: 'apple_common' value has no field or method 'multi_arch_split'

### ISSUE THREAD

**Issue by sgowroji** [bazelbuild/rules_foreign_cc#1083]
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/3252#018a1644-feae-46ba-aa8c-a27edd9ba830

Logs:
```
ERROR: Traceback (most recent call last):
	File "/private/var/tmp/_bazel_buildkite/74c36f9fadbb40496945af78b515f8ce/external/build_bazel_rules_apple/apple/internal/rule_support.bzl", line 221, column 36, in <toplevel>
		deps_cfg = apple_common.multi_arch_split,
Error: 'apple_common' value has no field or method 'multi_arch_split'
```
Fix is to update it with rules_apple once this is fixed https://github.com/bazelbuild/rules_apple/issues/2035#issuecomment-1663943174

CC Greenteam @salmasamy

**Comment by keith** [comment]
https://github.com/bazelbuild/rules_foreign_cc/pull/1086
