### ISSUE TITLE
Reopen: cmake_external does not handle source files with spaces

### ISSUE THREAD

**Issue by soro** [bazelbuild/rules_foreign_cc#1152]
This is simply reopening issue https://github.com/bazelbuild/rules_foreign_cc/issues/542
The problem is definitely not fixed yet. I assume the error disappeared for the author of the original issue because they upgraded boost sufficiently to no longer encounter that erroneous file name. Unfortunately, we are stuck on a boost version that still has this file.

```Error in fail: Wrong number (4) of arguments (("$$EXT_BUILD_ROOT$$/external/org_boost_boost/boost/serialization/collection_size_type", "copy.hpp", "$$EXT_BUILD_DEPS$$/include", "True")) in a call to 'symlink_contents_to_dir'```

**Comment by jsharpe** [comment]
Can you produce a minimal reproducer of this? Also what platform are you on as the toolchain for macos/linux/windows/freebsd for symlinking files is different on each of those OSes

**Comment by soro** [comment]
Unfortunately I don't really have time to minimize this and I've instead fixed it by updating to a newer boost version without this file
