### ISSUE TITLE
Under certain conditions, the `CMAKE` environment variable is not included in `TemplateVariableInfo`

### ISSUE THREAD

**Issue by thb-sb** [bazelbuild/rules_foreign_cc#1161]
Hello,

I've noticed that under some certain conditions, the `CMAKE` environment variable is not included in the [`TemplateVariableInfo`] object owned by the `current_cmake_toolchain`.

For instance, if CMake is built from source, then the variable is set:

https://github.com/bazelbuild/rules_foreign_cc/blob/c2e097455d2bbf92b2ae71611d1261ba79eb8aa8/toolchains/private/BUILD.bazel#L62-L65

However, when it comes to prebuilt CMake bundle, the variable isn't set.

https://github.com/bazelbuild/rules_foreign_cc/blob/c2e097455d2bbf92b2ae71611d1261ba79eb8aa8/toolchains/prebuilt_toolchains.py#L333-L342

Note that this issue does not affect prebuilt Ninja bundles:

https://github.com/bazelbuild/rules_foreign_cc/blob/c2e097455d2bbf92b2ae71611d1261ba79eb8aa8/toolchains/prebuilt_toolchains.py#L449

I'm trying to compile a rust crate which uses the [`cmake`] crate in its `build.rs` build script. I can include the CMake toolchain in the build script processing using the [`build_script_toolchains`] annotation, but since the `CMAKE` environment variable isn't necessary set, the build script fails to find the CMake binary.

Do you think this is a real issue?

I've written a quick-but-unsound fix locally, but before trying to open a PR to fix it I wanted to make sure that it's a real issue.

[`TemplateVariableInfo`]: https://bazel.build/rules/lib/providers/TemplateVariableInfo
[`cmake`]: https://crates.io/crates/cmake
[`build_script_toolchains`]: https://bazelbuild.github.io/rules_rust/crate_universe.html#crate.annotation-build_script_toolchains

**Comment by jsharpe** [comment]
I think this is just an oversight rather than intentional design - feel free to put together a PR to make this consistent!
