### ISSUE TITLE
Add rules_foreign_cc to Bazel with downstream pipeline

### ISSUE THREAD

**Issue by mhlopko** [bazelbuild/rules_foreign_cc#118]
Since these rules were never green on buildkite, I'm removing them from the downstream pipeline. Please make them green on https://buildkite.com/bazel/rules-foreign-cc, and then work with the Bazel Green Team (bazel-green-team@googlegroups.com) to re-enable it.

**Comment by mhlopko** [comment]
Or better, create an issue on https://github.com/bazelbuild/continuous-integration, thanks!

**Comment by irengrig** [comment]
Done.
