### ISSUE TITLE
cmake_options in Bzlmod example

### ISSUE THREAD

**Issue by bashtavenko** [bazelbuild/rules_foreign_cc#1210]
This is my legacy code

**WORSPACE**

```
http_archive(
    name = "rules_foreign_cc",
    sha256 = "e60cfd0a8426fa4f5fd2156e768493ca62b87d125cb35e94c44e79a3f0d8635f",
    strip_prefix = "rules_foreign_cc-0.2.0",
    url = "https://github.com/bazelbuild/rules_foreign_cc/archive/0.2.0.zip",
)
load("@rules_foreign_cc//foreign_cc:repositories.bzl", "rules_foreign_cc_dependencies")
rules_foreign_cc_dependencies()
```
**BUILD**
```
cmake(
    name = "opencv",
    cmake_options = [
        "-DBUILD_LIST=calib3d,core,features2d,highgui,imgcodecs,imgproc,video,videoio,ml",
        "-DWITH_FFMPEG=OFF",
        "-DWITH_GTK=ON",     # Add this line to enable GTK support
    ],
    lib_source = "@opencv//:all",
    out_include_dir = "include/opencv4",
    out_shared_libs = [
        "libopencv_ml.so.408",
        "libopencv_calib3d.so.408",
        "libopencv_core.so.408",
        "libopencv_flann.so.408",
        "libopencv_features2d.so.408",
        "libopencv_highgui.so.408",
        "libopencv_imgcodecs.so.408",
        "libopencv_imgproc.so.408",
        "libopencv_video.so.408",
        "libopencv_videoio.so.408",
    ],
    visibility = ["//visibility:public"],
)
```

I commented out this section in **WORKSPACE** and added to **MODULE.bazel**
```
bazel_dep(name = "rules_foreign_cc", version = "0.10.1")
```

but Bazel does not see `cmake_options`:

```
ERROR: package contains errors: : //:opencv: no such attribute 'cmake_options' in 'cmake' rule
```

I tried something like ```use_repo(rule_foreign_cc_deps = rules_foreign_cc_dependencies``` or ``rules_foreign_cc_dependencies()`` but it didn't work.

I am most likely not wiring this correctly, but is there an example for Bzlmod syntax?

**Comment by jsharpe** [comment]
0.2.0 is quite old at this point - a number of the arguments got renamed in versions between then. Refer to https://bazelbuild.github.io/rules_foreign_cc/0.9.0/cmake.html for the updated names.

**Comment by bashtavenko** [comment]
Is this a matter of updating Bazel Cenral Registry? What I am see is this [this]( https://app.snippyly.com/discuss?q=oavxgYfPEOk0pwdfmsF0&EDIT=PzxeCOwdWTKOTv5BPuOt) and the latest commit was 8 month ago. Is that right?

**Comment by jsharpe** [comment]
No; my point is that your previous WORKSPACE version was 0.2.0 which is v. old and that even the later workspace versions would be broken for you. You need to update your calls to the cmake rule to use the updated names.

**Comment by bashtavenko** [comment]
Yes, it is just a matter of changing `cmake_options` to `cache_entries`. It works in `bazel_dep(name = "rules_foreign_cc", version = "0.10.1")`. Thank you
