### ISSUE TITLE
create_library_to_link not called with correct arguments

### ISSUE THREAD

**Issue by bbarnes52** [bazelbuild/rules_foreign_cc#139]
#117 changed the method from create_symlink_library_to_link to create_library_to_link, but did not update the method parameters accordingly. any builds that execute this code will fail. simply rolling back that change, however, does not resolve the issue, as it leads to dangling symlink errors.

**Comment by irengrig** [comment]
Thank you for reporting the problem!

I tried to fix that #141 (passed the semantically correct arguments), but the test for building the shared library and passing it to cc_test, cc_binary fails with assertion.
Probably we will resolve this on Monday.
