### ISSUE TITLE
Example Request: LLVM

### ISSUE THREAD

**Issue by kkiningh** [bazelbuild/rules_foreign_cc#149]
LLVM is a big CMake only dependency for many C++ projects (e.g. Tensorflow). It would be awesome if it could be explicitly supported as an example.

Thanks for the awesome work on this library!

**Comment by irengrig** [comment]
Hi @kkiningh , thank you for your feedback:) It is definitely a good idea.
If you would like to submit a PR with the example, I will be happy to review it!
