### ISSUE TITLE
sandbox builds search in non-existent directories

### ISSUE THREAD

**Issue by bbarnes52** [bazelbuild/rules_foreign_cc#152]
```
CMake Error at /blaze/a08c2e4811c846650b733c6fc815a920/sandbox/processwrapper-sandbox/1/execroot/__main__/bazel_foreign_cc_deps_rosgraph_msgs/cpp_common/share/cpp_common/cmake/cpp_commonConfig.cmake:113 (message):
  Project 'cpp_common' specifies
  '/blaze/a08c2e4811c846650b733c6fc815a920/sandbox/processwrapper-sandbox/12/execroot/__main__/bazel_foreign_cc_deps_cpp_common/boost/include'
  as an include dir, which is not found.  It does neither exist as an 
  absolute directory nor in '/tmp/tmp.COXdz1ZDYu/cpp_common//blaze/a08c2e4811c846650b733c6fc815a920/sandbox/processwrapper-sandbox/12/execroot/__main__/bazel_foreign_cc_deps_cpp_common/boost/include'.
```

the cpp_commonConfig.cmake does exist, but it is in processwrapper-sandbox/1/execroot/__main__/bazel_foreign_cc_deps_rosgraph_msgs/boost/include

if my understanding is correct, the config is being written to the appropriate location, but bazel is later searching in the wrong directory? 

[out.txt](https://github.com/bazelbuild/rules_foreign_cc/files/2583071/out.txt)

**Comment by bbarnes52** [comment]
update: this only reproduces after a failed clean build, the `/blaze/a08c2e4811c846650b733c6fc815a920/sandbox/processwrapper-sandbox/12/execroot/__main__/bazel_foreign_cc_deps_cpp_common/boost/include` directory is only present after the clean build, not subsequent builds

if the clean build succeeds, this does not reproduce, so I am not affected. leaving this open in case it is indicative of a larger issue

**Comment by bbarnes52** [comment]
@irengrig will it be an issue for remote execution is that an action (in this case, action 1) is attempting to access files in a different action's (12) sandbox?

**Comment by bbarnes52** [comment]
potentially related to this line? https://github.com/bazelbuild/rules_foreign_cc/blob/master/for_workspace/utils_osx.sh#L20

is finding files matching regex "*-config" WAI, or should that read "*-config.cmake" (and potentially *Config.cmake as well)?

**Comment by irengrig** [comment]
Sorry for keeping you waiting. 
Thank you for investigating it!

Yep it is a good idea to include *.cmake (or just *.cmake config) files into the pattern for replacing absolute paths. The only reason the pattern is there is parsing all files will add unnecessary overhead.
Yep, probably this was giving the wrong absolute path under some previous sandbox.

Your PR is welcome!

**Comment by bbarnes52** [comment]
#156
