### ISSUE TITLE
generate test targets for cmake

### ISSUE THREAD

**Issue by JonathanDCohen** [bazelbuild/rules_foreign_cc#153]
Looking through the documentation, it looks like there is no way to generate CMake test targets currently.  I'm investigating using these rules for Abseil CMake builds, but we can't ditch our hand-rolled CMakeLists files without also being able to generate tests.

**Comment by irengrig** [comment]
Hi @JonathanDCohen, it is possible to change the make invocation with make_commands attribute, by default it is ["make", "make install"], so you can add "make test" as well.
Also CMake options to make tests be generated by CMake can be passed with cache_entries attribute (it depends on the target, which exactly options).

Is it necessary to run ctest explicitly?
