### ISSUE TITLE
Copts attribute?

### ISSUE THREAD

**Issue by JonathanDCohen** [bazelbuild/rules_foreign_cc#154]
Looking through the documentation for generating CMake targets, I don't see a way to pass in copts.  Ideally I'd like to call these functions from a wrapper function around cc_library and cc_test so we don't have to change our BUILD files to get our generated CMake.  Am I missing how to do this?

**Comment by irengrig** [comment]
Hi @JonathanDCohen, you can pass CMake's CFLAGS or CXXFLAGS with env_vars attribute of cmake_external rule.
Please note that we also take all the flags from Bazel's cc_toolchain and convert them to corresponding CMake environment variables or cache initializers, so you may already be fine with most flags.

cmake_external was designed to be similar to cc_library by the set of attributes and outputs. For instance, you can pass cc_library targets as dependencies and pass cmake_external as dependencies into other cc_libraries.

**Comment by JonathanDCohen** [comment]
Do we want to clobber CXXFLAGS?

For more context, Abseil has a bunch of standard copts we put on every target (https://github.com/abseil/abseil-cpp/blob/master/absl/copts.bzl) so I'd need some way to specify those flags in addition to whatever bazel or cmake would normally put there

**Comment by irengrig** [comment]
It is possible to convert these flags into a space-separated string in a BUILD file and pass the result with env_vars ([example](https://github.com/bazelbuild/rules_foreign_cc/blob/8590cb0da83122584a119016b0d751f7b3ac683c/examples/pybind11/BUILD#L20) of this option usage (though referring to locally installed python, which is not correct)). 
The values that are passed from Bazel's cc_toolchain into CXXFLAGS will be merged with the passed flags.
The passed values for CXXFLAGS will not be propagated to the dependants of that cmake_external target.

**Comment by htuch** [comment]
@irengrig does this also cover `--cxxopt` as specified on Bazel CLI?

**Comment by htuch** [comment]
@irengrig following your offline suggestion, I instrumented `get_flags_info()`. I set some coverage related flag, call it `-fblah`, in `--cxxopt`, `--conlyopt`, `--linkeropt` and `--host_linkeropt` on Bazel CLI. 

The only place `-fblah` appears is in `cxx_linker_executable` and `cxx_linker_shared`, it doesn't show up in `cc` or `cxx` in flags info.

It seems this is a bug or missing feature, we should be able to propagate the compiler options from Bazel CLI down to the `cmake` target. Would be awesome to have this supported.

**Comment by htuch** [comment]
@irengrig I also think this affects `configure_make`, which is how we setup two of our external deps (gperftools, LuaJIT).

**Comment by irengrig** [comment]
Please verify the fix #235, the --copt etc. options should be read by rules_foreign_cc now.

**Comment by JonathanDCohen** [comment]
Lookin gback at this, I think rules_foreign_cc isn't what I Was looking for anyways.  This builds a CMake lib using Bazel -- I want to generate a CMake buildsystem from a Bazel buildsystem.  It seems like other people are working on this though so I won't close

**Comment by EricCousineau-TRI** [comment]
Er, just curious: When you say "generate a CMake buildsystem", do you mean emitting the relevant config files to then be consumed by a *downstream* CMake project?

**Comment by JonathanDCohen** [comment]
Specifically I'm working on Abseil.  We maintain both a Bazel and a CMake
buildsystem and would like to avoid the duplication, possible drift between
the two buildystems.  As Abseil's source of truth is internal to Google, we
prefer to maintain a Bazel buildsystem ourselves and then generate the
CMakeLists.txt files from our BUILD.bazel files.

**Comment by EricCousineau-TRI** [comment]
Gotcha, thanks for the explanation!

If it's useful to you, we also ran into this for [drake](https://github.com/RobotLocomotion/drake), and made a solution for generating CMake artifacts for consumption via downstream CMake projects (at a loss of target granularity and only for shared libs for now):
https://github.com/RobotLocomotion/drake/blob/015998c4f/CMakeLists.txt#L426
https://github.com/RobotLocomotion/drake/blob/015998c4f/BUILD.bazel#L53
https://github.com/RobotLocomotion/drake/blob/015998c4f/tools/install/libdrake/BUILD.bazel#L75
Example usage:
https://github.com/RobotLocomotion/drake-external-examples/tree/43ff258/drake_cmake_installed#instructions

This is not a perfect solution by any means, but has been working for us thus far.
Definitely looking forward to seeing what solution y'all converge on!

**Comment by htuch** [comment]
I can confirm that https://github.com/bazelbuild/rules_foreign_cc/pull/235 fixes the issues we were observing in Envoy.

**Comment by irengrig** [comment]
Closing as the issue with passing flags transitively was solved by #235 .
Tests are here: https://github.com/bazelbuild/rules_foreign_cc/tree/master/test/standard_cxx_flags_test
