### ISSUE TITLE
_merge function not WAI

### ISSUE THREAD

**Issue by bbarnes52** [bazelbuild/rules_foreign_cc#158]
https://github.com/bazelbuild/rules_foreign_cc/blob/master/tools/build_defs/cmake_script.bzl#L178

If I were to add a cache_entry such as CMAKE_CXX_FLAGS, my builds will fail because the command passed to the compiler is invalid syntax. this is because the strip commands remove trailing quotations that are actually necessary.

for example, if I have CXXFLAGS="foo="bar"", and I add a cache_entry {CMAKE_CXX_FLAGS: "-Fbat}, this will yield CXXFLAGS="foo="bar -Fbat", which results in an unterminated quotation error when cmake is eventually called.

Just removing the "strip" calls worked for me, but I wanted to make sure there is not some other corner case where this would be problematic. If this is a reasonable fix, happy to submit a PR!

**Comment by irengrig** [comment]
Thank you for reporting that! 
Would be happy to see the fix! Feel free to file a PR.

Yep, these strings manipulations can be tricky, I will need to run some checks that other cases are fine.

**Comment by irengrig** [comment]
(Fixed)
