### ISSUE TITLE
unable to find shared object files

### ISSUE THREAD

**Issue by bbarnes52** [bazelbuild/rules_foreign_cc#165]
disclaimer: not a bug or FR, hoping for assistance troubleshooting, let me know if there is a better forum

I am trying to run a simple hello_world `cc_binary` target that depends on some `cmake_external` targets. the build completes successfully, but I get the following linking error when the target is `blaze run`:

```
/blaze/a08c2e4811c846650b733c6fc815a920/execroot/__main__/bazel-out/k8-fastbuild/bin/src/examples/hello_world/hello_world: error while loading shared libraries: libconsole_bridge.so.0.4: cannot open shared object file: No such file or directory
```

libconsole_bridge.so.0.4 is created by the build, and is located at $EXT_BUILD_ROOT/bazel-out/k8-fastbuild/genfiles/third_party/ros/console_bridge/copy_console_bridge/console_bridge/ in my filesystem, as expected.

would love to get your expertise on how to proceed @irengrig . in general, how can I ensure the linker can find .so files generated by `cmake external` targets? simply adding -L<path_to_dynamic_lib> to `linkopts` does not resolve the issue.

**Comment by irengrig** [comment]
Hi @bbarnes52,
is the resulting library declared in the ["shared_libraries"](https://github.com/bazelbuild/rules_foreign_cc/blob/c82068dd2dae61bd7f9246073258110a54570d0a/tools/build_defs/old_10_2018/framework.bzl#L78) attribute of the cmake_external target?

**Comment by bbarnes52** [comment]
yes that was it. had declared libconsole_bridge.so but not libconsole_bridge.so.0.4! smh
thank you as always for your help!

**Comment by bbarnes52** [comment]
OK so I'm getting the same error for a library that is declared in `shared_libraries` attribute of cmake_external. the library is `libboost_regex.so.1.68.0` (I'm maintaining my own fork of the `boost_build` rule). the library is generated during the build process as expected.

**Comment by irengrig** [comment]
Hi, about the forum, there is now Bazel's slack available, we may use it (I send you the invitation).

Actually, it works quite fine with the current master (I also did the similar changes to make it possible to pass additional attributes to boost rule): #177
Please see the examples in //examples/boost

**Comment by bbarnes52** [comment]
have not confirmed, but I think having both lib<name>.so and lib<name>.so.<version> in a `shared_libraries` target will fail at analysis time once I upgrade to latest version: https://github.com/bazelbuild/rules_foreign_cc/blob/master/tools/build_defs/new_11_2018/cc_toolchain_util.bzl#L104

**Comment by bbarnes52** [comment]
ok so closing the loop, this issue goes away if I remove the `static_libraries` from boost_build and only declare the `shared_libraries`. I imagine that has something to do with "https://github.com/bazelbuild/rules_foreign_cc/blame/master/tools/build_defs/old_11_2018/cc_toolchain_util.bzl#L164"

is this WAI? seems like it might be, just curious for own understanding

**Comment by bbarnes52** [comment]
tried with the new_11_2018, same issue occurs. root cause seems to be that .so files are not symlinked into _solib directory when `static_libraries` field is not the empty list.

**Comment by terrisgit** [comment]
This issue helped me get boost_build working with shared libraries. I'm grateful so I'm posting this to help others.

Here is my workspace

```
# Boost
http_archive(
    name = "boost",
    build_file_content = all_content,
    strip_prefix = "boost_1_65_0",
    urls = ["https://sourceforge.net/projects/boost/files/boost/1.65.0/boost_1_65_0.tar.gz"],
)
```

Here is my boost/BUILD

```
load("@rules_foreign_cc//tools/build_defs:boost_build.bzl", "boost_build")

boost_build(
    name = "boost",
    lib_source = "@boost//:all",
    shared_libraries = [
        "libboost_filesystem.so.1.65.0",
        "libboost_log.so.1.65.0",
        "libboost_system.so.1.65.0",
    ],
    user_options = [
        "threading=multi",
        "link=shared",
        "cxxflags=-std=c++11",
        "variant=debug",
        "-d0",  # Minimal output
        "-j8",  # Build with parallel processes
        "--with-filesystem",
        "--with-log",
    ],
    visibility = ["//visibility:public"],
)
```

**Comment by thymbahutymba** [comment]
I'm facing the same issue but I'm not able to solve it.

This is the build file
```
load("@rules_foreign_cc//foreign_cc:defs.bzl", "boost_build")

SHARED_LIBS = [
    "libboost_filesystem.so.1.73.0",
    "libboost_program_options.so.1.73.0",
    "libboost_regex.so.1.73.0",
    "libboost_system.so.1.73.0",
    "libboost_thread.so.1.73.0",
]

filegroup(
    name = "all_srcs",
    srcs = glob(["**"]) + [ ":user_config" ],
    visibility = ["//visibility:public"],
)

boost_build(
    name = "boost",
    lib_source = ":all_srcs",
    bootstrap_options = [ "--without-icu" ],
    out_shared_libs = SHARED_LIBS,
    user_options = [
        "-j$(nproc)",
        "--with-filesystem",
        "--with-program_options",
        "--with-regex",
        "--with-system",
        "--with-thread",
        "--user-config=user-config.jam",
        "variant=release",
        "link=shared",
        "threading=multi",
    ],
    visibility = ["//visibility:public"],
)

genrule(
    name = "user_config",
    outs = ["user-config.jam"],
    cmd = """
cat > $@ << EOF
using mpi ;
EOF"""
)
```
Running `bazel build @boost//...` I got the following error:
```
(13:01:18) ERROR: /root/.cache/bazel/540135163923dd7d5820f3ee4b306b32/external/boost/BUILD.bazel:79:12: output 'external/boost/boost/lib/libboost_filesystem.so.1.73.0' was not created
(13:01:18) ERROR: /root/.cache/bazel/540135163923dd7d5820f3ee4b306b32/external/boost/BUILD.bazel:79:12: output 'external/boost/boost/lib/libboost_program_options.so.1.73.0' was not created
(13:01:18) ERROR: /root/.cache/bazel/540135163923dd7d5820f3ee4b306b32/external/boost/BUILD.bazel:79:12: output 'external/boost/boost/lib/libboost_regex.so.1.73.0' was not created
(13:01:18) ERROR: /root/.cache/bazel/540135163923dd7d5820f3ee4b306b32/external/boost/BUILD.bazel:79:12: output 'external/boost/boost/lib/libboost_system.so.1.73.0' was not created
(13:01:18) ERROR: /root/.cache/bazel/540135163923dd7d5820f3ee4b306b32/external/boost/BUILD.bazel:79:12: output 'external/boost/boost/lib/libboost_thread.so.1.73.0' was not created
(13:01:27) ERROR: /root/.cache/bazel/540135163923dd7d5820f3ee4b306b32/external/boost/BUILD.bazel:79:12: not all outputs were created or valid
```
