### ISSUE TITLE
osx libtool paramater error

### ISSUE THREAD

**Issue by bpeake13** [bazelbuild/rules_foreign_cc#185]
This seems to be related to #49 although I don't see a resolution in that issue. I am trying to compile on OSX 10.14.1 (18B75) Mojave with bazel 0.21 and am getting the following errors when I try to build libz from the examples:

```
error: /Library/Developer/CommandLineTools/usr/bin/libtool: no output file specified (specify with -o output)
Usage: /Library/Developer/CommandLineTools/usr/bin/libtool -static [-] file [...] [-filelist listfile[,dirname]] [-arch_only arch] [-sacLT] [-no_warning_for_no_symbols]
Usage: /Library/Developer/CommandLineTools/usr/bin/libtool -dynamic [-] file [...] [-filelist listfile[,dirname]] [-arch_only arch] [-o output] [-install_name name] [-compatibility_version #] [-current_version #] [-seg1addr 0x#] [-segs_read_only_addr 0x#] [-segs_read_write_addr 0x#] [-seg_addr_table <filename>] [-seg_addr_table_filename <file_system_path>] [-all_load] [-noall_load]
make[2]: *** [lib/libopenblas.a] Error 1
make[1]: *** [CMakeFiles/openblas.dir/all] Error 2
make: *** [all] Error 2
```

Here is my command line:
`bazel build //examples/cmake:libz`

Any thoughts?

**Comment by snowp** [comment]
I've ran into what seems to be a similar issue when building https://github.com/envoyproxy/envoy on latest master which recently switched to rules_foreign_cc. 

The issue seems to be that `CMAKE_AR` is incorrectly inferred to be `/usr/bin/libtool`:

```
/var/folders/y1/2rg8_b7s2k372mb520jjcln00000gn/T/tmp.JIJtfdBb:0 rg CMAKE_AR
CMakeCache.txt
37:CMAKE_AR:FILEPATH=/usr/bin/libtool
268://ADVANCED property for variable: CMAKE_AR
269:CMAKE_AR-ADVANCED:INTERNAL=1

CMakeFiles/3.13.4/CMakeCCompiler.cmake
19:set(CMAKE_AR "/usr/bin/libtool")
```

When running cmake directly in one of the third party repositories I get `ar` as expected:

```
~/Development/zlib(master):0 rg CMAKE_AR
CMakeCache.txt
24:CMAKE_AR:FILEPATH=/Library/Developer/CommandLineTools/usr/bin/ar
222://ADVANCED property for variable: CMAKE_AR
223:CMAKE_AR-ADVANCED:INTERNAL=1

CMakeFiles/3.13.2/CMakeCCompiler.cmake
19:set(CMAKE_AR "/Library/Developer/CommandLineTools/usr/bin/ar")
```

I was able to get Envoy building by setting `"CMAKE_AR": "/usr/bin/ar"` to each foreign rule, which is obviously not ideal. 

It should be noted that most people are able to build Envoy on OS X with foreign rules - this only seems to impact some people. 

@irengrig Any clues as to what might be going on?

**Comment by gsserge** [comment]
I've ran into the same issue when building Envoy on OSX 10.14.3.

**Comment by penglei** [comment]
> I've ran into the same issue when building Envoy on OSX 10.14.3.

me too.

**Comment by tvoran** [comment]
FWIW, I got this same issue with envoy, and got past it after installing Xcode from the app store.

**Comment by wuliu7** [comment]
I ran into the same error with Bazel 1.0.0, downgrading to bazel 0.29.1 worked

**Comment by irengrig** [comment]
Please make sure you are using rules_foreign_cc updated to this commit: https://github.com/bazelbuild/rules_foreign_cc/pull/315.

**Comment by ktf** [comment]
I still have this error with zeromq and today's master.

**Comment by irengrig** [comment]
The libtool is used now on Mac OSX by Bazel as part of the toolchain; so if you do not specify anything for CMAKE_AR tool in the cache_entries, libtool from the toolchain will be used;
if the library that you are building does not support that (i.e. have some assumptions about CMAKE_AR in the build script), you probably get this error.
I may be wrong; I would appreciate more fresh data from /logs folder of the library that you are trying to build (the actual scripts and the log is there).
Thank you in advance!

For instance, I had to change this test: https://github.com/irengrig/rules_foreign_cc/blob/2a6ea8b697549374fa7fecbfee308939b5f50974/examples/cc_configure_make/BUILD#L17

**Comment by ktf** [comment]
Thank you for your reply. Changing things as you did in your last example fixed my problem.
