### ISSUE TITLE
Cmake linkopts not passed

### ISSUE THREAD

**Issue by Dig-Doug** [bazelbuild/rules_foreign_cc#200]
Hi,

I'm trying to build the [CGAL library](https://github.com/CGAL/cgal) using the `cmake_external` rule. Everything builds successfully, but the library also requires some additional linker flags when it's used. I've listed the necessary flags in the `linkopts` attribute, however they do not seem to be passed to other rules.

I've created a small reproduction of my problem [here](https://github.com/Dig-Doug/foreign-cc-cgal). The repo has 3 different test cases:
1. Building cgal and using it all within bazel - I believe this is the ideal usage, but doesn't work
1. CGAL is built externally and wrapped in a `cc_library` with `linkopts`. - I think this is roughly equivalent to what `cmake_external` is doing and it works.
1. Similar to case 1, except `linkopts` are added to the `cc_binary`. - This works, but is not ideal. I don't want to add the `linkopts` to all binaries (e.g. all my tests) that have CGAL as a dependency.

Please let me know if you need any more info.

Thanks for your help!

P.S. Thanks for your work on this library, I've been using it to build some other libs and it works well :)

**Comment by AdamDorwart** [comment]
I'm able to reproduce this.

**Comment by htuch** [comment]
I think we're also seeing this for `--cxxopt`.

**Comment by irengrig** [comment]
Sorry for the delay, this should have been fixed by #235.

**Comment by Dig-Doug** [comment]
Yes, this seems to be fixed now. Thanks!
