### ISSUE TITLE
Support for arm64 / aarch64

### ISSUE THREAD

**Issue by moderation** [bazelbuild/rules_foreign_cc#212]
Envoy Proxy just implemented `rules_foreign_cc` today with PR https://github.com/envoyproxy/envoy/pull/5218. My builds for Linux x86_64 and macOS are working fine. However my arm64 / aarch64 builds are failing with the following error.

`ERROR: While resolving toolchains for target //bazel/foreign_cc:zlib: no matching toolchains found for types @rules_foreign_cc//tools/build_defs/shell_toolchain/toolchains:shell_commands`

It looks like only Linux, Windows and macOS are supported on the x86_64 architecture after looking at https://github.com/bazelbuild/rules_foreign_cc/blob/master/tools/build_defs/shell_toolchain/toolchains/toolchain_mappings.bzl

/cc @htuch

**Comment by irengrig** [comment]
Sorry. 
Yes, this is a bug with rules_foreign_cc to not provide the default toolchain implementation.
I just added default toolchain in #213, with "linux" be assumed to be a os name to be passed to CMake. (I.e. that is what is recorded into CMake's crosstool file. 
If the platform name should be different, it can be overridden with passing correct CMAKE_SYSTEM_NAME, but as we better try to pass the correct name, I will try to improve on that)

I will continue to check it with amd64/aarch64 later today in a Docker container. Are there more speicfic details to take into account?

Sorry again.

**Comment by moderation** [comment]
Thanks. I can confirm that if I modify the following Envoy will build on aarch64.
```diff
diff --git a/~/Library/rules_foreign_cc/tools/build_defs/shell_toolchain//toolchains/toolchain_mappings.bzl b/~/Library/envoyproxy/moderation/rules_foreign_cc/tools/build_defs/shell_toolchain/toolchains/toolchain_mappings.bzl
index af9647e..42fa81a 100644
--- a/~/Library/rules_foreign_cc/tools/build_defs/shell_toolchain//toolchains/toolchain_mappings.bzl
+++ b/~/Library/envoyproxy/moderation/rules_foreign_cc/tools/build_defs/shell_toolchain/toolchains/toolchain_mappings.bzl
@@ -11,7 +11,7 @@ TOOLCHAIN_MAPPINGS = [
     _ToolchainMapping(
         exec_compatible_with = [
             "@bazel_tools//platforms:linux",
-            "@bazel_tools//platforms:x86_64",
+            "@bazel_tools//platforms:aarch64",
         ],
         file = "@rules_foreign_cc//tools/build_defs/shell_toolchain/toolchains/impl:linux_commands.bzl",
     ),
```
I'll try using `CMAKE_SYSTEM_NAME`. I did have a couple of tries at adding a new `ToolchainMapping` section but ran into errors. So hopefully it won't be too hard to add `aarch64` in addition to `x86_64`. There are teams building Envoy for the IBM `ppc64le` architecture as well so I expect there will be several architectures that need to be added.

**Comment by moderation** [comment]
I just tested the latest commit and it works on `aarch64`. Thanks for the quick turnaround.

**Comment by irengrig** [comment]
> I will make it now that CMAKE_SYSTEM_NAME comes from os_name() function

Done in #215.

**Comment by irengrig** [comment]
> I just tested the latest commit and it works on aarch64. Thanks for the quick turnaround.

Cool, thank you!

**Comment by irengrig** [comment]
Can I close the issue then?

**Comment by moderation** [comment]
Yes - thanks again for the quick turnaround.
