### ISSUE TITLE
Can this project suitably work with minimal change to use regular GNU Make instead of CMake?  

### ISSUE THREAD

**Issue by indrgun** [bazelbuild/rules_foreign_cc#217]
A colleague of mine forwarded to me this repository.  I wonder whether it is suitably easy to make modification to this so I can use it using GNU Make instead of CMake.

Thank you

**Comment by indrgun** [comment]
Thank you for replying back swiftly.  I really appreciate it.

The third-party cc project we have provides "configure" that is executed first prior to running 
"<configured-gnu-make>/bin/make -C <src-dir> -f Makefile" and
"<configured-gnu-make>/bin/make -C <src-dir> -f Makefile install".

Env variables set prior to "configure" like CC, LDFLAGS, PLATFORM_ARCH are set and exported.
Any open source project can be used as example for instance : https://github.com/JHUISI/charm, and https://github.com/gpg/libgcrypt.

Thank you

**Comment by irengrig** [comment]
I did some experiments with building charm library.
It required some changes in configure_make rule: #221.
However, I was not able to build it, as it uses many dependencies (and working with all of them takes significantly more time that I can devote), each of them should be built separately or taken from the local system, through it is not typical Bazel approach.

The part of the Bazel BUILD file for building charm:
`configure_make(
    name = "charm",
# maybe use static_libraries to specify the name of the resulting library
    configure_command = "configure.sh",
    configure_in_place = True,
    lib_source = "@charm//:all",
    deps = [
        ":gmp",
        ":pbc",
    ],
)`
where charm repository is defined in WORKSPACE file as:
`all_content = """filegroup(name = "all", srcs = glob(["**"]), visibility = ["//visibility:public"])"""
http_archive(
        name = "charm",
        build_file_content = all_content,
        strip_prefix = "charm-dev",
        urls = ["https://github.com/JHUISI/charm/archive/dev.zip"],
    )
`
I was trying to build also pbc and gmp with the same configure_make rule:
`configure_make(
    name = "gmp",
    lib_source = "@gmp//:all",
    static_libraries = ["libgmp.a"],
)

configure_make(
    name = "pbc",
    lib_source = "@pbc//:all",
# not sure about the name of the resulting library
    static_libraries = ["libpbc.a"],
)`
 
Gmp builds, but from what I see, charm's configure.sh script does not pass -I<gmp include directory> to the actual make call, where gmp.h is needed. However, it was able to locate in it the local system, when I installed it. Not sure how one can handle this - maybe the configure.sh can be patched, or it is acceptable to use gmp from the local system.
I was not able to build pbc, as it requires the some other dependencies and I just stopped.

Also, for both gmp and pbc, the flag "configure_in_place" is not needed.
If you need to change the default GNU Make commands (make & make install), invoked by configure_make, use "make_commands" attribute.

Please let me know if this was helpful.

**Comment by lizan** [comment]
+1, in Envoy we also want to use this to build [LuaJIT](https://github.com/LuaJIT/LuaJIT) as a dependency with make only.

**Comment by lizan** [comment]
cc @htuch

**Comment by BloggerBust** [comment]
Hi, I have a similar question. I am trying to understand how to build an autotools project with gmake using rules_foreign_cc. Specifically, I want to be able to build libsodium. I have setup a github repo to demonstrate what I have so far: https://github.com/BloggerBust/bazelLibsodiumTest. Any guidance would be greatly appreciated. I think I lack some basic understandings and would love a point in the right direction.

Cheers!

**Comment by BloggerBust** [comment]
I created a [paste of the bazelLibsodiumTest build output](https://pastebin.com/CNiw50zT). At the bottom of the output there is an error complaining that CMake cannot find CMakeLists.txt.

```CMake Error: The source directory "/home/dustfinger/.cache/bazel/_bazel_dustfinger/9eac64b3fc007e990a2b4d34b02baad6/sandbox/linux-sandbox/2/execroot/com_github_bloggerbust_bazelLibsodiumTest/external/org_libsodium" does not appear to contain CMakeLists.txt.```

**Comment by BloggerBust** [comment]
My project builds now. I was using cmake_external, which as it turns out was the reason I was seeing the error about CMakeLists.txt not existing. All I needed was to use configure_make and provide the correct library dependency in shared_libraries. I left my [bazelLibsodiumTest repo](https://github.com/BloggerBust/bazelLibsodiumTest) up just in case it helps anyone else. It is a bare bones c++ project that uses libsodium as a dependency.

**Comment by irengrig** [comment]
Please see #285 , I hope it solves the problem!

Usage: load("@rules_foreign_cc//tools/build_defs:make.bzl", "make")
make(name = <name>, lib_source = <source>), please see more arguments in make.bzl

**Comment by irengrig** [comment]
Please look at my attempt to create an example for Luajit: 

Comment on the issue about building LuaJit: https://github.com/bazelbuild/rules_foreign_cc/issues/284#issuecomment-510137153

The demo pull request: https://github.com/bazelbuild/rules_foreign_cc/pull/291

**Comment by irengrig** [comment]
Closing as I believe #285 is the solution.
