### ISSUE TITLE
Ancillary binaries are confused by outer linkeropts

### ISSUE THREAD

**Issue by htuch** [bazelbuild/rules_foreign_cc#222]
I've recently been chasing down why Envoy's oss-fuzz build regressed in early Jan. There have been multiple issues, but one is related to our adoption of external_cmake, this can be seen in https://oss-fuzz-build-logs.storage.googleapis.com/log-ae2debc3-c07f-47aa-93ff-7eb4c9fe21af.txt.

The problem is that we have a fairly hokey invocation of Bazel, which you can see at https://github.com/google/oss-fuzz/blob/master/projects/envoy/build.sh. This is telling Bazel to use `-lFuzzingEnginer` everywhere. Unfortunately, `zlib`, when built under `external_cmake`, tries to do this with its test executables; that linker option is only safe to use with the target fuzzer binaries.

It might be reasonable to try and disable test binaries in `external_cmake` deps, but this doesn't work in general; e.g. zlib and c-ares don't support it by default, so we need to fix upstream, maybe a dep needs some host binary, etc.

I think one work around for us is to separate out the final link from Bazel, I'll look into this, but I'm interested the thoughts of others on the cleanest way to address this via either `external_cmake` support or changes to how we are structuring our fuzzer build.

CC @Dor1s

**Comment by irengrig** [comment]
As far as I can see, the -lFuzzingEngine gets on the command line from Bazel C++ toolchain as the part of the linkopts passed transitively to all targets.
I can create an attribute "linkopts_filter_out" for cmake_external rule for passing linker flags that should be filtered out (possibly we could have simple regexp there, like xxx* and *xxx).
Will it solve the problem? Do we need more generic approach?

**Comment by Dor1s** [comment]
I don't know how Bazel works :)

**Comment by htuch** [comment]
@irengrig the filter would work, but I'm not sure if that's the cleanest thing to do, this is why I'm asking the Bazel brains trust :) I have workaround for this in https://github.com/envoyproxy/envoy/pull/5843 and https://github.com/google/oss-fuzz/pull/2135 for now.
