### ISSUE TITLE
configure_make target cannot be specified as malloc library

### ISSUE THREAD

**Issue by lizan** [bazelbuild/rules_foreign_cc#227]
I've been trying to use `configure_make` with https://github.com/gperftools/gperftools, it could build but I cannot specify the `configure_make` target as malloc, workaround is write another `cc_library` to depend on the `configure_make`:
https://github.com/lizan/envoy/commit/9b8fb6e9ff41ca214e84928e25c72bf666ac0704#diff-cc0cb5c73ecf46a8066fc6a1d7d3096dR22

**Comment by irengrig** [comment]
Currently it is asserted by bazel, I created an issue for Bazel C/C++ team: https://github.com/bazelbuild/bazel/issues/8252

**Comment by UebelAndre** [comment]
This should stay open since it's linked to an upstream bug

**Comment by UebelAndre** [comment]
Pinging this once again

**Comment by hcoona** [comment]
any progress or workaround?

**Comment by jsharpe** [comment]
Workaround was suggested in the original report but the linked commit no longer exists. If you care about this then ping the upstream issue at https://github.com/bazelbuild/bazel/issues/8252 as this is a bazel core issue.
