### ISSUE TITLE
Bazel incompatible changes

### ISSUE THREAD

**Issue by laurentlb** [bazelbuild/rules_foreign_cc#228]
According to our CI, rules_foreign_cc doesn't build with incompatible flags, e.g.
https://buildkite.com/bazel/bazel-at-release-plus-incompatible-flags/builds/110#a3aa54f6-e49c-44a1-bdad-8f6902a05c9d

To test all flags, you can use:
  `bazelisk --migrate`

(https://github.com/philwo/bazelisk)

**Comment by laurentlb** [comment]
cc @irengrig

**Comment by irengrig** [comment]
Fixed by #231
