### ISSUE TITLE
executable rule?

### ISSUE THREAD

**Issue by UlysseM** [bazelbuild/rules_foreign_cc#238]
Hi,

First, thanks for doing this rule, it's definitely an improvement over our previous pipeline!

When trying to build libjpeg-turbo, I found out that I needed nasm.
I then found out that while I could build nasm (after adding a macro to patch bazel's ?), I had no easy way to use the result of the `configure_make` as a binary, and had to hack it with a `genrule`. It works, but I'm not sure if I'm doing this the right way (I couldn't find a way to make the output of `configure_make` executable).

Would it be possible to, say, if there is only one entry in "binaries", make these rules executable?

Thanks !

For those who are interested, here is what I ended up doing.
BUILD
```
load("@rules_foreign_cc//tools/build_defs:configure.bzl", "configure_make")

configure_make(
    name = "nasm_build",
    # nasm contains a macro __DATE__ which would cause the build to be not reproducible
    # bazel replace these macro with 'redacted'.
    # Somehow, it would have been remplaced in this library without quote, so we'll add another
    # macro to add the quotes.
    configure_options = ["CFLAGS='-Dredacted=\"redacted\"'"],
    lib_source = "@nasm_src//:all",
    out_bin_dir = "bin",
    binaries = ["nasm"],
)

genrule(
    name = "nasm",
    srcs = ["//:nasm_build"],
    outs = ["nasm"],
    cmd = "cp `ls $(locations //:nasm_build) | grep /bin/nasm$$` $(@)",
    executable = True,
)

configure_make(
    name = "libjpeg_turbo",
    configure_options = ["--with-jpeg8"],
    lib_source = "@libjpeg_turbo_src//:all",
    out_lib_dir = "lib",
    static_libraries = ["libjpeg.a"],
    tools_deps = ["//:nasm"],
)
```
with the workspace
```
http_archive(
    name = "nasm_src",
    build_file_content = all_content,
    strip_prefix = "nasm-2.14.02",
    urls = ["http://www.nasm.us/pub/nasm/releasebuilds/2.14.02/nasm-2.14.02.tar.xz"],
)

http_archive(
   name = "libjpeg_turbo_src",
   build_file_content = all_content,
   strip_prefix = "libjpeg-turbo-1.5.2",
   urls = ["http://downloads.sourceforge.net/libjpeg-turbo/libjpeg-turbo-1.5.2.tar.gz"],
)
```

**Comment by irengrig** [comment]
Please have a look at example here: https://github.com/bazelbuild/rules_foreign_cc/blob/master/examples/apache_httpd/BUILD

there's relevant tricks on how to select files with output_group and how to construct LD_LIBRARY_PATH for passing shared libraries locations.

**Comment by irengrig** [comment]
Closing as working with even 2 ways to do it:)

**Comment by filmil** [comment]
> Please have a look at example here: https://github.com/bazelbuild/rules_foreign_cc/blob/master/examples/apache_httpd/BUILD

It's a 404 today.

What would be a new link?

**Comment by snakethatlovesstaticlibs** [comment]
Looking at the git history: https://github.com/bazelbuild/rules_foreign_cc/blob/6b04da2262f92135abc98953fe3f5ab5004ab1e6/examples/apache_httpd/BUILD
