### ISSUE TITLE
Don't set --prefix to a subdirectory of where you're building.

### ISSUE THREAD

**Issue by rnburn** [bazelbuild/rules_foreign_cc#240]
I'm building apache with configure_make. The config log shows that the prefix is set to `tmp/tmp.jocLKX7QSG/./httpd`

```
configure: summary of build options:

    Server Version: 2.4.38
    Install prefix: /tmp/tmp.jocLKX7QSG/./httpd
```

But the project is building in `/tmp/tmp.jocLKX7QSG/` and already generates an `httpd` dir as part of the build, so it fails later with

```
mkdir /tmp/tmp.jocLKX7QSG/./httpd
mkdir: cannot create directory '/tmp/tmp.jocLKX7QSG/./httpd': File exists
```

I was able to work around this by changing the `name` attribute to something other than `httpd`, but it would be much better to keep the installation directory totally separate from the build directory so there's no possibility of clashing.

**Comment by irengrig** [comment]
Hello @rnburn, thank you for the feedback!
There is an attiribute of configure_make that you could use to set the --prefix:

`        # Install prefix, i.e. relative path to where to install the result of the build.
        # Passed to the 'configure' script with --prefix flag.
        "install_prefix": attr.string(mandatory = False),
`
Hope it helps.

**Comment by irengrig** [comment]
Closing this one: I think having install prefix set to the library name (or target name is library name is not given) is a good default - and there is an attribute to override this.

I also found out that configure_make script is creating installation directory: https://github.com/bazelbuild/rules_foreign_cc/blob/3831409fd50e77a4c029bc42b2c77eb294f5e0f5/tools/build_defs/framework.bzl#L247
but when I remove this line (and change the name of the target to "httpd" - I have this in ./examples/apache_httpd) - the build still fails complaining that the directory already exists - so this is really the issue of the script not accepting installation prefix to be 'httpd'.
