### ISSUE TITLE
Unable to 'source' function definitions from files local to the project inside configure script

### ISSUE THREAD

**Issue by mancini0** [bazelbuild/rules_foreign_cc#243]
Hello - I'm trying to build librdkafka using configure_make. The library uses mklove instead of autoconf, and mklove is distributed alongside the source code.   One of the early steps of the configure script is sourcing the mklove bash functions, defined in the file "mklove/modules/configure.base", where the mklove directory is inside the project folder and at the same level as the configure script.

```
librdkafka
  - configure
  - mklove/...
  - other files
```

```
#!/usr/bin/env bash
# Load base module
source mklove/modules/configure.base
...
mkl_in_list <do stuff>
... 
```
The build fails with command not found errors, since the mklove/modules/configure.base is not found.

Inside of a configure script, how does one 'source' definitions from files relative to the scripts location? 

__________________________PKG_CONFIG_PATH=
/home/ronmexico/.cache/bazel/_bazel_ronmexico/dc9d11a71c518156e18cc15c4d21f77b/sandbox/linux-sandbox/2/execroot/orderinbound/external/kafka/configure: line 15: **mklove/modules/configure.base: No such file or directory**
/home/ronmexico/.cache/bazel/_bazel_ronmexico/dc9d11a71c518156e18cc15c4d21f77b/sandbox/linux-sandbox/2/execroot/orderinbound/external/kafka/configure: line 19: **mkl_in_list: command not found**
/home/ronmexico/.cache/bazel/_bazel_ronmexico/dc9d11a71c518156e18cc15c4d21f77b/sandbox/linux-sandbox/2/execroot/orderinbound/external/kafka/configure: line 21: mkl_in_list: command not found

**Comment by promiseofcake** [comment]
@mancini0 -- how did you move path this?

**Comment by mancini0** [comment]
@promiseofcake librdkafka provides a cmake build as well, so I was able to build it using rules_foreign_cc's cmake rules. I closed this issue because I was unsure if it was an actual gap or if I just didn't read the manual close enough...are you hitting the same issue?

**Comment by irengrig** [comment]
Hi @mancini0, thanks for reporting this!
I think you should try "configure_in_place" attribute: https://github.com/bazelbuild/rules_foreign_cc/blob/9c6480858ae8f62d760807b3a1f33b7d67c89fac/tools/build_defs/configure.bzl#L82

This will make the configure script be executed in its parent directory, so any relative paths will be correct.

**Comment by promiseofcake** [comment]
@mancini0 right now we are  building librdkafka through some hand-coded native cc_ rules. We are then using the targets to build the Confluent Go package but it seems a little brittle. I was investigating to see if moving to this made more sense and you're right, we should be able to use the native cmake. Thanks.

**Comment by mancini0** [comment]
@promiseofcake  Coincidentally, I also wanted to use Confluent's go kafka library inside one of my microservices. I have been unable to link the outputs of the librdkafka cmake build with the go library, however, I have [an open question](https://stackoverflow.com/questions/55698979/bazel-rules-go-linking-go-binary-against-a-static-c-library-a-file-produce) related to this on stackoverflow , perhaps you could answer that? That link will also show you how I used the cmake bazel rule to build librdkafka.

@irengrig  Thanks, the attribute you mention is likely what I was looking for.

**Comment by MaruHyl** [comment]
@irengrig Still fail.
Output:
```
make[1]: Entering directory `/root/.cache/bazel/_bazel_root/699ab69f21a6635cf3a7aafa123bbf87/sandbox/processwrapper-sandbox/48/execroot/test/external/com_github_edenhill_librdkafka/src'
cc -MD -MP   -c rdkafka.c -o rdkafka.o
In file included from rd.h:56:0,
                 from rdkafka_int.h:44,
                 from rdkafka.c:38:
tinycthread.h:32:10: fatal error: ../config.h: No such file or directory
 #include "../config.h"
          ^~~~~~~~~~~~~
compilation terminated.
make[1]: *** [rdkafka.o] Error 1
make[1]: Leaving directory `/root/.cache/bazel/_bazel_root/699ab69f21a6635cf3a7aafa123bbf87/sandbox/processwrapper-sandbox/48/execroot/test/external/com_github_edenhill_librdkafka/src'
make: *** [libs] Error 2
```
the `config.h` generated by configure is in `BUILD_TMPDIR`, not in `/root/.cache/bazel/_bazel_root/699ab69f21a6635cf3a7aafa123bbf87/sandbox/processwrapper-sandbox/48/execroot/test/external/com_github_edenhill_librdkafk`

**Comment by MaruHyl** [comment]
@irengrig 
```
/tmp/tmp.MT40dh9F2C
├── BUILD.bazel -> /root/.cache/bazel/_bazel_root/699ab69f21a6635cf3a7aafa123bbf87/sandbox/processwrapper-sandbox/48/execroot/test/external/com_github_edenhill_librdkafka/BUILD.bazel
├── CMakeLists.txt -> /root/.cache/bazel/_bazel_root/699ab69f21a6635cf3a7aafa123bbf87/sandbox/processwrapper-sandbox/48/execroot/test/external/com_github_edenhill_librdkafka/CMakeLists.txt
├── CODE_OF_CONDUCT.md -> /root/.cache/bazel/_bazel_root/699ab69f21a6635cf3a7aafa123bbf87/sandbox/processwrapper-sandbox/48/execroot/test/external/com_github_edenhill_librdkafka/CODE_OF_CONDUCT.md
├── config.cache
├── config.h.    <---- * here!
├── config.log
├── config.log.old
................................
```

**Comment by artemyarulin** [comment]
Hi all, alternative way is to use cmake approch
```
http_archive(
    name = "librdkafka",
    strip_prefix = "librdkafka-1.3.0",
    urls = ["https://github.com/edenhill/librdkafka/archive/v1.3.0.tar.gz"],
    build_file_content = all_content,
    sha256 = "465cab533ebc5b9ca8d97c90ab69e0093460665ebaf38623209cf343653c76d2"
)

cmake_external(
  name = "librdkafka",
  lib_source = "@librdkafka//:all", 
  static_libraries = ["librdkafka++.a", "librdkafka.a"],
  cache_entries = {
    "RDKAFKA_BUILD_STATIC": "ON", 
    "WITH_ZSTD": "OFF", 
    "WITH_SSL": "OFF", 
    "WITH_SASL": "OFF", 
    "ENABLE_LZ4_EXT": "OFF", 
    "WITH_LIBDL": "OFF", 
    "WITH_ZLIB": "OFF"
})

# Ensure to use linkstatic for your libs depending on librdkafka
cc_library(name = "kafka", srcs = ["kafka.cc"], hdrs = ["kafka.h"], deps = [":librdkafka"], linkstatic=True)

**Comment by MaruHyl** [comment]
@artemyarulin thanks! But note that `The cmake build mode is experimental and not officially supported`.
