### ISSUE TITLE
libnl doesn't build with configure_make

### ISSUE THREAD

**Issue by Ragora** [bazelbuild/rules_foreign_cc#272]
I'm sure this is indicative is a problem outside of simply "libnl doesn't build" I just don't know what the root cause actually is.

When attempting to build libnl-1.1.4 using configure_make (the .tar.gz at https://www.infradead.org/~tgr/libnl/files/libnl-1.1.4.tar.gz ) it fails to build because it cannot find the Makefile once it runs configuration.

The output is below:
```
Loading: 
Loading: 0 packages loaded
Analyzing: 6 targets (0 packages loaded, 0 targets configured)
INFO: Analyzed 6 targets (0 packages loaded, 0 targets configured).
INFO: Found 5 targets and 1 test target...
[0 / 9] [-----] CcConfigureMakeRule external/libnl/library/include
ERROR: /root/.cache/bazel/_bazel_root/697d6ba340055fca6ef81da4c7b91113/external/libnl/BUILD.bazel:19:1: error executing shell command: '/bin/bash -c function cleanup_function() {
local ecode=$?
if [ $ecode -eq 0 ]; then
cleanup_on_success
else
cleanup_on_failure
fi
}
set -e
function cleanup_on_success() {
printf "rules_foreign_cc: ...' failed (Exit 2) bash failed: error executing command /bin/bash -c ... (remaining 1 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox

rules_foreign_cc: Build failed!
rules_foreign_cc: Keeping temp build directory  and dependencies directory  for debug.
rules_foreign_cc: Please note that the directories inside a sandbox are still cleaned unless you specify '--sandbox_debug' Bazel command line flag.

rules_foreign_cc: Printing build logs:

_____ BEGIN BUILD LOGS _____
Bazel external C/C++ Rules #0.0.8. Building library 'library'
Environment:______________TMPDIR=/tmp
EXT_BUILD_ROOT=/root/.cache/bazel/_bazel_root/697d6ba340055fca6ef81da4c7b91113/sandbox/linux-sandbox/1/execroot/__main__
INSTALLDIR=/root/.cache/bazel/_bazel_root/697d6ba340055fca6ef81da4c7b91113/sandbox/linux-sandbox/1/execroot/__main__/bazel-out/k8-fastbuild/bin/external/libnl/library
PATH=/root/.cache/bazel/_bazel_root/697d6ba340055fca6ef81da4c7b91113/sandbox/linux-sandbox/1/execroot/__main__:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
BUILD_TMPDIR=/tmp/tmp.2ezONwkdLp
PWD=/root/.cache/bazel/_bazel_root/697d6ba340055fca6ef81da4c7b91113/sandbox/linux-sandbox/1/execroot/__main__
EXT_BUILD_DEPS=/root/.cache/bazel/_bazel_root/697d6ba340055fca6ef81da4c7b91113/sandbox/linux-sandbox/1/execroot/__main__/bazel_foreign_cc_deps_library
SHLVL=2
BUILD_LOG=bazel-out/k8-fastbuild/bin/external/libnl/library/logs/Configure.log
BUILD_SCRIPT=bazel-out/k8-fastbuild/bin/external/libnl/library/logs/Configure_script.sh
_=/usr/bin/env

PKG_CONFIG_PATH=
checking for gcc... /usr/bin/gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether /usr/bin/gcc accepts -g... yes
checking for /usr/bin/gcc option to accept ISO C89... none needed
checking for a BSD-compatible install... /usr/bin/install -c
checking for an ANSI C-conforming const... yes
checking for inline... inline
checking for pow in -lm... yes
checking for pthread_mutex_lock in -lpthread... yes
configure: creating ./config.status
config.status: creating Makefile.opts
config.status: WARNING:  '/root/.cache/bazel/_bazel_root/697d6ba340055fca6ef81da4c7b91113/sandbox/linux-sandbox/1/execroot/__main__/external/libnl/libnl-1.1.4/Makefile.opts.in' seems to ignore the --datarootdir setting
config.status: creating libnl-1.pc
config.status: creating doc/Doxyfile
config.status: creating lib/defs.h

----------------------------------------------------------------------
SUMMARY:

Included in Compilation:
  libnl:   Yes  -lm -lpthread

Dependencies:
  libm             Yes       (required)
make: *** No targets specified and no makefile found.  Stop.

_____ END BUILD LOGS _____
rules_foreign_cc: Build script location: bazel-out/k8-fastbuild/bin/external/libnl/library/logs/Configure_script.sh
rules_foreign_cc: Build log location: bazel-out/k8-fastbuild/bin/external/libnl/library/logs/Configure.log

INFO: Elapsed time: 1.253s, Critical Path: 0.54s
INFO: 0 processes.
FAILED: Build did NOT complete successfully
<PROJECT NAME>                                     NO STATUS

Executed 0 out of 1 test: 1 was skipped.
FAILED: Build did NOT complete successfully
```

The temporary directory it creates to run Make contains:
```
ragora@Kiaro:/tmp/2lFYBpGRJR$ ls
config.log  config.status  doc  lib  libnl-1.pc  Makefile.opts
```

Meaning it seems to somehow fail to copy not only the program source code but also the original Makefile it's supposed to invoke after it ran the configure script.

The following code should reproduce it:

In WORKSPACE:

```
git_repository(
    name = "rules_foreign_cc",
    remote = "https://github.com/bazelbuild/rules_foreign_cc.git",
    commit = "6b2f454a41dc1d59607718224438d66ad4f4ddbc"
)

load("@rules_foreign_cc//:workspace_definitions.bzl", "rules_foreign_cc_dependencies")

rules_foreign_cc_dependencies(register_default_tools=True)

http_archive(
    name = "libnl",
    urls = ["https://www.infradead.org/~tgr/libnl/files/libnl-1.1.4.tar.gz"],
    sha256 = "4f80c21fe5bbcdde6e72b59b4f98306063a41421f909887c34e58d93e746d063",
    build_file = "libnl.BUILD"
)
```

In libnl.BUILD:

```
load("@rules_foreign_cc//tools/build_defs:configure.bzl", "configure_make")

filegroup(
    name = "payload",
    srcs = glob(["libnl-1.1.4/**"])
)

configure_make(
    name = "library",
    lib_source = ":payload", # It behaves the same even if you don't use a separate target and simply use a workspace path directly, this was a debug step.
    visibility = ["//visibility:public"],

    alwayslink = True,

    static_libraries = ["lib/libnl.a"],
)
```

It works fine if I try other libraries (even libnl3 appears to work, actually).

**Comment by irengrig** [comment]
Hi @Ragora , thank you for reporting the issue.
I played with it a bit, did some modifications:
1) I use the same pattern for selecting all external repository contents as in examples of rules_foreign_cc - seems I should fix something with the "root" detection
2) configure script needs to be invoked in the exact directory where the sources are (maybe I should make it a default for rules_foreign_cc)

After that, I get the code:
WORKSPACE:
git_repository(
    name = "rules_foreign_cc",
    remote = "https://github.com/bazelbuild/rules_foreign_cc.git",
    commit = "6b2f454a41dc1d59607718224438d66ad4f4ddbc"
)
load("@rules_foreign_cc//:workspace_definitions.bzl", "rules_foreign_cc_dependencies")

rules_foreign_cc_dependencies(register_default_tools = True)

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

all_content = """filegroup(name = "all", srcs = glob(["**"]), visibility = ["//visibility:public"])"""

http_archive(
    name = "libnl",
    build_file_content = all_content,
    sha256 = "4f80c21fe5bbcdde6e72b59b4f98306063a41421f909887c34e58d93e746d063",
    strip_prefix = "libnl-1.1.4",
    urls = ["https://www.infradead.org/~tgr/libnl/files/libnl-1.1.4.tar.gz"],
)
BUILD:
load("@rules_foreign_cc//tools/build_defs:configure.bzl", "configure_make")

configure_make(
    name = "library",
    configure_in_place = True,
    lib_source = "@libnl//:all",  # It behaves the same even if you don't use a separate target and
    static_libraries = ["libnl.a"],
    # simply use a workspace path directly, this was a debug step.
    visibility = ["//visibility:public"],
    alwayslink = True,
)

After that, I moved further with the build, but there is still a problem:
SUMMARY:

Included in Compilation:
  libnl:   Yes  -lm -lpthread

Dependencies:
  libm             Yes       (required)
Entering lib
  MAKE .so.
make[2]: *** No rule to make target '../Makefile.opts', needed by '.so.'.  Stop.
make[2]: *** No rule to make target '../Makefile.opts', needed by '.a'.  Stop.
Makefile:47: recipe for target 'all' failed
make[1]: *** [all] Error 2
Makefile:20: recipe for target 'all' failed
make: *** [all] Error 2

So, apparently, the distribution includes "../Makefile.opts.in", not ../Makefile.opts

I guess calling the conversion can be included into script, but I am not sure how exactly.
I.e. not only "configure && make" should be called, but "configure && convert Makefile.opts && make"
