### ISSUE TITLE
platform-specific .so rules

### ISSUE THREAD

**Issue by sayrer** [bazelbuild/rules_foreign_cc#283]
In the example directory,

```
configure_make(
    name = "pcre",
    lib_source = "@pcre//:all",
    static_libraries = ["libpcre.a"],
    shared_libraries = ["libpcre.so.1"],
)
```

fails to build for me on macOS, because the shared_library produced is `libpcre.1.dylib`. It would be nice to let shared library outputs be specified as triples, and rearranged for each platform (I suspect .dll on windows causes similar problems).

This isn't an issue with Bazel's native cc rules: those seem to generate .so no matter what.

**Comment by artemyarulin** [comment]
Having the same issue. I wonder if we can utilise Starlark to introduce some kind of if to select which lib name to use?

**Comment by artemyarulin** [comment]
Yes, using helper from https://docs.bazel.build/versions/master/platforms.html it works just fine, [random example](https://github.com/adam-rocska/rules_php/blob/30944cc9cebfb05a35d9585736a4d645475eccc9/php/BUILD#L15) from Github
```
 shared_libraries = select({
        "@bazel_tools//src/conditions:windows": [
            "libcharset.dll",
            "libiconv.dll"
        ],
        "@bazel_tools//src/conditions:darwin": [
            "libcharset.dylib",
            "libiconv.dylib"
        ],
        "//conditions:default": [
            "libcharset.so",
            "libiconv.so"
        ],
    }),
```
