### ISSUE TITLE
configure_make building GMP: Cannot Find C++ Compiler

### ISSUE THREAD

**Issue by Dig-Doug** [bazelbuild/rules_foreign_cc#296]
Hi, I'm trying to build the GMP library with C and C++ support. The C builds fine, however, when I try to enable the C++ support the build fails.

If I run the standard `configure` and `make` in the downloaded archive outside of bazel, it works without any issues.

Here's more info about my setup:

- I'm using bazel 0.28.0. 

```python
# WORKSPACE
http_archive(
    name = "libgmp",
    build_file_content = ALL_CONTENT,
    sha256 = "87b565e89a9a684fe4ebeeddb8399dce2599f9c9049854ca8c0dfbdea0e21912",
    strip_prefix = "gmp-6.1.2",
    urls = [
        "https://gmplib.org/download/gmp/gmp-6.1.2.tar.xz",
    ],
)
```

```python
# BUILD
configure_make(
    name = "libgmp",
    configure_options = [
        "--enable-cxx",
    ],
    lib_source = "@libgmp//:all",
    shared_libraries = ["libgmp.so.10"],
    static_libraries = [
        "libgmp.a",
        "libgmpxx.a",
    ],
)
```

```
# bazel-genfiles/libgmp/logs/Configure.log
Bazel external C/C++ Rules #0.0.8. Building library 'libgmp'
Environment:______________EXT_BUILD_ROOT=/home/doug/.cache/bazel/_bazel_doug/9ac7162f67ac3d0fbc3f9ecceb35e9c8/sandbox/linux-sandbox/19/execroot/grid
INSTALLDIR=/home/doug/.cache/bazel/_bazel_doug/9ac7162f67ac3d0fbc3f9ecceb35e9c8/sandbox/linux-sandbox/19/execroot/grid/bazel-out/k8-fastbuild/bin/libgmp
PWD=/home/doug/.cache/bazel/_bazel_doug/9ac7162f67ac3d0fbc3f9ecceb35e9c8/sandbox/linux-sandbox/19/execroot/grid
BUILD_TMPDIR=/tmp/tmp.tXSvOe0Qdg
TMPDIR=/tmp
EXT_BUILD_DEPS=/home/doug/.cache/bazel/_bazel_doug/9ac7162f67ac3d0fbc3f9ecceb35e9c8/sandbox/linux-sandbox/19/execroot/grid/bazel_foreign_cc_deps_libgmp
SHLVL=2
BUILD_LOG=bazel-out/k8-fastbuild/bin/libgmp/logs/Configure.log
BUILD_SCRIPT=bazel-out/k8-fastbuild/bin/libgmp/logs/Configure_script.sh
PATH=/home/doug/.cache/bazel/_bazel_doug/9ac7162f67ac3d0fbc3f9ecceb35e9c8/sandbox/linux-sandbox/19/execroot/grid:/home/doug/.yarn/bin:/home/doug/.config/yarn/global/node_modules/.bin:/home/doug/.cargo/bin:/usr/local/bin:/home/doug/.nvm/versions/node/v10.16.0/bin:/home/doug/.cargo/bin:/home/doug/bin:/home/doug/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/doug/Development/go/bin
_=/usr/bin/env
__________________________PKG_CONFIG_PATH=
checking build system type... kabylake-pc-linux-gnu
checking host system type... kabylake-pc-linux-gnu
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... no
checking for mawk... mawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether to enable maintainer-specific portions of Makefiles... no
checking ABI=64
checking compiler /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -fno-canonical-system-headers -Wno-builtin-macro-redefined -D__DATE__="redacted" -D__TIMESTAMP__="redacted" -D__TIME__="redacted" ... yes
checking for gcc... /usr/bin/gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether /usr/bin/gcc accepts -g... yes
checking for /usr/bin/gcc option to accept ISO C89... none needed
checking whether /usr/bin/gcc understands -c and -o together... yes
checking for /usr/bin/gcc option to accept ISO C99... none needed
checking for /usr/bin/gcc option to accept ISO Standard C... (cached) none needed
checking how to run the C preprocessor... /usr/bin/gcc -E
checking build system compiler /usr/bin/gcc... yes
checking for build system preprocessor... /usr/bin/gcc -E
checking for build system executable suffix... 
checking whether build system compiler is ANSI... yes
checking for build system compiler math library... -lm
checking whether we are using the GNU C++ compiler... yes
checking whether /usr/bin/gcc accepts -g... yes
checking C++ compiler /usr/bin/gcc  -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -std=c++0x -fno-canonical-system-headers -Wno-builtin-macro-redefined -D__DATE__="redacted" -D__TIMESTAMP__="redacted" -D__TIME__="redacted" -std=c++14... no, std iostream
configure: error: C++ compiler not available, see config.log for details
```

```
# End of config.log from tmp dir
...

pdfdir='${docdir}'
prefix='/tmp/tmp.tXSvOe0Qdg/libgmp'
program_transform_name='s,x,x,'
psdir='${docdir}'
sbindir='${exec_prefix}/sbin'
sharedstatedir='${prefix}/com'
sysconfdir='${prefix}/etc'
target_alias=''

## ----------- ##
## confdefs.h. ##
## ----------- ##

/* confdefs.h */
#define PACKAGE_NAME "GNU MP"
#define PACKAGE_TARNAME "gmp"
#define PACKAGE_VERSION "6.1.2"
#define PACKAGE_STRING "GNU MP 6.1.2"
#define PACKAGE_BUGREPORT "gmp-bugs@gmplib.org, see https://gmplib.org/manual/Reporting-Bugs.html"
#define PACKAGE_URL "http://www.gnu.org/software/gmp/"
#define PACKAGE "gmp"
#define VERSION "6.1.2"
#define WANT_FFT 1
#define HAVE_HOST_CPU_kabylake 1
#define HAVE_SPEED_CYCLECOUNTER 2
#define HAVE_CALLING_CONVENTIONS 1

configure: exit 1
```

Do you have any suggestions on how I can fix this issue?

Please let me know if you need more information.

Thanks!

**Comment by phst** [comment]
This is somewhat subtle: by default, the linker command doesn't link against the standard C++ library. Then the `configure` step which tries to link a trivial C++ binary fails even though the compiler is present. So you can add e.g. `configure_env_vars = {"CXXFLAGS": "-lstdc++"}` to the `configure_make` rule (or `-lc++` when using libc++ instead of libstdc++).

It would be nice if `foreign_rules_cc` did the right thing automatically, though.

I also haven't found a way to view the `config.log` file mentioned in the `configure` output; apparently Bazel deletes it even with `--debug_sandbox`.

**Comment by Dig-Doug** [comment]
Thanks for looking at this. Adding `CXXFLAGS` didn't work for me, however you gave me enough of a pointer to find a solution. :)

I compared the configure logs from building inside and outside bazel and noticed that the CXX value was different. Setting it manually solved the issue:

```bash
configure_make(
    name = "libgmp",
    configure_env_vars = {
        # See https://github.com/bazelbuild/rules_foreign_cc/issues/296
        "CXX": "g++",
    },
    configure_options = [
        "--enable-cxx",
    ],
    lib_source = "@libgmp//:all",
    shared_libraries = ["libgmp.so.10"],
    static_libraries = [
        "libgmp.a",
        "libgmpxx.a",
    ],
)
```

Also, to see the `config.log` file, what you need to do is look `BUILD_TMPDIR` in the console output:

```
_____ BEGIN BUILD LOGS _____
...
BUILD_TMPDIR=/tmp/tmp.h2Ni07IAxV
...

```

Look inside that directory and you should see it.

Having to set `configure_env_vars` seems like an issue to me, so I'm leaving this open.

**Comment by phst** [comment]
> Adding CXXFLAGS didn't work for me

Yeah, I guess it depends a lot on the toolchain what works and what doesn't.

IIUC the reason (at least on macOS) is that the compiler is some Clang wrapper which gets called with different flags depending on whether C++ files are listed on the commandline. This heuristic only works for the native `cc_library` etc. rules, but not here.

**Comment by mobileink** [comment]
FYI, same problem on MacOS (Catalina).  This works for me:

configure_make( ## macos
    name = "libgmp",
    visibility = ["//visibility:public"],
    configure_env_vars = { "AR": "", "CXXFLAGS": "-lstdc++"},
    configure_options = [ "--enable-cxx", "CFLAGS=-Dredacted"],
    lib_source = "@libgmp//:all",
    out_lib_dir = "lib",
    shared_libraries = ["libgmp.dylib"],
    static_libraries = ["libgmp.a", "libgmpxx.a"],
)

Without the CFLAGS bit I get:

../gmp.h:2327:417: error: invalid suffix on literal; C++11 requires a space between literal and identifier [-Wreserved-user-defined-literal]
#define __GMP_CFLAGS "-D_FORTIFY_SOURCE=1 -fstack-protector -fcolor-diagnostics -Wall -Wthread-safety -Wself-assign -fno-omit-frame-pointer -O0 -DDEBUG -isysroot __BAZEL_XCODE_SDKROOT__ -F__BAZEL_XCODE_SDKROOT__/System/Library/Frameworks -F__BAZEL_XCODE_DEVELOPER_DIR__/Platforms/MacOSX.platform/Developer/Library/Frameworks -mmacosx-version-min=10.15 -no-canonical-prefixes -Wno-builtin-macro-redefined -D__DATE__="redacted" -D__TIMESTAMP__="redacted" -D__TIME__="redacted""

Note the last three -D params, added by bazel.  They need spacing for C++11.  The only way I could find to get around this is by redefining 'redacted' to null.  Only took me about a day to figure that one out.

**Comment by jonathan-enf** [comment]
I had the same issue, and my workaround:

```
configure_make(
    name = "libgmpxx",
    lib_source = ":gmp_all",
    out_static_libs = ['libgmpxx.a'],
    out_shared_libs = ['libgmpxx.so'],
    configure_options = ['--enable-cxx'],
    # see https:/github.com/bazelbuild/rules_foreign_cc/issues/296
    configure_env_vars = {
      "CXX": "g++-10",
      "CXXFLAGS": "-lstdc++",
    },
    visibility = ["//visibility:public"]
)
```

It would be nice if there was a way for rules_foreign_cc to do the right thing out of the box.

**Comment by UebelAndre** [comment]
> It would be nice if there was a way for rules_foreign_cc to do the right thing out of the box.

Agreed! If you've come across anything you think should be updated to help make the rules easier to use, I'd be glad to collaborate on a pull request 😄 

But thanks for posting your findings here, very much appreciated!
