### ISSUE TITLE
Cross-compile?

### ISSUE THREAD

**Issue by terrisgit** [bazelbuild/rules_foreign_cc#297]
I have a Bazel project that needs to build Boost etc. for Raspberry Pi on Ubuntu. I am using rules_foreign_cc today successfully to build both boost b2 and CMake projects but haven't yet tried cross compilation. How much trouble do you suppose I'm in for?

I was about to embark on a project following the approach described here:
https://jpieper.com/2018/10/28/configuring-bazel-to-cross-compile-for-the-raspberry-pi-3/

**Comment by oquenchil** [comment]
Hey Terris,

I think the best would be for you to try and let us know of any issues you have so that we can try helping you. We are not aware of any blockers that might prevent you from following along with that blog post.

Good luck!

**Comment by irengrig** [comment]
Hello @terrisgit , yes, this is the right direction.

One should use the general approach for cross compiling C++ projects in Bazel, rules_foreign_cc are  taking all the cross compilation information from Bazel C++ toolchain.
CMake toolchain file (CMAKE_TOOLCHAIN_FILE) is created under cover by the rules_foreign_cc from the values in Bazel C++ toolchain.

**Comment by terrisgit** [comment]
That is very encouraging. Thank you!

**Comment by terrisgit** [comment]
It did not go well. https://github.com/bazelbuild/rules_foreign_cc/issues/297

**Comment by terrisgit** [comment]
I had to modify boost/BUILD and add to user_options.

```
 user_options = [
        ...
        "toolset=clang-arm",
```

**Comment by terrisgit** [comment]
I was not able to get it to work with CMake projects either. https://github.com/mjbots/rpi_bazel/issues/3 updated

**Comment by terrisgit** [comment]
https://github.com/dev-guy/pi-bazel-boost-vsomeip

**Comment by irengrig** [comment]
@terrisgit you can run "bazel build --spawn_strategy=standalone" for the execution without sandbox.
As a result, all the intermediate build files will be left in place, and you can explore them.

As far as I can tell by the message, it is something with the crosstool configuration itself, as CMake can not successfully compile some simple test program using the tools and flags passed to it.

Also, there should be the full script file used by cmake_external in ./bazel-gen/<package>/<library-name>/logs/ directory, this may help.

**Comment by terrisgit** [comment]
Thank you for the reply. I will add --spawn_strategy=standalone to .bazelrc.

TL/DR: Neither CMake nor Boost work with mjbots/ripi_bazel 

If there's an alternative to getting these to cross-compile for the Pi and other platforms, I will use that instead. I just can't find anything. I'm not waiting for it - I want to grease the wheels for everyone in the IoT/embedded industry. The issues I've encountered are impediments to using Bazel.

**Comment by terrisgit** [comment]
Update: These two projects, mjbots/rpi_bazel and bazelbuild/rules_foreign_cc are philosophically opposed. There are now several repos that aren't bazelbuild organization which attempt to wrap CMake and b2 projects with Bazel. Without official bazelbuild support, they are all at risk of being abandoned. I guess I need to better understand what rpi_bazel is doing and try to make it work with rules_foreign_cc. That seems like the only long-term path forward.
