### ISSUE TITLE
windows build is red on Bazel CI

### ISSUE THREAD

**Issue by buchgr** [bazelbuild/rules_foreign_cc#299]
https://buildkite.com/bazel/rules-foreign-cc/builds/445

**Comment by meteorcloudy** [comment]
This is due to some infrastructure change on CI, green again with Bazel@HEAD
https://buildkite.com/bazel/bazel-at-head-plus-disabled/builds/253#_

**Comment by irengrig** [comment]
Thank you, Yun! Can we close this then?

**Comment by meteorcloudy** [comment]
Yes!
