### ISSUE TITLE
Propagating compiler -D'efines to dependent native bazel cc_library components from cmake_external dependencies?

### ISSUE THREAD

**Issue by wrowe** [bazelbuild/rules_foreign_cc#301]
Simple case, the grpc/grpc component compiles against the c-ares project, built using
foreign_cc with the following syntax, and we have listed CARES_STATICLIB as defines to
prevent the symbols from being imported when linking monolithicly;

```
envoy_cmake_external(
    name = "ares",
    cache_entries = {
        "CARES_SHARED": "no",
        "CARES_STATIC": "on",
        "CARES_MSVC_STATIC_RUNTIME": "on",
        "CMAKE_BUILD_TYPE": "RelWithDebInfo",
    },
    copy_pdb = True,
    lib_source = "@com_github_c_ares_c_ares//:all",
    pdb_name = "c-ares",
    static_libraries = select({
        "//bazel:windows_x86_64": ["cares.lib"],
        "//conditions:default": ["libcares.a"],
    }),
    defines = ["CARES_STATICLIB"],
)
```

This is documented in https://github.com/bazelbuild/rules_foreign_cc/blob/master/README.md
```
    # Optional compilation definitions to be passed to the dependencies of this library.
    # They are NOT passed to the compiler, you should duplicate them in the configuration options.
    "defines": attr.string_list(mandatory = False, default = []),
```
Looking at the behavior of core bazel logic, it makes sense that these defines are not passed to the object they are declared in, but to all the dependent components and should be in the compiler options of those dependencies. E.g. a dynamic library object compilation might declare an EXPORT stub in building the component. But all dependent components must use a corresponding (different) IMPORT stub, which is one purpose of this defines=[] list.

In bazel/envoy_build_system.bzl envoy_cmake_external(), the **kwargs argument including any defines list is passed on to cmake_external().

This component is consumed then by a grpc/grpc rule which compiles against the resulting ares.h header file and requires that define noted above;
```
def _com_github_grpc_grpc():
    _repository_impl("com_github_grpc_grpc")
    native.bind(
        name = "cares",
        actual = "//external:ares",
    )
```

In spite of this, we see the following error indicating that the grpc_ares_wrapper.cc compilation during the com_github_grpc_grpc component is not given the -DCARES_STATICLIB flag as listed in the dependencies' defines;
```
ERROR: C:/workspace/envoy/source/exe/BUILD:27:1: Linking of rule '//source/exe:envoy-static' failed (Exit
4217)
grpc_resolver_dns_ares.lib(grpc_ares_wrapper.obj) : warning LNK4217: locally defined symbol ares_library_init imported in function "struct grpc_error * __cdecl grpc_ares_init(void)" (?grpc_ares_init@@YAPEAUgrpc_error@@XZ)
LINK : error LNK1218: warning treated as error; no output file generated
```

It's not entirely clear from the documentation what we are supposed to do to convey that compiler define flag to the grpc cmake component. Could you advise?

**Comment by wrowe** [comment]
cc @irengrig @achasveachas

Note that further testing reveals that the defines=[] list of symbols from cmake_external() components are not propagated to cmake_external dependencies either.

**Comment by wrowe** [comment]
Ping once more, @irengrig could you perhaps examine and classify this report?

We might be getting to the point of crafting a patch given a couple more months of experience with bazel's structure and style. If this could get attention sooner, it has come up for other devs.

Right now we tweak a number of variables on windows in our .bazelrc that would be better tweaked in the foreign_cc/BUILD cmake library project rules.

**Comment by wrowe** [comment]
Periodic reminder that this needs to be triaged and the issue remains issue for inheriting the appropriate -D flags required to compile against third party foreign header files.

**Comment by wrowe** [comment]
Ping

Annual reminder that this needs to be triaged and the issue remains issue for inheriting the appropriate -D flags required to compile against third party foreign header files.

**Comment by wrowe** [comment]
Here's a typical scenario illustrating this problem, and two related problems related to an inability to add target-specific copts, which would serve to at least ameliorate the problem.

This specific example illustrates a (bazel lib) -> curl -> (zlib, c-ares, nghttp2) dependency chain and identifies the issues conveying required defines to consumers of those dependencies with the current rules_foreign_cc;

```
cmake_external(
    # zlib cmake correctly injects -DZLIB_DLL for the shared lib src compilation
    # zlib cmake correctly omits -DZLIB_DLL for the static lib src compilation
    # zlib cmake cannot inject -DZLIB_DLL into zlib/share/pkgconfig/zlib.pc if both are being compiled
    # rules_foreign_cc could manually inject -DZLIB_DLL to compile bazel sources dependent on it
    # rules_foreign_cc would fail to inject -DZLIB_DLL to compile cmake_external libs dependent on it
    name = "zlib",
    cache_entries = {
        "BUILD_SHARED_LIBS": "off",
        "SKIP_BUILD_EXAMPLES": "on",
        "ZLIB_COMPAT": "on",
    },
    lib_source = select({
        "//bazel:zlib_ng": "@com_github_zlib_ng_zlib_ng//:all",
        "//conditions:default": "@net_zlib//:all",
    }),
    static_libraries = select({
        "//bazel:windows_x86_64": ["zlibstatic.lib"],
        "//conditions:default": ["libz.a"],
    }),
)

cmake_external(
    # c-ares cmake correctly injects -DCARES_STATICLIB to compile its lib sources
    # c-ares cmake correctly injects -DCARES_STATICLIB in its lib/pkgconfig/libcares.pc Cflags
    # rules_foreign_cc manual defines injects -DCARES_STATICLIB to compile bazel sources dependent on it
    #     (rules_foreign_cc could have gathered this from lib/pkgconfig/libcares.pc automatically)
    # rules_foreign_cc fails to inject -DCARES_STATICLIB to compile cmake_external libs dependent on it
    name = "ares",
    cache_entries = {
        "CARES_SHARED": "no",
        "CARES_STATIC": "on",
        "CMAKE_INSTALL_LIBDIR": "lib",
    },
    defines = ["CARES_STATICLIB"],
    lib_source = "@com_github_c_ares_c_ares//:all",
    static_libraries = select({
        "//bazel:windows_x86_64": ["cares.lib"],
        "//conditions:default": ["libcares.a"],
    }),
)

cmake_external(
    # nghttp cmake correctly injects -DNGHTTP2_STATICLIB to compile its lib sources
    # nghttp cmake fails to inject -DNGHTTP2_STATICLIB in its lib/pkgconfig/libnghttp2.pc Cflags
    # rules_foreign_cc manual defines injects -DNGHTTP2_STATICLIB to compile bazel sources dependent on it
    #     (rules_foreign_cc could have gathered this from lib/pkgconfig/libnghttp2.pc automatically)
    # rules_foreign_cc fails to inject -DNGHTTP2_STATICLIB to compile cmake_external libs dependent on it
    name = "nghttp2",
    cache_entries = {
        "ENABLE_LIB_ONLY": "on",
        "ENABLE_SHARED_LIB": "off",
        "ENABLE_STATIC_LIB": "on",
        "CMAKE_INSTALL_LIBDIR": "lib",
    },
    cmake_files_dir = "$BUILD_TMPDIR/lib/CMakeFiles",
    defines = ["NGHTTP2_STATICLIB"],
    lib_source = "@com_github_nghttp2_nghttp2//:all",
    static_libraries = select({
        "//bazel:windows_x86_64": ["nghttp2.lib"],
        "//conditions:default": ["libnghttp2.a"],
    }),
)

cmake_external(
    # curl cmake fails to inject -DCURL_STATICLIB to compile its lib sources
    # curl cmake fails to inject -DCURL_STATICLIB in its lib/pkgconfig/libcurl.pc Cflags
    # rules_foreign_cc manual defines injects -DCURL_STATICLIB to compile bazel sources dependent on it
    # rules_foreign_cc fails to inject -DCURL_STATICLIB to compile cmake_external libs dependent on it
    # rules_foreign_cc fails to infer the manual defines -DNGHTTP2_STATICLIB and -DCARES_STATICLIB
    #     from its deps list
    # rules_foreign_cc fails to provide copts or local_defines which would allow manual injection
    #     of ["-DCURL_STATICLIB", "-DNGHTTP2_STATICLIB", "-DCARES_STATICLIB"] to work around this 
    #     pile of bugs originating at four projects (bazel, cmake, curl and nghttp2)
    name = "curl",
    cache_entries = {
        "BUILD_CURL_EXE": "off",
        "BUILD_SHARED_LIBS": "off",
        "ENABLE_ARES": "on",
        "CARES_LIBRARY": "$EXT_BUILD_DEPS/ares",
        "CARES_INCLUDE_DIR": "$EXT_BUILD_DEPS/ares/include",
        "USE_NGHTTP2": "on",
        "NGHTTP2_LIBRARY": "$EXT_BUILD_DEPS/nghttp2",
        "NGHTTP2_INCLUDE_DIR": "$EXT_BUILD_DEPS/nghttp2/include",
        "CURL_ZLIB": "on",
        "ZLIB_LIBRARY": "$EXT_BUILD_DEPS/zlib",
        "ZLIB_INCLUDE_DIR": "$EXT_BUILD_DEPS/zlib/include",
    },
    defines = ["CURL_STATICLIB"],
    generate_crosstool_file = True,
    lib_source = "@com_github_curl//:all",
    static_libraries = select({
        "//bazel:windows_x86_64": ["libcurl.lib"],
        "//conditions:default": ["libcurl.a"],
    }),
    deps = [
        ":ares",
        ":nghttp2",
        ":zlib",
    ],
)
```

**Comment by wrowe** [comment]
Note also, it would help if envoy_cmake_external supported copts. It already supports linkopts, and this is a shortcoming relative to cc_library or cc_binary. This would make implementing workarounds simpler.

While it does support cache_entries, which can include CMAKE_CXX_FLAGS, and also supports env_vars, which can include CXXFLAGS, these are very difficult to manipulate using select().

In this case the select() would be useful to distinguish between dynamic and static builds, which alters the corresponding dependency build (via copts) and dependent components builds (via dependency's defines).

**Comment by jsharpe** [comment]
@wrowe are you able to see if #498 resolves this issue for you?
As noted in #498 I suspect that includes also fail to propagate in the same way due to the way the flags passed to the environment variables are constructed.

**Comment by wrowe** [comment]
> @wrowe are you able to see if #498 resolves this issue for you?

This appears to resolve the inheritance issues of defines. Closing.

> As noted in #498 I suspect that includes also fail to propagate in the same way due to the way the flags passed to the environment variables are constructed.

Interestingly, we've never observed an issue with the includes paths. I can share observations if you want to hit me up for specifics on bazel slack, or a new issue.

Thanks, looking forward to picking this up!
