### ISSUE TITLE
Feature request: additional outputs

### ISSUE THREAD

**Issue by mattgodbolt** [bazelbuild/rules_foreign_cc#320]
I'm using foreign rules to build things like `postgres` to run a test instance locally during my build. `postgres` needs files in `$PREFIX/shared` to be preserved. It would be really useful if I could tell `configure_make()` to also preserve more subfolders than:

```
$ ls bazel-out/k8-fastbuild/bin/tools/third_party/postgres
bin/  include/  lib/  logs/
```

Is there something I'm overlooking that allows me to do this already? Thanks in advance!

**Comment by mattgodbolt** [comment]
I've seen that all the files are available in `.../copy_postgres/...` but I'm uncertain how to appropriately refer to these later on (or whether I can rely on such).

**Comment by irengrig** [comment]
Hi @mattgodbolt, right now you can select the copy_postgres directory with the filegroup, specifying the output_group as "gen_dir". 
(and write a custom Starlark rule for selecting the certain files by name/subpath.
I quickly sketched one: https://github.com/bazelbuild/bazel-skylib/pull/194 - probably I will make it a pull request.)

Here is the example how a binary file can be selected: https://github.com/bazelbuild/rules_foreign_cc/blob/14a9f35611c3256496d260ba56c1d602a8deab51/examples/configure_gnuplot/BUILD#L61

Here is the code of creating output groups of cmake_external/configure_make:
https://github.com/bazelbuild/rules_foreign_cc/blob/14a9f35611c3256496d260ba56c1d602a8deab51/tools/build_defs/framework.bzl#L384

- currently the separate file groups are created for the "install" directory, i.e. what is produced by the build, and for each of the specified binary files.
Unfortunately, I have the fixed attributes for each of the directories bin, include etc.

**Comment by mattgodbolt** [comment]
Thanks @irengrig

**Comment by jschaf** [comment]
@mattgodbolt, off-topic, so forgive me in advance:

Would you mind posting your bazel rules for Postgres? This thread is currently the top hit for a Google search of "rules_foreign_cc postgres". I've started to write my own but have hit a couple snags. I'll open a separate bug for those.

**Comment by mattgodbolt** [comment]
Oh! I'm afraid we switched away from Bazel a long time back after hitting too many issues (unlrelated to this). We never got the postgres thing working, sorry.
