### ISSUE TITLE
output 'external/name/x/lib/lib.so' was not created using bazel make

### ISSUE THREAD

**Issue by adityagujral** [bazelbuild/rules_foreign_cc#325]
I was trying to follow the example provided by [Building Makefile using bazel
](https://stackoverflow.com/questions/58035752/building-makefile-using-bazel) post to build an external package in envoy. In the WORKSPACE file I added the following:

```
new_git_repository(
	name = "name",
	remote = "remote.git",
	build_file = "//foo/bazel/external:x.BUILD",
)
```

And foo/bazel/external/x.BUILD has the following contents:
```
load("@rules_foreign_cc//tools/build_defs:make.bzl", "make")

filegroup(
  name = "m_srcs",
  srcs = glob(["code/**"]),
)

make(
  name = "foo_bar",
  make_commands = ["make lib"],
  lib_source = ":m_srcs",
  shared_libraries = ["lib.so"],
)

```

and I set the visibility in foo/bazel/BUILD as `package(default_visibility = ["//visibility:public"])
`

On executing `bazel build -s @name//:foo_bar`, I get the error that `external/name/x/lib/lib.so` was not created.

I checked the `bazel-bin/external/name/x/logs/GNUMake.log` and make completes successfully. I see that `BUILD_TMPDIR` directory has created lib.so. I think it should have been copied to EXT_BUILD_DEPS/lib, but I am not sure why it was not copied. Would appreciate any tips to debug the error.

**Comment by adityagujral** [comment]
@irengrig thanks for your response. It is private lib that generated libXXX.so in the `code/` folder. As a workaround, I added `; cp libXXX.so $INSTALLDIR/lib/libXXX.so` to the make command which fixed the issue for me.

**Comment by mancini0** [comment]
Sometimes if I build on Fedora I have to add `out_lib_dir = "lib64"` to my cmake_external rule. Building on ubuntu often places the library in /lib. I wonder what the best practice is for writing rules that are easily built across different linux flavors.

**Comment by jiridanek** [comment]
@mancini0 My thinking is that its best to tell the CMake build to name the output lib dir simply "lib", or "lib64", irrespective of platform. I'll try to accomplish that, and update the comment if I find anything.
