### ISSUE TITLE
failed to creating symbolic link

### ISSUE THREAD

**Issue by deryck1031** [bazelbuild/rules_foreign_cc#331]
I am trying to build a project that only suppose cmake.  the project needs glog/gflags.  when i tried to add glog/glags to the 'deps' (see below):

    cmake_external(
      name = "project1",
      lib_source = "project1//:all",
      deps = [
              "@com_google_glog//:glog",
              "@com_google_gflags//:gflags",
             ],
      visibility = ["//visibility:public"],
    )

I am getting below error:
      __________________________ln: creating symbolic link `/tmp/tmp.UOJFtnahpx/include/src': File exists

Looks like it is trying to create links in include dir (according to CMake_script.sh) to both glog/gflags, but both glog/gflags dirs have src dir and hence 'ln' cmd failed to create the link.
It this an issue or I shouldnt be including anything in deps?

**Comment by deryck1031** [comment]
Below is from CMake_script.sh:
"mkdir -p $EXT_BUILD_DEPS/lib
symlink_contents_to_dir $EXT_BUILD_ROOT/bazel-out/k8-fastbuild/bin/external/com_google_glog/libglog.a $EXT_BUILD_DEPS/lib
symlink_contents_to_dir $EXT_BUILD_ROOT/bazel-out/k8-fastbuild/bin/_solib_k8/libexternal_Scom_Ugoogle_Uglog_Slibglog.so $EXT_BUILD_DEPS/lib
mkdir -p $EXT_BUILD_DEPS/include
symlink_contents_to_dir $EXT_BUILD_ROOT/bazel-out/k8-fastbuild/bin/external/com_google_glog/_virtual_includes/glog $EXT_BUILD_DEPS/include
symlink_contents_to_dir $EXT_BUILD_ROOT/external/com_google_glog $EXT_BUILD_DEPS/include
**symlink_contents_to_dir $EXT_BUILD_ROOT/bazel-out/k8-fastbuild/bin/external/com_google_glog $EXT_BUILD_DEPS/include**
"
from above, we already copy libglog.a to lib directory, and includes to include directory.  but why are we coping the whole directory into the include dir (the last symlink_contents_to_dir cmd)

**Comment by beneisner** [comment]
This is a blocker for us, would be great to have workaround/resolution. I don't quite understand the implementation details well enough to do a proper fix, unfortunately :(

**Comment by deryck1031** [comment]
I noticed that it is trying to copy other directories that  arent needed for build because proper include/lib directories are all linked correctly.  To workaround the issue, I created a patch to add '-f' option to the 'ln' cmd in tools/build_defs/shell_toolchain/toolchains/impl/linux_commands.bzl:

@@ -87,9 +87,9 @@
 mkdir -p ${target}
 if [[ -d $1 ]]; then
-  ln -s -t ${target} $1
+  ln -sf -t ${target} $1
 elif [[ -f $1 ]]; then
-  ln -s -t ${target} $1
+  ln -sf -t ${target} $1
 elif [[ -L $1 ]]; then
   cp --no-target-directory $1 ${target}
 else

**Comment by wesleyw72** [comment]
Also hitting this

**Comment by lizan** [comment]
@irengrig any idea? We're also hitting this when trying to update `rules_foreign_cc` in Envoy (from commit in Aug to master). Seems #330 can fix that.

**Comment by fcelda** [comment]
I'm also affected. I can confirm that #330 doesn't have the problem (after rebase).

**Comment by htuch** [comment]
@lberki this is another Envoy-related `rules_foreign_cc` issue that we're blocked on.
