### ISSUE TITLE
Passing flatc location to cmake_external

### ISSUE THREAD

**Issue by ktf** [bazelbuild/rules_foreign_cc#335]
I would like to pass "@flatbuffers//:flatc" as `cache_entries` entry, i.e.:

```bazel
cmake_external(
  ...
  cache_entries = {
      "FLATBUFFERS_INCLUDE_DIR": "$EXT_BUILD_DEPS/include",
      "FLATC": "@flatbuffers//:flatc",
  },
  deps = [..., "@flatbuffers//:flatbuffers", "@flatbuffers//:flatc"]
)
```

however, the label does not seem to be expanded. Is that expected? Any workaround?

**Comment by irengrig** [comment]
Hi @ktf , as you are passing @flatbuffers//:flatc as dependency into the rule, the library files will be copied (by the cmake_external rule) under $EXT_BUILD_DEPS, depending on whether it was built with cmake_external or Bazel's native cc_library rule.
In case of cmake_external, the library will be under $EXT_BUILD_DEPS/flatc/lib directory - if the cmake_external target's name is "flatc".
In case when flatc was built with Bazel, it will be in $EXT_BULD_DEPS/lib directory.

You should use "FLATC": "$EXT_BUILD_DEPS/flatc/lib" or "FLATC": "$EXT_BUILD_DEPS/lib" for the FLATC directory, depending on the case.

(The variant that you are using will not work, as the value @flatbuffers//:flatc is interpreted as text, and even with $(location ) pattern, it will be evaluated to a group of files.)

**Comment by ktf** [comment]
Hi, thank you for your reply.

I did a few attempts and in particular what you suggest:

* deps = ["@flatbuffers//:flatc"]
* "FLATC": "$EXT_BUILD_DEPS/lib"

does not seem to work, at least using flatbuffers 1.11 and the internal native bazel targets.  "$EXT_BUILD_DEPS/lib" seems to be empty and the error is:

/bin/sh: /var/folders/gg/xldx68351cd9k1rpb_0bhbc80000gn/T/tmp.bMLfkTVY/lib: is a directory

**Comment by ktf** [comment]
(notice `flatc` is a binary, not a library)

**Comment by ktf** [comment]
Ok, I just discovered about `tools_deps`. 

* tools_deps = ["@flatbuffers//:flatc"]
* "FLATC": "$EXT_BUILD_DEPS/bin/flatc"

worked for me. Thank you for the hint.

**Comment by irengrig** [comment]
Happy it works! 
Thank you for describing the working scenario.
