### ISSUE TITLE
How to pass copts to configure or Make?

### ISSUE THREAD

**Issue by mehrdadn** [bazelbuild/rules_foreign_cc#342]
Hi, I'm trying to build a library that uses configure/Make.  

I have some conditional `COPTS` like this:

	COPTS = [...] + select({
	    "@bazel_tools//src/conditions:windows": [...],
	    "//conditions:default": [...],
	})

How do I pass them to, say, a `make` rule?

**Comment by irengrig** [comment]
Hi @mehrdadn , the intended usage is that you pass --copts in .bazelrc file, and rules_foreign_cc takes it from there (but I do not see how it can be adjusted for the operating system).

For passing the compiler options conditionally to specific rules_foreign_cc targets, you can use 
configure_env_vars attribute with configure_make to add flags to CXXFLAGS or CFLAGS environment variables (that are constructed from Bazel toolchain and user values in configure_env_vars) to be passed to configure script:

`configure_make(
    name = "...",
    lib_source = "...",
    configure_env_vars = {
        "CXXFLAGS": "XXXXX",
    },
)
`

In the case of make rule, use make_env_vars attribute.

**Comment by mehrdadn** [comment]
Oh I see, I didn't realize the intention was using `.bazelrc`. (I actually did try the env var option, but as you noticed, it doesn't work for conditionals.) Unfortunately using `.bazelrc` means we can't make sure it uses the same flags the rest of the build system, right? Otherwise it forces us to put _everything_ into the `.bazelrc`.

**Comment by irengrig** [comment]
>Unfortunately using .bazelrc means we can't make sure it uses the same flags the rest of the build system, right?

quite opposite, --copts in the .bazelrc passes the value for all Bazel cc_library/cc_binary targets, and for all rules_foreign_cc targets.

**Comment by mehrdadn** [comment]
What I meant was that that's only possible if we move **all** of our build rules into `.bazelrc`, which doesn't seem like a good thing. Right?

**Comment by mehrdadn** [comment]
Build flags*

**Comment by irengrig** [comment]
The other place where all default flags are described is a toolchain: https://docs.bazel.build/versions/master/cc-toolchain-config-reference.html

rules_foreign_cc are copying all the tools and flags of the cc_toolchain, selected/generated by Bazel.

**Comment by wrowe** [comment]
Please note that modifying the env vars or cmake cache dictionaries isn't possible with select.

First class support for a copts list, just as rules_foreign_cc supports linkopts, would go a long was to solving many problems that we've tripped over, especially covering for other quirks in the cmake external build schema.

**Comment by mehrdadn** [comment]
Is this going to be addressed?

**Comment by UebelAndre** [comment]
I believe this was addressed in https://github.com/bazelbuild/rules_foreign_cc/pull/588

A `copts` attribute was added to the core `foregin_cc` framework so each rule should have it.

**Comment by mehrdadn** [comment]
Ah awesome, thanks!
