### ISSUE TITLE
Unable to find package for '@rules_foreign_cc_bazel_version'

### ISSUE THREAD

**Issue by magichome** [bazelbuild/rules_foreign_cc#343]
I'm getting the following error when I try to use 'rules_foreign_cc':

```
... rules_foreign_cc/tools/build_defs/cc_toolchain_util.bzl: Unable to find package for @rules_foreign_cc_bazel_version//:def.bzl
```
I'm new to bazel so this could be something wrong with my environment but I noticed the reference to '@rules_foreign_cc_bazel_version' was a recent change.  This is with bazel v1.0.1.

**Comment by irengrig** [comment]
Hi @magichome , please make sure that you make the proper initialization of rules_foreign_cc in your WORKSPACE file, i.e. that you call rules_foreign_cc_dependencies.
(There is an example in the README file of rules_foreign_cc repository for CMake, but it is relevant to all rules: https://github.com/bazelbuild/rules_foreign_cc)

**Comment by magichome** [comment]
That was the problem.  Thanks
