### ISSUE TITLE
"malloc" attribute not woking?

### ISSUE THREAD

**Issue by codefever** [bazelbuild/rules_foreign_cc#345]
According to the "[use_malloc](https://github.com/bazelbuild/rules_foreign_cc/tree/master/examples/use_malloc)" example in rule_foreign_cc, linking tcmalloc is allowed via another cc_library. So I try the BUILD file below with a simple "helloworld" program:

```
load("@rules_foreign_cc//tools/build_defs:configure.bzl", "configure_make")

configure_make(
    name = "gperftools_build",
    configure_options = [
        "--enable-shared=no",
        "--enable-frame-pointers",
        "--disable-libunwind",
    ],
    linkopts = ['-lpthread'],
    lib_source = "@gperftools//:all",
    static_libraries = ["libtcmalloc_and_profiler.a"],
)

cc_library(
    name = "gperftools",
    deps = [
        ":gperftools_build",
    ],
)

cc_test(
    name = "hello",
    srcs = ["main.cc"],
    malloc = ":gperftools",
)
```

But it turns out that the hello binary isn't really linked with tcmalloc. 

Try this out:
> HEAPCHECK=strict ../bazel-bin/hello/hello

No heap check information comes out. And we can also check with `nm -a ../bazel-bin/hello/hello`.

> Bazel version: 1.2.1
> GCC: 9.2.1
> OS: ubuntu 20.04

**Comment by vinllen** [comment]
is there any solution？ meet the same question.
