### ISSUE TITLE
Please provide releases?

### ISSUE THREAD

**Issue by joshburkart** [bazelbuild/rules_foreign_cc#360]
Could tagged releases please be provided? Right now users need to either rely on the `master.zip` file, which carries security concerns, or need to pin to a specific commit, without guidance on which.

Thanks for providing the code in this repo!

**Comment by FlyingBBQ** [comment]
Please add releases. For reproducible builds (and security reasons) I would like to add a sha256, but this becomes out of date every time there is an update to master.

**Comment by jake-arkinstall** [comment]
Just here to bump this. The last tag point was 91 weeks ago.

**Comment by UebelAndre** [comment]
We will be making a new release/tag soon. Trying to resolve a few PRs first. Hoping to have something by next week.

**Comment by jsharpe** [comment]
We've just tagged a release. Hopefully they will be more frequent now going forward.
