### ISSUE TITLE
Problems with pkg-config on transitive builds

### ISSUE THREAD

**Issue by flichtenheld** [bazelbuild/rules_foreign_cc#365]
Hi.

I have a configure_make build that tries to run pkg-config against a component built with a different configure_make. But it fails with:

```
checking for libmnl... no
configure: error: Package requirements (libmnl >= 1) were not met:

Variable 'EXT_BUILD_DEPS' not defined in '/home/flichtenheld/.cache/bazel/_bazel_flichtenheld/a7def64fd52f4e313e77afa5a69def9f/sandbox/processwrapper-sandbox/46/execroot/__main__/bazel-out/k8-fastbuild/bin/libs/mnl/copy_mnl/mnl/lib/pkgconfig/libmnl.pc'

```

I fixed it by adding an additional statement to the configure_script.bzl like this:

```
script += ["export PKG_CONFIG=\"pkg-config --define-variable=EXT_BUILD_DEPS=$$EXT_BUILD_DEPS$$\""]
```

This resolves the issue for me and looks to me like good default behavior. But before opening a pull request for this I wanted to make sure I didn't miss a better solution.

Regards,
  Frank

**Comment by jheaff1** [comment]
This seems to be related to #344

**Comment by rajachan** [comment]
I've stumbled into a manifestation of the same issue. Are the maintainers planning to review/merge your proposed fix, @flichtenheld?

**Comment by jsharpe** [comment]
Unfortunately without a sign off on the CLA we can't merge the change. It also needs rebasing on top of main as the file structure has changed since this PR was made.
