### ISSUE TITLE
configure_make: How to specify preprocessor defines?

### ISSUE THREAD

**Issue by dev-guy** [bazelbuild/rules_foreign_cc#366]
I would like to do something like pass -DNDEBUG to clang. Thank you.

**Comment by flichtenheld** [comment]
configure_make can't directly control the compiler. configure and make are doing that. So you need to instruct them to add the flag. Usually you can achieve this by using configure_env_vars. Something like this `configure_env_vars = { "CFLAGS": "additional cflags" }`

These are appended to the flags as determined by the toolchain ([https://github.com/bazelbuild/rules_foreign_cc/blob/master/tools/build_defs/configure_script.bzl#L150]) so if you want to set the flag globally you can do so also via the usual bazel mechanisms.
