### ISSUE TITLE
Correctly extracting built libraries and binaries?

### ISSUE THREAD

**Issue by celskeggs** [bazelbuild/rules_foreign_cc#376]
When I declare an external cmake build like the following:

```
cmake_external(
    name = "ceph",
    binaries = ["ceph-authtool"],
    shared_libraries = ["libcephfs.so.2"],
    cache_entries = {
        // [...]
    },
    lib_source = "@ceph//:source",
)
```

Trying to reference a target like `:ceph-authtool` (which appears to at least partially exist) yields an error like the following:

```
ERROR: missing input file 'ceph/ceph-authtool', owner: '//ceph:ceph-authtool'
ERROR: /homeworld/platform/ceph/BUILD.bazel:116:1: //ceph:oci-contents-bin: missing input file '//ceph:ceph-authtool'
```

I've worked around this using the feature that lets us extract a particular cmake-built binary via its filegroup:

    filegroup(
        name = "ceph-authtool",
        srcs = [":ceph"],
        output_group = "ceph-authtool",
    )

However, this appears to be limited to only working on _binaries_, not _libraries_. The following, for example, does not work:

    filegroup(
        name = "libcephfs.so.2",
        srcs = [":ceph"],
        output_group = "libcephfs.so.2",
    )

This was easy to work around with a one-word patch to `framework.bzl`:

```
--- tools/build_defs/framework.bzl
+++ tools/build_defs/framework.bzl
@@ -289,7 +289,7 @@ def cc_external_rule_impl(ctx, attrs):
         lib_dir_name = attrs.out_lib_dir,
         include_dir_name = attrs.out_include_dir,
     )
-    output_groups = _declare_output_groups(installdir_copy.file, outputs.out_binary_files)
+    output_groups = _declare_output_groups(installdir_copy.file, outputs.declared_outputs)
     wrapped_files = [
         wrapped_outputs.script_file,
         wrapped_outputs.log_file,
```

However, I'm not sure that this is the correct way to solve the original problem.

Is there something else I should be using to extract individual binaries and libraries from a cmake build besides using an explicit `filegroup`? If not, could rules_foreign_cc get a feature to add support for doing this with libraries, and not just binaries?

**Comment by celskeggs** [comment]
(I hit submit before I finished writing this issue. I've finished writing what I intended to write and edited it in, but if GitHub emailed out an earlier iteration of the issue before I'd fixed it, please disregard that version. My apologies.)

**Comment by cameron-martin** [comment]
Can you re-open this? This is still an issue.

**Comment by cameron-martin** [comment]
Looks like this may have been fixed by https://github.com/bazelbuild/rules_foreign_cc/pull/1056.
