### ISSUE TITLE
Error executing shell command '...cleanup_function...'

### ISSUE THREAD

**Issue by emctague** [bazelbuild/rules_foreign_cc#388]
When trying to build a project which includes a `cmake_external` rule to build [SFML 2.5.1](https://github.com/SFML/SFML/releases/tag/2.5.1) from source, I run into this error nearly (but not consistently) every time:

```
ERROR: /Users/t/WorkspacePath/ProjectPath/BUILD:4:1: Couldn't build file ProjectPath/SFML/include: error executing shell command: '/bin/bash -c function cleanup_function() {
local ecode=$?
if [ $ecode -eq 0 ]; then
cleanup_on_success
else
cleanup_on_failure
fi
}
set -e
function cleanup_on_success() {
printf "rules_foreign_cc: ...' failed (Exit 2) bash failed: error executing command /bin/bash -c ... (remaining 1 argument(s) skipped)
```

The `cmake_external` rule looks like this:

```
cmake_external(
   name = "SFML",
   headers_only = False,
   lib_source = "@SFML//:all",
   static_libraries = ["libsfml-graphics.a", "libsfml-system.a", "libsfml-window.a"],
   install_prefix = "." # Not sure about this, bazel was trying  to *install* cmake to my system at one point so i tried to override the install_prefix
)
```

And the workspace entry:

```
http_archive(
   name = "SFML",
   build_file_content = all_content,
   urls = ["https://github.com/SFML/SFML/archive/2.5.1.zip"],
   strip_prefix="SFML-2.5.1"
)
```

This seems similar to #265, except that is marked as fixed, and of course I am experiencing this issue in the present.

**Edit:** This seems to be output when other build errors are encountered. In this case, `cmake_external` is trying to install documentation files to `/usr/local/share` during the build process for no apparent reason (I've even tried to override the install path via `env_vars`, `cmake_options`, `cache_entries`, *and* `install_prefix` just to avoid the error), which somehow breaks the whole build process.

**Comment by irengrig** [comment]
It is hard to say what is wrong without looking into the build script of this exact library.
I tried to repeat the problem and I am missing some libraries:

CMake Error at cmake/Macros.cmake:296 (message):
  Missing item in X11_X11_LIB;X11_Xrandr_LIB

- they should be either taken from local system (in that case, CMake will try to find them in the local system by itself) - or described by other Bazel targets and provided as dependencies for cmake_external target.

Also, if you update rules_foreign_cc and try it again, the actual shell script executed by rules-foreign_cc behind the scenes is printed now in case of failure - it may give more information.
