### ISSUE TITLE
Running binaries produced by cmake_external under bazel

### ISSUE THREAD

**Issue by Dig-Doug** [bazelbuild/rules_foreign_cc#391]
I have a `cmake_external` rule that is producing a binary that I would like to run with bazel (in a genrule). It looks like this:

```
cmake_external(
    name = "cppgraphqlgen",
    binaries = [
        "schemagen", # I want to run this
    ],
    cache_entries = {
        "BOOST_INCLUDEDIR": "$EXT_BUILD_DEPS/boost",
        "RapidJSON_DIR": "$EXT_BUILD_DEPS/rapidjson",
        "RAPIDJSON_INCLUDE_DIRS": "$EXT_BUILD_DEPS/rapidjson/include",
        "GRAPHQL_BUILD_TESTS": "OFF",
    },
    lib_source = "@com_github_microsoft_cppgraphqlgen//:all",
    out_bin_dir = "bin/cppgraphqlgen",
    static_libraries = [
        "libgraphqljson.a",
        "libgraphqlpeg.a",
        "libgraphqlresponse.a",
        "libgraphqlservice.a",
    ],
    deps = [
        # I also build these with bazel using cmake_external and boost_build
        ":rapidjson",
        "//:boost",
    ],
)
```

The problem I'm facing is that when I try to run the `schemagen` binary, I get an error:

```
bazel-bin/third_party/cppgraphqlgen/bin/cppgraphqlgen/schemagen --help    
bazel-bin/third_party/cppgraphqlgen/bin/cppgraphqlgen/schemagen: error while loading shared libraries: libboost_program_options.so.1.72.0: cannot open shared object file: No such file or directory
```

I've been able to fix it by specifying a library search path:

```
LD_LIBRARY_PATH=bazel-bin/boost/lib bazel-bin/third_party/cppgraphqlgen/bin/cppgraphqlgen/schemagen --help  
```

but I was wondering if there is an existing way to run the output binaries under bazel where I don't need to specify the search path?

Thanks for your help!

**Comment by z-hasher** [comment]
> I have a `cmake_external` rule that is producing a binary that I would like to run with bazel (in a genrule). It looks like this:
> 
> ```
> cmake_external(
>     name = "cppgraphqlgen",
>     binaries = [
>         "schemagen", # I want to run this
>     ],
>     cache_entries = {
>         "BOOST_INCLUDEDIR": "$EXT_BUILD_DEPS/boost",
>         "RapidJSON_DIR": "$EXT_BUILD_DEPS/rapidjson",
>         "RAPIDJSON_INCLUDE_DIRS": "$EXT_BUILD_DEPS/rapidjson/include",
>         "GRAPHQL_BUILD_TESTS": "OFF",
>     },
>     lib_source = "@com_github_microsoft_cppgraphqlgen//:all",
>     out_bin_dir = "bin/cppgraphqlgen",
>     static_libraries = [
>         "libgraphqljson.a",
>         "libgraphqlpeg.a",
>         "libgraphqlresponse.a",
>         "libgraphqlservice.a",
>     ],
>     deps = [
>         # I also build these with bazel using cmake_external and boost_build
>         ":rapidjson",
>         "//:boost",
>     ],
> )
> ```
> 
> The problem I'm facing is that when I try to run the `schemagen` binary, I get an error:
> 
> ```
> bazel-bin/third_party/cppgraphqlgen/bin/cppgraphqlgen/schemagen --help    
> bazel-bin/third_party/cppgraphqlgen/bin/cppgraphqlgen/schemagen: error while loading shared libraries: libboost_program_options.so.1.72.0: cannot open shared object file: No such file or directory
> ```
> 
> I've been able to fix it by specifying a library search path:
> 
> ```
> LD_LIBRARY_PATH=bazel-bin/boost/lib bazel-bin/third_party/cppgraphqlgen/bin/cppgraphqlgen/schemagen --help  
> ```
> 
> but I was wondering if there is an existing way to run the output binaries under bazel where I don't need to specify the search path?
> 
> Thanks for your help!

@Dig-Doug Hi were you able to resolve this at the end? I ran into this issue several times, which is pretty painful especially for automating tests, and wonder if there's anybody having good idea what to do with it. Thanks

**Comment by Dig-Doug** [comment]
I ended up not using this. As a workaround, you might be able to specify it in a `bazelrc` file using `action_env`.
