### ISSUE TITLE
`CMAKE_SYSTEM_NAME` as target OS

### ISSUE THREAD

**Issue by keith** [bazelbuild/rules_foreign_cc#397]
Currently rules_foreign_cc passes the host OS as the `CMAKE_SYSTEM_NAME`. There is currently this comment:

https://github.com/bazelbuild/rules_foreign_cc/blob/ed3db61a55c13da311d875460938c42ee8bbc2a5/tools/build_defs/cmake.bzl#L70-L71

That implies this is not the desired behavior. With [envoy](https://github.com/envoyproxy/envoy) we found a case where cross compiling between Linux / macOS this ends up causing the wrong arguments to be configured for the current linker.

Is there a clear path currently with bazel to fix this? I'd be happy to implement it if so. It looks like we could possibly take the same approach as this:

https://github.com/bazelbuild/rules_foreign_cc/blob/ed3db61a55c13da311d875460938c42ee8bbc2a5/tools/build_defs/shell_toolchain/toolchains/toolchain_mappings.bzl#L10-L35

except use a separate set of them with `target_compatible_with` instead of `exec_compatible_with` and only provide the OS name. But I'd love to hear if there were different implementation plans from someone who has more context on this than me!

**Comment by keith** [comment]
It's worth noting that in some cases, such as in envoy's build system, it isn't trivial to pass this value ourselves. This is because we cannot combine a dictionary with a `select()` since we want to support building this for multiple platforms. Ideally we could do:

```bzl
default_cache_entries + select({
    "some config": {"CMAKE_SYSTEM_NAME": "something"},
})
```

But this ends up failing because of dictionaries in starlark not supporting `+`

**Comment by irengrig** [comment]
Hi @keith , thank you for reporting this.

Is that possible to use update method to add entries to the dict?
[https://docs.bazel.build/versions/3.1.0/skylark/lib/dict.html#update](https://docs.bazel.build/versions/3.1.0/skylark/lib/dict.html#update)
In that case, it seems you can override the value with cache_entries.

**Comment by keith** [comment]
Unfortunately in our case there are a few too many levels of selects and `.update`s happening in macros today
https://github.com/envoyproxy/envoy/blob/698df2c5f1b9b71d49c183d902a6cde59a335da7/bazel/envoy_build_system.bzl#L100-L103 https://github.com/envoyproxy/envoy/blob/698df2c5f1b9b71d49c183d902a6cde59a335da7/bazel/envoy_build_system.bzl#L76-L78 that I don't think is compatible with another `.update`

**Comment by htuch** [comment]
@lberki FYI, this is something that Envoy Mobile is running into and might need some support.
