### ISSUE TITLE
Make configure command options should expand bazel make variables

### ISSUE THREAD

**Issue by rockwotj** [bazelbuild/rules_foreign_cc#402]
See: https://docs.bazel.build/versions/master/be/make-variables.html

I'm trying to build FFMPEG from source and it doesn't support the standard default CC environment variable - I'd like to define it using the --cc flag, but those rules don't support that.

**Comment by rockwotj** [comment]
This is still relevant, please keep open

**Comment by UebelAndre** [comment]
We can keep this open. Do you have an example of what you're trying to do? I thought we supported expanding variables.

**Comment by rockwotj** [comment]
Here's an example of a BUILD file for FFMPEG that needs this:

```
load("@rules_foreign_cc//tools/build_defs:configure.bzl", "configure_make")

filegroup(name="all_files", srcs=glob(["**"]))

configure_make(
    name = "ffmpeg",
    configure_options = [
        "--ar=$(AR)",
        "--cc=$(CC)",
        "--cxx=$(CXX)",
        "--disable-static",
        "--disable-programs",
        "--enable-shared",
        "--x86asmexe=yasm",
    ] + select({
      "@//bazel:optimized_build": ["--disable-debug"],
      "//conditions:default": [],
    }),
    lib_source = ":all_files",
    make_commands = [
        # I'm not sure if this is a good idea, but it's one way to guess this number.
        "export NUMJOBS=$(python3 -c 'import os; print(max(os.cpu_count() // 2, 1))')",
        "make -j $NUMJOBS",
        "make install",
    ],
    shared_libraries = select({
        "@//bazel:osx_x86_64": [
            "libavcodec.dylib",
            "libavdevice.dylib",
            "libavfilter.dylib",
            "libavformat.dylib",
            "libswresample.dylib",
            "libavutil.dylib",
            "libswscale.dylib",
        ],
        "@//bazel:linux_x86_64": [
            "libavcodec.so",
            "libavdevice.so",
            "libavfilter.so",
            "libavformat.so",
            "libswresample.so",
            "libavutil.so",
            "libswscale.so",
        ],
    }),
    tools_deps = ["@yasm//:yasm_binary"],
    visibility = ["//visibility:public"],
)
```


To be able to pass in those variables as flags instead of via the environment, you need to be able to resolve `$(CC)` like mentioned here: https://docs.bazel.build/versions/4.0.0/be/make-variables.html#custom_variables

For make, one solution is here: https://github.com/bazelbuild/rules_foreign_cc/blob/main/foreign_cc/private/configure_script.bzl#L67-L71

Where we could use the following function to expand environment variables into the flags: https://docs.bazel.build/versions/4.0.0/skylark/lib/ctx.html#expand_make_variables


Here's a rough patch that I make when I first opened this issue to hack this into working:
```
configure_vars = {k: _join_flags_list(workspace_name, v).replace('$', '$$') for (k, v) in _get_configure_variables(tools, flags, user_vars).items()}
expanded_options = [ctx.expand_make_variables("configure_options", opt, configure_vars) for opt in user_options]
 
script.append("{env_vars} \"{configure}\" --prefix=$$BUILD_TMPDIR$$/$$INSTALL_PREFIX$$ {user_options}".format(
  env_vars = env_vars_string,
  configure = configure_path,
  user_options = " ".join(expanded_options),
))
```

Although expand_make_variables is deprecated, and it seems that the advice here https://github.com/bazelbuild/bazel/issues/5859 is to replace it with a python like replace mechanism, but there seems to be little interest in actually coming up with a migration here/standard way of doing this from the core bazel team, which is why I never got my patch in a good enough shape to submit here.
