### ISSUE TITLE
cmake_external: common tags attribute

### ISSUE THREAD

**Issue by ukai** [bazelbuild/rules_foreign_cc#404]
similar with #346 

there is no way to specify cmake_external not to use remote, sandbox etc.
better to understand common tags attributes?
https://docs.bazel.build/versions/master/be/common-definitions.html#common-attributes

 no-sandbox, no-remote-* etc

**Comment by ukai** [comment]
can be fixed by `--experimental_allow_tags_propagation`

https://github.com/bazelbuild/bazel/issues/8830

**Comment by jsharpe** [comment]
Closing as a workaround has been identified
