### ISSUE TITLE
Fix tools_deps to be executable on host (cross compile)

### ISSUE THREAD

**Issue by em84** [bazelbuild/rules_foreign_cc#414]
Description of the tools_deps states, these are required for the actual **building** of the library/binary. Thus they should be configured for the host machine, otherwise they can't be used for building in a cross compile environment.

**Comment by em84** [comment]
#415

**Comment by attilaolah** [comment]
The linked pull request was merged in d2698df7dfe357d2e09a452a9f092b7278c78c8b, can we close this ticket or is there still something to be done?
