### ISSUE TITLE
Support "data" outputs

### ISSUE THREAD

**Issue by samschlegel** [bazelbuild/rules_foreign_cc#419]
I'm currently attempting to use rules_foreign_cc to build python (😅), but I'm running into the issue that python depends on non-library files that are output as part of the build process into `lib/pythonX.Y`. As far as I can tell there's no way to support this with the current rules.

It seems like supporting something like `data` outputs would make sense, however in this case we'd also need to support data directories, since I'm not sure (or don't want to enumerate) of all the the file names in the target definition. Unfortunately there's also a lot of files that aren't reproducible in the `lib/pythonX.Y` directory, so maybe we'll need to manually specify them anyways.

I'm open to implementing this myself, but would like to know if this seems like a good direction before I go down that path.

There's also a whole other host of things that I'm sure will make building python non-trivial, but at least this data file requirement seems like it could be common.

**Comment by attilaolah** [comment]
Not sure what's  good way to solve the data output problem, but it sure would be very cool to build Python with these rules.

**Comment by samschlegel** [comment]
FWIW I ended giving up on using these rules as there ended up being a lot of config that had to be done to get it to be reproducible, and I managed to stumble upon Dropbox's build tools where they have very granular rules for building python https://github.com/dropbox/dbx_build_tools/tree/master/thirdparty/cpython

Also IIRC I was able to just rely on depending on the output lib dir, but that's not the best if you want specific file outputs

**Comment by jheaff1** [comment]
I have submitted PR#622 to resolve this
