### ISSUE TITLE
make rule ignores env vars

### ISSUE THREAD

**Issue by mobileink** [bazelbuild/rules_foreign_cc#435]
The code for `create_make_script` (in [https://github.com/bazelbuild/rules_foreign_cc/blob/master/tools/build_defs/configure_script.bzl](https://github.com/bazelbuild/rules_foreign_cc/blob/master/tools/build_defs/configure_script.bzl) seems to ignore `make_env_vars`.

I'm trying to compile [rocksdb](https://github.com/facebook/rocksdb) with the following:

```
make(
    name = "rocksdb",
    make_commands = ["make", "static_lib", "-j2"],
    make_env_vars = {
        "ROCKSDB_DISABLE_SNAPPY": "1",
        "ROCKSDB_DISABLE_GFLAGS": "1",
        "ROCKSDB_DISABLE_LZ4": "1",
        "ROCKSDB_DISABLE_ZSTD": "1",
        "ROCKSDB_DISABLE_NUMA": "1",
        "ROCKSDB_DISABLE_TBB": "1",
        "ROCKSDB_DISABLE_JEMALLOC": "1",
        "ROCKSDB_DISABLE_TCMALLOC": "1",
        "ROCKSDB_DISABLE_BACKTRACE": "1",
        "PORTABLE": "1",
        "FORCE_SSE42": "1",
        "DISABLE_WARNING_AS_ERROR": "1",
    },
    lib_source = "@rocksdb//:all",
    out_lib_dir = "lib",
    static_libraries = ["librocksdb.a"],
)
```

The result is:

```
ERROR: /Users/gar/mina/gitfork/bzl/external/rocksdb/BUILD.bazel:4:5: output 'bzl/external/rocksdb/rocksdb/lib/librocksdb.a' was not created
ERROR: /Users/gar/mina/gitfork/bzl/external/rocksdb/BUILD.bazel:4:5: not all outputs were created or valid
```

The env vars I pass do not appear in the log, and that causes an error.

**Comment by mobileink** [comment]
FYI I got it to build by putting all the env vars in `make_commands` like so:

```
    make_commands = [
        " ".join(["env",
        "ROCKSDB_DISABLE_SNAPPY=1",
        "ROCKSDB_DISABLE_GFLAGS=1",
        "ROCKSDB_DISABLE_LZ4=1",
        "ROCKSDB_DISABLE_ZSTD=1",
        "ROCKSDB_DISABLE_NUMA=1",
        "ROCKSDB_DISABLE_TBB=1",
        "ROCKSDB_DISABLE_JEMALLOC=1",
        "ROCKSDB_DISABLE_TCMALLOC=1",
        "ROCKSDB_DISABLE_BACKTRACE=1",
        "PORTABLE=1",
        "FORCE_SSE42=1",
        "DISABLE_WARNING_AS_ERROR=1",
        "make", "static_lib", "-j2"])
    ],
```
However, the build still fails with the same opaque message.  The log says that `librocksdb.a` was built, and indeed I found it in `BUILD_TMPDIR=/var/folders/wz/dx0cgvqx5qn802qmc3d4hcfr0000gp/T/tmp.zPEWsxd0`.

How can I get that to the right place?  Evidently `out_lib_dir` is also ignored.

**Comment by jsharpe** [comment]
https://github.com/bazelbuild/rules_foreign_cc/pull/383 is a fix for this.

`out_lib_dir` is just telling the rule what the name of the output directory is, it does nothing to your build scripts to ensure that make outputs to this location. You might need to add an additional step to your make_commands to `mv $$BUILD_TMPDIR/librocksdb.a lib/`
