### ISSUE TITLE
make rule ignores out_lib_dir

### ISSUE THREAD

**Issue by mobileink** [bazelbuild/rules_foreign_cc#436]
See #435 .  The following successfully builds `librocksdb.a` in `BUILD_TMPDIR` but fails with

```
ERROR: /Users/gar/mina/gitfork/bzl/external/rocksdb/BUILD.bazel:4:5: output 'bzl/external/rocksdb/rocksdb/lib/librocksdb.a' was not created
ERROR: /Users/gar/mina/gitfork/bzl/external/rocksdb/BUILD.bazel:4:5: not all outputs were created or valid
```

Rule:

```
make(
    name = "rocksdb",
    make_commands = [
        " ".join(["env",
        "ROCKSDB_DISABLE_SNAPPY=1",
        "ROCKSDB_DISABLE_GFLAGS=1",
        "ROCKSDB_DISABLE_LZ4=1",
        "ROCKSDB_DISABLE_ZSTD=1",
        "ROCKSDB_DISABLE_NUMA=1",
        "ROCKSDB_DISABLE_TBB=1",
        "ROCKSDB_DISABLE_JEMALLOC=1",
        "ROCKSDB_DISABLE_TCMALLOC=1",
        "ROCKSDB_DISABLE_BACKTRACE=1",
        "PORTABLE=1",
        "FORCE_SSE42=1",
        "DISABLE_WARNING_AS_ERROR=1",
        "make", "static_lib", "-j2"])
    ],
    lib_source = "@rocksdb//:all",
    out_lib_dir = "lib",
    static_libraries = ["librocksdb.a"],
)
```

**Comment by whs-dot-hk** [comment]
Missing `make install`?

**Comment by mobileink** [comment]
On Wed, Dec 16, 2020 at 5:02 AM Wong Heung Sang <notifications@github.com>
wrote:

> Missing make install?
>

Something like that.  The critical bit is INSTALLDIR, which determines
where the 'make' rule installs stuff.  For the record, in case anybody else
needs this:

In bzl/host/BUILD.bazel:
package(default_visibility = ["//visibility:public"])
config_setting( name = "linux", constraint_values = [
"@platforms//os:linux" ] )
config_setting( name = "macos", constraint_values =
["@platforms//os:macos"] )

In a BUILD.bazel file:

ENV_VARS = " ".join([
    # "env",
    "ROCKSDB_DISABLE_SNAPPY=1",
    "ROCKSDB_DISABLE_GFLAGS=1",
    "ROCKSDB_DISABLE_LZ4=1",
    "ROCKSDB_DISABLE_ZSTD=1",
    "ROCKSDB_DISABLE_NUMA=1",
    "ROCKSDB_DISABLE_TBB=1",
    "ROCKSDB_DISABLE_JEMALLOC=1",
    "ROCKSDB_DISABLE_TCMALLOC=1",
    "ROCKSDB_DISABLE_BACKTRACE=1",
    "PORTABLE=1",
    "FORCE_SSE42=1",
    "DISABLE_WARNING_AS_ERROR=1",
    "VERBOSE=1",
    "INSTALL_PATH=${INSTALLDIR}", # v5.17.2, v6.0.1
    "PREFIX=${INSTALLDIR}", # v6.14.5
])

VERSION_MAJOR = "5"
VERSION_MINOR = "17"
VERSION_PATCH = "2"

make(
    name = "librocksdb",
    lib_source = "@rocksdb//:all", # mandatory
    out_lib_dir = "lib",
    prefix = "${INSTALLDIR}",
    visibility = ["//visibility:public"],
    static_libraries = ["librocksdb.a"],
    shared_libraries = select({
        "//bzl/host:macos": [
            "librocksdb.dylib",
            "librocksdb.{major}.dylib".format(
                major=VERSION_MAJOR
            ),
            "librocksdb.{major}.{minor}.dylib".format(
                major=VERSION_MAJOR, minor=VERSION_MINOR
            ),
             "librocksdb.{major}.{minor}.{patch}.dylib".format(
                 major=VERSION_MAJOR, minor=VERSION_MINOR,
patch=VERSION_PATCH
             ),
        ],
        "//bzl/host:linux": [
            "librocksdb.so",
            "librocksdb.so.{major}".format(
                major=VERSION_MAJOR
            ),
            "librocksdb.so.{major}.{minor}".format(
                major=VERSION_MAJOR, minor=VERSION_MINOR
            ),
             "librocksdb.so.{major}.{minor}.{patch}".format(
                 major=VERSION_MAJOR, minor=VERSION_MINOR,
patch=VERSION_PATCH
             ),
        ]
    }, no_match_error = "Unsupported platform. MacOS or Linux only."),
    make_env_vars = {
        "PREFIX": "${INSTALLDIR}",
        "VERBOSE": "1"
    },
    make_commands = [
        " ".join([
            # "INSTALL_PATH=${INSTALLDIR}", # v6.0.1
            "make",
            # "install", ## both static and shared
            "install-shared",
            "-j2",
        ]) + " " + ENV_VARS,
        " ".join([
            # "INSTALL_PATH=${INSTALLDIR}", # v6.0.1
            "make",
            "install-static",
            "-j2",
        ]) + " " + ENV_VARS,
    ],
)
