### ISSUE TITLE
cmake_external: how to pkg_tar outputs without copy_ folder

### ISSUE THREAD

**Issue by al-tu** [bazelbuild/rules_foreign_cc#439]
hello
i can't find a way to package results of cmake build without inclusion of copy_ folder, which messes up the resultant tree
example: BUILD file for catch2 library:
```
load("@rules_foreign_cc//tools/build_defs:cmake.bzl", "cmake_external")

filegroup( 
    name = "srcs",
    srcs = glob(["**"]),
    visibility = ["//visibility:public"],
)

cmake_external(
    name = "catch2",
    cache_entries = {
      "CMAKE_BUILD_TYPE" : "Release",
    },
    lib_source = ":srcs",
    headers_only = True,
)

load("@rules_pkg//:pkg.bzl", "pkg_tar")
pkg_tar(
  name = "catch2-tar",
  extension = "tar.gz",
  srcs = [
    ":catch2",
  ],
)
```

after running bazel build //:catch2 i get the following output:
```
bazel-bin/external/catch2/catch2/include
bazel-bin/external/catch2/copy_catch2/catch2
bazel-bin/external/catch2/catch2/logs/CMake_script.sh
bazel-bin/external/catch2/catch2/logs/CMake.log
bazel-bin/external/catch2/catch2/logs/wrapper_script.sh
```

and there's no way to filter inputs for pkg_tar (https://github.com/bazelbuild/rules_pkg/issues/85 is probably relevant)
i suppose there might be a hacky way to write some genrule to delete that copy just before packaging and wrap it all in one rule
but maybe i'm doing something wrong with cmake_external in the first place

**Comment by fmeum** [comment]
I would also be interested in a good solution to this problem. Having a genrule just for filtering out log files does seem very hacky.

**Comment by jsharpe** [comment]
#483 is related to this issue. But also I think that the logs probably shouldn't be included in `DefaultInfo` and should be their own OutputGroup.
