### ISSUE TITLE
where is the documentation?

### ISSUE THREAD

**Issue by symbiont-ji** [bazelbuild/rules_foreign_cc#444]
There are a few simple examples here, but where is the complete documentation for the provided rules?

**Comment by whs-dot-hk** [comment]
What are you trying to build?

**Comment by UebelAndre** [comment]
I have a PR that adds the capability for generated docs https://github.com/bazelbuild/rules_foreign_cc/pull/453 if that gets merged I'll open a follow-up to populate it.

**Comment by UebelAndre** [comment]
We now have generated docs in https://github.com/bazelbuild/rules_foreign_cc/blob/master/docs/README.md

We'll continue to improve documentation but for the foreseeable future that README and the top level README is where the documentation lives.

**Comment by UebelAndre** [comment]
Gonna close this for now. If you have more concerns about the documentation (something missing or unclear) please let us know 😀
