### ISSUE TITLE
what is foreign_cc_platform_utils?

### ISSUE THREAD

**Issue by symbiont-ji** [bazelbuild/rules_foreign_cc#445]
`examples/BUILD` has the line `load("@foreign_cc_platform_utils//:bazel_version.bzl", "BAZEL_VERSION")`, but `foreign_cc_platform_utils` is not defined anywhere.

**Comment by UebelAndre** [comment]
It was being generated in a repository rule if I remember correctly. It's recently been removed in https://github.com/bazelbuild/rules_foreign_cc/commit/d85b575a4071bb0318e8b1e3aef8bf990e330e26 though

**Comment by UebelAndre** [comment]
Gonna close this since it's been removed. If you update your version of `rules_foreign_cc` to that commit or newer then it shouldn't impact you anymore.
