### ISSUE TITLE
Why release code that doesn't work?

### ISSUE THREAD

**Issue by symbiont-ji** [bazelbuild/rules_foreign_cc#446]
$ bazel build //...
Starting local Bazel server and connecting to it...
INFO: Repository remote_coverage_tools instantiated at:
  /DEFAULT.WORKSPACE.SUFFIX:11:13: in <toplevel>
Repository rule http_archive defined at:
  /home/ji/.cache/bazel/_bazel_ji/c847f071cfe595e49d189cf4d2639f27/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
INFO: Repository 'remote_coverage_tools' used the following cache hits instead of downloading the corresponding file.
 * Hash 'cd14f1cb4559e4723e63b7e7b06d09fcc3bd7ba58d03f354cdff1439bd936a7d' for https://mirror.bazel.build/bazel_coverage_output_generator/releases/coverage_output_generator-v2.5.zip
If the definition of 'remote_coverage_tools' was updated, verify that the hashes were also updated.
ERROR: While resolving toolchains for target //tools/build_defs/native_tools:make_tool: invalid registered toolchain '@rules_foreign_cc_tests//:built_cmake_toolchain': no such target '@rules_foreign_cc_tests//:built_cmake_toolchain': target 'built_cmake_toolchain' not declared in package '' defined by /home/ji/.cache/bazel/_bazel_ji/c847f071cfe595e49d189cf4d2639f27/external/rules_foreign_cc_tests/BUILD
ERROR: Analysis of target '//tools/build_defs/native_tools:make_tool' failed; build aborted: invalid registered toolchain '@rules_foreign_cc_tests//:built_cmake_toolchain': no such target '@rules_foreign_cc_tests//:built_cmake_toolchain': target 'built_cmake_toolchain' not declared in package '' defined by /home/ji/.cache/bazel/_bazel_ji/c847f071cfe595e49d189cf4d2639f27/external/rules_foreign_cc_tests/BUILD
INFO: Elapsed time: 4.157s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (21 packages loaded, 47 targets configured)
    Fetching ...7f071cfe595e49d189cf4d2639f27/external/remote_coverage_tools; Extracting /home/ji/.cache/bazel/_bazel_ji/c847f071cfe595e49d189cf4d2639f27/external/remote_coverage_tools/temp13653568990184657603/coverage_output_generator-v2.5.zip
ji@rsi:~/rules_foreign_cc$ bazel build //...
ERROR: While resolving toolchains for target //tools/build_defs/native_tools:cmake_tool: invalid registered toolchain '@rules_foreign_cc_tests//:built_cmake_toolchain': no such target '@rules_foreign_cc_tests//:built_cmake_toolchain': target 'built_cmake_toolchain' not declared in package '' defined by /home/ji/.cache/bazel/_bazel_ji/c847f071cfe595e49d189cf4d2639f27/external/rules_foreign_cc_tests/BUILD
ERROR: Analysis of target '//tools/build_defs/native_tools:built_cmake' failed; build aborted: invalid registered toolchain '@rules_foreign_cc_tests//:built_cmake_toolchain': no such target '@rules_foreign_cc_tests//:built_cmake_toolchain': target 'built_cmake_toolchain' not declared in package '' defined by /home/ji/.cache/bazel/_bazel_ji/c847f071cfe595e49d189cf4d2639f27/external/rules_foreign_cc_tests/BUILD
INFO: Elapsed time: 0.099s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded, 0 targets configured)

**Comment by jsharpe** [comment]
I believe these issues should now be resolved on master. Let us know if you still have issues.
