### ISSUE TITLE
Build under Bazel sandbox instead of /tmp

### ISSUE THREAD

**Issue by UebelAndre** [bazelbuild/rules_foreign_cc#478]
https://github.com/bazelbuild/rules_foreign_cc/pull/367 was originally opened some time ago to solve for this but ended up not being merged. This sort of change seems incredibly beneficial and might solve a few issues users are seeing.

**Comment by UebelAndre** [comment]
@attilaolah Just FYI, I made an issue so this isn't forgotten.

**Comment by attilaolah** [comment]
Thanks for opening this.

Note that this is likely going to break e.g. Python, which requires runtime dependencies for all the non-builtin modules, as discussed in #419. A solution would be to extract all Python files from the `copy_` directory, like it is suggested in #320, although I believe there is a simpler way to do that, e.g. I recently pushed https://github.com/attilaolah/wasm/commit/47e3ac67324a5122b15aace6dc4e57356253dd42 to work around exactly this issue.
