### ISSUE TITLE
Provide a stable API for accessing all build artifacts

### ISSUE THREAD

**Issue by attilaolah** [bazelbuild/rules_foreign_cc#482]
Currently this is possible using the `copy_…` output of the CMake/Make/… rules, but it doesn't seem to be advertised very widely, and it seems to be a bit of a hack to use. For example, I ended up with something like this recently:

In [`installed_files.bzl`](https://github.com/attilaolah/wasm/blob/main/tools/installed_files.bzl):
```
load("@bazel_skylib//lib:paths.bzl", "paths")

def _installed_files_impl(ctx):
    return [DefaultInfo(files = depset([
        dep
        for dep in ctx.files.deps
        if (dep.is_directory and
            paths.basename(dep.dirname).startswith("copy_"))
    ]))]

installed_files = rule(
    implementation = _installed_files_impl,
    attrs = {
        "deps": attr.label_list(
            doc = "List of targets built with cmake_external(), configure_make() or make().",
            mandatory = True,
        ),
    },
)
```

Then in the [`BUILD`](https://github.com/attilaolah/wasm/blob/main/tools/python/BUILD.bazel) file, I do:
```
configure_make(
    name = "python",
    …
)

installed_files(
    name = "runtime",
    deps = [":python"],
)
```

And finally, in places where I need to run Python, I will depend on both `:python` and `:runtime`, and set the `PYTHONHOME` env var to the root of `:runtime`.

While this works, there are a few caveats:

- Any generated output file that happens to start with `copy_` would be picked up.
- The runtime files do not live under the same directory tree as the actual `configure_make()` output.

Te solve the first problem, I think we could extend the provider returned by `configure_make()` to include this "copy_" directory, and then use the provider to pick up the value in `_instaddeld_files_impl()`.

But in the end, it would be even nicer if we could simply declare output directories in `configure_make()`, much like it is suggested in #419. In addition, it might be possible to avoid generating the `copy_` directory altogether if we add this feature? That would also be helpful e.g. for #439.

**Comment by jsharpe** [comment]
Does the `OutputGroup` `gen_dir` not work for this?

**Comment by attilaolah** [comment]
You mean for providing the filename for the `copy_` directory? Probably it does — I haven't checked.

**Comment by jsharpe** [comment]
No, I mean providing a `filegroup` e.g.
```
filegroup(
    srcs = ":my_cmake_project",
    output_group = "gen_dir",
)
```
does the equivalent to  your installed_files rule?

**Comment by attilaolah** [comment]
Ah I see. (I was trying to use `ctx.attr.deps[…][OutputGroupInfo] and that seems to work too.)

But it works, you're right. So this is what I have now:

```
filegroup(                                                                                                              
    name = "runtime",                                                                                                   
    srcs = [":python"],                                                                                                 
    output_group = "gen_dir",                                                                                           
) 
```

I think that should be good enough for my use case. Lemme close this feature request then.

Thanks for pointing out that these rules provide different output groups!

**Comment by jsharpe** [comment]
One slight annoyance with `gen_dir` though is how it includes the log files. This probably shouldn't be the case as it causes file conflicts when you try to combine multiple `rules_foreign_cc` built targets into a single `filegroup`

**Comment by attilaolah** [comment]
Can we put the log files into a different output group then?

**Comment by jsharpe** [comment]
I think we should be able to; I did look at this a while back but I think due to the logs being under the directory artifact which gets put into the `gen_dir` output dir then it would require us to put the logs directory in a different location so I didn't get round to fixing it then.
