### ISSUE TITLE
Support some sort of configure "wrapper"

### ISSUE THREAD

**Issue by attilaolah** [bazelbuild/rules_foreign_cc#486]
Here's the problem: I can pass Emscripten wrappers to `make_commands` like so:

```
    make_commands = [
        "emmake make",
        "emmake make install",
    ],
```

Same for using `emcmake cmake` instead of `cmake`. In fact, the nice way of doing this is by registering the configure/make/cmake toolchains for Emscripten that wrap these commands.

The problem is, I can't do it with `configure`, because it is prefixed by the source location, and there is no easy way to put anything in front of it.

[My workaround](https://github.com/attilaolah/wasm/blob/main/toolchains/make/env_vars.bzl) for now is to use an `emconfigure.sh`, which then calls `emconfigure` like so:

```sh
"${EXT_BUILD_DEPS}/bin/emscripten/emconfigure" $(dirname $0)/configure $@
```

I then patch this `emconfigure.sh` into the source tree of the external workspace using `patch_cmds`.

This works and all, but is somewhat hacky, and inconvenient, since now every time I decide to change something in the env vars that get added to `emconfigureg.sh`, the remote source tree changes, triggering a full rebuild of every external workspace, for every target (not just `wasm32`).

Instead, it should be possible to implement a sort-of configure wrapper, that would come before the `…/configure` command?

---

Or maybe there is a better way to do what I'm doing with the workspace patching? I'd be really happy if I wouldn't have to patch.

**Comment by jlaxson** [comment]
I've had the same questions/thoughts.  A few of my use cases:
* Alter flags in ways that interact with environment variables.  For instance, a configure script that doesn't respect CC/CXX but has the flags `--cc=/path/to/gcc` etc.  
* Modify the EXT_BUILD_DEPS tree so the configure script detects dependencies correctly.  In my case, remove static libraries and rename the .so variants

I have tried to inject the wrapper script by appending it to lib_source, passing to additional_tools/additional_inputs/tools_deps etc but haven't seen them show up in the sandbox source tree.

@attilaolah Thanks for turning me on to patch_cmds, I had done a similar thing for my first bullet but in a substantially hackier way.

**Comment by UebelAndre** [comment]
This has been addressed by https://github.com/bazelbuild/rules_foreign_cc/pull/676
