### ISSUE TITLE
configure_in_place causes (near?) infinite symlink recursion

### ISSUE THREAD

**Issue by attilaolah** [bazelbuild/rules_foreign_cc#505]
In #479 I've added [an exception](https://github.com/bazelbuild/rules_foreign_cc/pull/479/files#diff-3796b11de709dc4560c4cc5892d3385d3cdaac834856ce2aa33a05ad1fce3273L103-R102) for `.ext_build_deps`, maybe we need one for `.build_tempdir` as well, for the case when `configure_in_place` is set.

Also maybe a failing test case would be nice.

**Comment by whs-dot-hk** [comment]
Maybe revert #479 ? Clean up function is always there...

**Comment by jsharpe** [comment]
configure_with_bazel_transitive on macOS seems to exhibit this failure - its not enabled in CI though.

**Comment by attilaolah** [comment]
It's odd that it would be platform-specific though. In the meantime, I found out that in my case the error was caused by something else, and not the symlink tree (there just happened to be a very deep directory layout, generated by `./configure` & `make`, for some reason.)

**Comment by UebelAndre** [comment]
You should check out `tools/build_defs/shell_toolchain/toolchains/impl/osx_commands.bzl` in https://github.com/bazelbuild/rules_foreign_cc/pull/514. There's a snippet on line 128 that was there for every platform but MacOS.

**Comment by attilaolah** [comment]
Oops, you're right! Looks like I missed adding that exception to `osx_commands.bzl`. Thanks for adding it!

**Comment by UebelAndre** [comment]
Do you think that would cause the recursive behavior we're seeing?

**Comment by attilaolah** [comment]
I think so.
