### ISSUE TITLE
boost_build with local boost submodule

### ISSUE THREAD

**Issue by traceon** [bazelbuild/rules_foreign_cc#510]
(Bazel beginner here) Is it possible to use `boost_build` with a local boost source tree snapshot/git submodule instead of downloading it, i.e, when I have it under `third_party/boost`?

**Comment by UebelAndre** [comment]
Yeah, I don't see why not. Can you a bit more about what you're looking to do with [build_boost](https://github.com/bazelbuild/rules_foreign_cc/tree/main/docs#boost_build)? Maybe an example build file?

**Comment by traceon** [comment]
Don't really have any example, just want to be able to build my boost sources snapshot, and be able to link in [some] boost libs, built this way, into my other targets.

**Comment by UebelAndre** [comment]
We're definitely looking into ways to have better examples. Does https://github.com/bazelbuild/rules_foreign_cc/pull/474 help you out at all?

**Comment by jsharpe** [comment]
I would recommend looking towards https://github.com/nelhage/rules_boost first as this will build the libraries in isolation. You can override the included version of boost sources by defining a `local_repository` from your snapshot before calling the boost_deps macro.

**Comment by traceon** [comment]
@jsharpe thanks, I'll definitely give it a try! The work done there deserves respect. However, it seems to me that this approach will require constant maintenance with each boost upgrade, at least theoretically. 

@UebelAndre the existing example works just fine, but downloads the archive with sources by default. What I haven't figured out is how to use a folder instead.

**Comment by UebelAndre** [comment]
You should hop in the [Bazel Slack Channel](https://bazelbuild.slack.com/archives/CA31HN1T3) to get quicker feedback and more helpful eyes.

In general though. You can setup a `.bazelignore` file in your top level workspace and use `local_repository` to create the repository you care about. Similar to what's happening in this repo with the examples. [.bazelignore](https://github.com/bazelbuild/rules_foreign_cc/blob/main/.bazelignore#L2) and [top level WORKSPACE file](https://github.com/bazelbuild/rules_foreign_cc/blob/main/WORKSPACE#L7-L10)

**Comment by traceon** [comment]
> You should hop in the Bazel Slack Channel to get quicker feedback and more helpful eyes.

Got this:
```
Don’t have an @google.com email address?
Contact the workspace administrator at Bazel for an invitation.
```
Who should I contact, do you know?

**Comment by UebelAndre** [comment]
Hmm, I thought it was public 
👋  Let’s move this to Slack! We’ve got 2588 folks from the team there already. You can sign up here: https://join.slack.com/t/bazelbuild/shared_invite/zt-dzm4qj0h-maSR3EcEr8SWE1f7dA55zw

**Comment by traceon** [comment]
> In general though. You can setup a `.bazelignore` file in your top level workspace and use `local_repository` to create the repository you care about. Similar to what's happening in this repo with the examples. .bazelignore and top level `WORKSPACE` file

With `WORKSPACE`:
```
...
local_repository(
    name = "boost",
    path = "third_party/boost",
)
...
```

...and `third_party/BUILD.bazel`:
```
...
load("@rules_foreign_cc//tools/build_defs:boost_build.bzl", "boost_build")
boost_build(
    name = "boost",
    lib_source = "@boost//:all"
)
...
```

If I put `third_party` in `.bazelignore`, and run `bazel build //third_party:boost`, I get:
```
ERROR: Skipping '//third_party:boost': no such package 'third_party': Package is considered deleted due to --deleted_packages
```

...and if I put `third_party/boost` in `.bazelignore`, and run `bazel build //third_party:boost`, I get:
```
ERROR: /path/third_party/BUILD.bazel:5:12: //third_party:boost depends on @boost//:all in repository @boost which failed to fetch. no such package '@boost//': No WORKSPACE file found in /private/var/tmp/_bazel_path/da18835db896305bb46480859a6b605c/external/boost
```

**Comment by UebelAndre** [comment]
You would build `@boost//...` or something. But try the slack link

**Comment by traceon** [comment]
Joined the slack, asked in `#cc`. Thanks!

**Comment by UebelAndre** [comment]
Gonna close this for now then. Happy slacking 😄

**Comment by traceon** [comment]
@jsharpe https://github.com/nelhage/rules_boost/issues/9 has the same issue, however, there, it is kind of justified, since the source structure is hardcoded in the scripts.

**Comment by sunstarchan** [comment]
> You would build `@boost//...` or something. But try the slack link



> Hmm, I thought it was public
> 👋 Let’s move this to Slack! We’ve got 2588 folks from the team there already. You can sign up here: ~link~

Could you invite me to the Bazel Slack channel?
