### ISSUE TITLE
HDF5 CMake re-builds are non-deterministic

### ISSUE THREAD

**Issue by attilaolah** [bazelbuild/rules_foreign_cc#517]
Building [HDF5](https://www.hdfgroup.org/downloads/hdf5/) version 1.12.0 using `cmake` results in cache-misses every time the library is re-built.

The reason appears to be that the build script re-generates some of the source files (that are under `${BUILD_ROOT}/external/…`) and the order of lines appears to be non-deterministic.

This is bad, and the build script probably shouldn't do that, but I'm now wondering: would it be possible to prevent this somehow, e.g. by giving a *copy* of the source files to the build script, and throwing away the copy after the build? I think currently the build gets a symlink tree, and what I'm suspecting is going on is that the build script follows the symlinks and messes with the original files.

**Comment by UebelAndre** [comment]
Oof, that's unfortunate... Is this something newly discovered or was there a regression?

**Comment by attilaolah** [comment]
No I think this was always the case. Just never noticed it until I set up a remote cache, then saw that HDF5 was rebuilding all the time, and did some debugging.

I think I can work around it for now, either by using custom make commands that back up and restore the four files in question, or patch the perl script, so that even if it modified the source, at least the modification would be deterministic (currently it relies on hash table key ordering which is non-deterministic in Perl). At least the second time it would no longer make any changes to the source files.

**Comment by attilaolah** [comment]
Or, maybe I can patch those auto-generated files out of the source tree with `patch_cmds = "rm …"`. That way even if they get regenerated, the new files will end up in the symlink tree and not clobber any originals. Also they will not be part of the inputs so they should not dirty the cache.

**Comment by attilaolah** [comment]
OK I figured out that I can just wipe those files from the sources, then they don't clobber the input, and I get cache hits. Like so:

```
    patch_cmds = [                                                                                                     
        # Auto-generated headers, keep sorted:                                                                         
        "rm src/H5Edefin.h",                                                                                           
        "rm src/H5Einit.h",                                                                                            
        "rm src/H5Epubgen.h",                                                                                          
        "rm src/H5Eterm.h",                                                                                            
    ],                                                                                                                 
```

**Comment by UebelAndre** [comment]
So was this a complexity in how HDF5 is built or how the rules function? Is there something in `rules_foreign_cc` that should be implemented to mitigate this? It seems like the issue is in HDF5 to me though

**Comment by attilaolah** [comment]
I think too that the issue is in HDF5. And quite easy to work around with the `patch_cmds` so I'd leave it as-is for now.

**Comment by attilaolah** [comment]
(And even without the workaround, the only issue is the cache misses, which is annoying, but not the end of the world since HDF5 builds in just a few minutes.)

**Comment by UebelAndre** [comment]
I mean, it could be the end of the world depending on what's depending on HDF5. Just saying 😅
