### ISSUE TITLE
CMake lib dir selection is not portable

### ISSUE THREAD

**Issue by slsyy** [bazelbuild/rules_foreign_cc#518]
Depending on system the CMake select different output lib directory:

- Centos 8: `/lib64`
- Manjaro 20: `/lib`

I would like to add some bool flag to the `cmake_external` rule, which add an entry: `-DCMAKE_INSTALL_LIBDIR=${out_lib_dir}` to the `cmake_options`, so it should work in the same way on all systems. IMO it should be enabled by default, but I guess such a change break backward compatibility.

What do you think?

**Comment by jsharpe** [comment]
This makes a lot of sense to me as a lot of projects make use of the GNUInstallDirs options in CMake.
I guess we should also set `CMAKE_INSTALL_BINDIR` and `CMAKE_INSTALL_INCLUDE_DIR` too.

**Comment by jsharpe** [comment]
https://github.com/bazelbuild/rules_foreign_cc/pull/710#issuecomment-907690236

From attempting to implement this I think unfortunately we can't automatically set this as it seems like it can break projects configuration, particularly where they haven't quite followed the GNUInstallDirs docs fully or have implemented some custom behaviour around these settings.

I'm going to close this but it can be reopened if anyone can come up with a good way of implementing this that doesn't break things
