### ISSUE TITLE
How to consume cmake_external (openssl) rule in another cmake_external rule (postgres)?

### ISSUE THREAD

**Issue by jschaf** [bazelbuild/rules_foreign_cc#537]
I'm trying to build Postgres with openssl support. I'm able to build openssl successfully and Postgres (without openssl) successfully. I can't figure out how to add openssl as included library during Postgres compilation.

https://gist.github.com/jschaf/940e9c67c6ac8fc23b4d853ed379dc7d

Here's the modifications to the postgres rule:
```
configure_make(
    name = "postgres",
    configure_options = [
        "CFLAGS='-Dredacted=\\\"redacted\\\"'",
        "--with-includes=${EXT_BUILD_DEPS}/openssl/include",
        "--with-openssl",
    ],
    deps = [
        "//third_party/openssl",
    ],
)
```

The Postgres configure script errors with:

```
checking for CRYPTO_new_ex_data in -lcrypto... no
configure: error: library 'crypto' is required for OpenSSL
```

The `Configure_script` is included in the [gist](https://gist.github.com/jschaf/940e9c67c6ac8fc23b4d853ed379dc7d).

**Comment by UebelAndre** [comment]
Maybe check out some of the third party examples? https://github.com/bazelbuild/rules_foreign_cc/blob/main/examples/third_party/libgit2/BUILD.libgit2.bazel

There's examples of consuming OpenSSL there. Is that what you're looking for?

**Comment by jschaf** [comment]
Thank you, I was getting tripped up by how to add SSL libraries as a configure option which requires knowing about `EXT_BUILD_DEPS`.  I figured it out from this thread: https://github.com/bazelbuild/rules_foreign_cc/issues/442#issuecomment-789037893
