### ISSUE TITLE
tool_deps symlinks wrong dir in 0.1.0

### ISSUE THREAD

**Issue by celentes** [bazelbuild/rules_foreign_cc#546]
In prior version (i was using commit 78dd4749941c0031e107cccbc441c7eeb89accd0), putting a tool built with cmake to tool_deps produced the following line of wrapper script:
`symlink_to_dir $EXT_BUILD_ROOT/bazel-out/host/bin/external/corrade/rc $EXT_BUILD_DEPS/bin/`
but now it produces this one:
`symlink_to_dir $EXT_BUILD_ROOT/bazel-out/host/bin/external/corrade/rc/include $EXT_BUILD_DEPS/bin/`
which then results in the tool not being found.

Tried circumventing it with also adding the tool to deps, does not help.

**Comment by UebelAndre** [comment]
Thanks for the reporting the issue and sorry about the inconvenience! Do you have a reproduction case you could share so I can look into this?

**Comment by celentes** [comment]
It is a bit too hairy a repro case to share at the moment, but i have traced it locally.
Basically, somewhere between 78dd474 and 0.1 tag, there was a change to `tools/build_defs/detect_root.bzl`.
The target in question is built with `cmake_external` and produces no headers, just one binary, but when fed into detect_root, it sees the following files/dirs:
```
external/corrade/rc/include
external/corrade/rc/bin/corrade-rc
external/corrade/copy_rc/rc
```
Now, looking at the code, I don't think detect_root was working _correctly_ previously, but it was, perhaps accidentally, doing what i wanted it to do. As far as I can tell, it was broken before and is still broken right now.
Generally speaking, detecting a tool/dependency root should be as easy as the common path prefix between the set of files fed into the rule, so I thought i'd just go in quickly and fix the rule myself, but that last line with copy_rc complicates things, and it made me wonder whether there are some other reasons why the rule implementation looks like it does right now.

**Comment by UebelAndre** [comment]
My understanding is that there's two ways to consume artifacts of a `foreign_cc` rule. One is to consume the file outputs directly (ie: when you specify `static_library`, and then consume it with a `filegroup` of some sort) and the second is to depend on the output base (the `include`, `lib`, and `bin` directories). The way the rules are currently built is to build everything within the "copy" directory which contains all build outputs and then the built artifacts are copied into the install directory where Bazel then only keeps the declared files.

This behavior has been a large point of confusion for me and have a feeling there's a clearer way to specify the intended behavior. One thing you could do is not depend on the `corrade` target but create a filegroup to maybe exclude the other outputs?

https://github.com/bazelbuild/rules_foreign_cc/blob/175b29c6f78cf3c78516836587c268f3d0690526/examples/third_party/openssl/BUILD.openssl.bazel#L51-L56

would that work in your case?

**Comment by UebelAndre** [comment]
This is something that can be easily fixed. If the target contains a `ForeignCcDeps` provider, we can wire up all the correct things so users don't have to think about this. The issue for me is that there are numerous ways that users can define dependencies that I don't feel add great value (https://github.com/bazelbuild/rules_foreign_cc/issues/490). I'd like to clean that up first then begin to streamline things further.

**Comment by UebelAndre** [comment]
Also, have you tried adding something like the following?
https://github.com/bazelbuild/rules_foreign_cc/blob/b7c0461a66009864589a15c392872ec1f7551cdd/examples/third_party/curl/BUILD.curl.bazel#L11

**Comment by celentes** [comment]
That is how it is set up right now, yes. It exposes `corrade/rc/include` instead of `corrade/rc`, so i wouldn't get access to the correct file. Exposing `@corrade//:rc` in both tools and deps does not solve it either because in deps it gets `copy_rc` instead of `rc` and therefore bazel does not propagate the correct executable file to `tools` in `ctx.actions.run`.
Solved by:
```
load("@bazel_skylib//rules:select_file.bzl", "select_file")
select_file(
    name = "corrade-rc",
    srcs = ":rc",
    subpath = "bin/corrade-rc",
)
```

**Comment by celentes** [comment]
That solution of checking whether `tools_deps` has `ForeignCcDeps` in providers sounds like the best longterm solution here.
