### ISSUE TITLE
Release v0.1.0 zip download does not contain "cmake" rule

### ISSUE THREAD

**Issue by jbremnant** [bazelbuild/rules_foreign_cc#553]
I am trying to use this zip file using bazel `http_archive`:  https://github.com/bazelbuild/rules_foreign_cc/archive/0.1.0.zip
The extracted content doesn't seem to contain the rule `cmake` in `tools/build_defs/cmake.bzl`:

```bash
$ wget https://github.com/bazelbuild/rules_foreign_cc/archive/0.1.0.zip
$ unzip 0.1.0.zip                                                      
$ egrep "^cmake" rules_foreign_cc-0.1.0/tools/build_defs/cmake.bzl       
cmake_external = rule(          
```                                                                                  
Is this intended? The latest git clone of this repository shows both `cmake` and `cmake_external` rules.

**Comment by hoffbrinkle** [comment]
In release 0.1.0, it was only `cmake_external`.  This change happened after 0.1.0. https://github.com/bazelbuild/rules_foreign_cc/commit/f307e857f6f40f9c0b5ce73960e3d5b77ab788bb#diff-ad1028fe2e4d4d692b530b1994ea0a812bd2c9a4856fbda767a79b26d35f92e0

**Comment by UebelAndre** [comment]
Ah, the rule was *just* added in a recent commit and we have not cut a new release since. Try viewing the docs at the `0.1.0` tag. `cmake_external` should continue to work for you though.

**Comment by UebelAndre** [comment]
We're looking to have a much higher release cadence so expect a release with the newly named rule soon.

**Comment by jbremnant** [comment]
I see. Thanks for the note.

**Comment by UebelAndre** [comment]
Release `0.2.0` was just cut and has the cmake rule located in `@rules_foreign_cc//foreign_cc:cmake.bzl`. You can additionally load the rules through `@rules_foreign_cc//foreign_cc:defs.bzl` in cases where you have uses of multiple rules in the same file. Going to close this issue for now, please don't hesitate to open any new issues for `0.2.0`.
