### ISSUE TITLE
Can't `bazel run` things generated as `out_binaries`

### ISSUE THREAD

**Issue by illicitonion** [bazelbuild/rules_foreign_cc#582]
I put together a `rules_foreign_cc` rule for building a binary which builds with configure+make, and wanted to be able to `bazel run` it.

This was tricky - a bunch of the things I wanted to do didn't work:

First I tried to just `bazel run` the target, but the target isn't labelled as `executable`. Rules can't be conditionally marked `executable` based on e.g. whether they have `out_binaries` (or exactly one `out_binary`). We could do something like "always run the first `out_binary` if there are any, and generate a dummy executable if not", but that seems kind of sketchy, and ideally the `run`-ability could be decided at analysis time.

Next I tried to copy the generated file in a `genrule` marked `executable=True`, but the generated file didn't have an associated label (for `//target:my` with an `out_binary` named `binary`, I couldn't write `//target:my/bin/binary`).

So I ended up writing a wrapper rule, `runnable_binary` which depends on the `rules_foreign_cc` target, looks up the file in the provider and does the copy, and is marked as `executable`.

I can upstream `runnable_binary` if folks would be interested, but I'd be interested in whether there's a better approach here...

**Comment by jsharpe** [comment]
This is similar to what https://github.com/bazelbuild/rules_foreign_cc/pull/417 is attempting to address. It's a tricky problem as we don't know what the runtime dependencies are between the files generated in the `gen_dir` output group is as this is not made explicit to bazel. The standard way of using runfiles in bazel to provide any data files needed by a runnable target generated by a `rules_foreign_cc` rule is unlikely to be correct and so a general solution probably needs to wrap the declared `out_binary`'s somehow and ensure the correct relative file layout is setup. 

I have wondered if we could approach this with aspects and generate the set of `executable` targets that way?

**Comment by UebelAndre** [comment]
I like the idea of a wrapper rule for defining runnable targets

**Comment by KennyS** [comment]
Hey @illicitonion, I just ran into the same issue, could you share "runnable_binary"? If the repo isn't shareable a pastebin or gist link would be great

**Comment by illicitonion** [comment]
Absolutely; this is what we're currently using:

```starlark
def _impl(ctx):
    name = ctx.attr.binary_name or ctx.attr.name
    input = ctx.attr.generated_by[OutputGroupInfo][name].to_list()[0]
    output = ctx.actions.declare_file(name)

    # We're not allowed to specify a file generated by another rule as our executable, so copy it.
    #   
    # Implemented after skylib's `copy_file` rule:
    # We need access to the `OutputGroupInfo` provider, so we can't use that rule wholesale.
    # Ref: https://github.com/bazelbuild/bazel-skylib/blob/main/docs/copy_file_doc.md
    #   
    # Note: We need to use `run_shell` instead of `run` here because bazel ignores `--action_env` for `run`,
    #       which means that $PATH (and therefore `cp`) is not accessible.
    ctx.actions.run_shell(
        inputs = [input],
        outputs = [output],
        command = "cp -f \"$1\" \"$2\"",
        arguments = [ 
            input.path,
            output.path,
        ],  
        mnemonic = "CopyRunnableBinary",
        progress_message = "Copying binary file",
    )   
    return [DefaultInfo(
        executable = output,
        runfiles = ctx.runfiles(transitive_files = ctx.attr.generated_by[OutputGroupInfo]["gen_dir"]),
    )]  

runnable_binary = rule(
    doc = "A wrapper around a rules_foreign_cc target which can be `bazel run`",
    implementation = _impl,
    attrs = { 
        "generated_by": attr.label(
            mandatory = True,
            doc = "The rules_foreign_cc target which listed the generated file in its out_binaries attribute",
        ),  
        "binary_name": attr.string(
            doc = "The name of the binary (which should be the same as the value in the out_binaries attribute of the generated_by target). If not set, the name of this target will be used.",
        ),  
    },  
    executable = True,
)
```

**Comment by KennyS** [comment]
@illicitonion  Thanks, works great!
