### ISSUE TITLE
built make fails to build on Windows

### ISSUE THREAD

**Issue by jsharpe** [bazelbuild/rules_foreign_cc#589]
Using `make_tool` to build make for windows fails to successfully build.

**Comment by jheaff1** [comment]
Hi,

Any update on this? If I find time I’ll take a look at this.

**Comment by UebelAndre** [comment]
Neither @jsharpe or I are super experienced with windows so if you have some familiarity and time, we'd love your help! 😄

**Comment by jheaff1** [comment]
Sadly I have no experience with software development in Windows but if I find the time I’ll see what I can do!

**Comment by jheaff1** [comment]
Please see PR #716
