### ISSUE TITLE
Absolutize tool paths for configure_make for hermetic toolchains

### ISSUE THREAD

**Issue by jheaff1** [bazelbuild/rules_foreign_cc#593]
Hi,

I’m using a custom cc toolchain with wrappers around the tools checked into my repo, eg //toolchains/gcc_x86_64_linux_musl/wrappers/gcc.

It appears that the `configure_make` rule sets the CXX variable as “ toolchains/gcc_x86_64_linux_musl/wrappers/gcc”. This path is not accessible by the directory in which the build actions take place, therefore the build action fails.

`cmake` rules, however, are successful with my cc toolchain.

After digging around the rules_foreign_cc repo, [cmake_script.bzl](https://github.com/bazelbuild/rules_foreign_cc/blob/bae11c9a508953c1ec3a564102630878737de99d/foreign_cc/private/cmake_script.bzl#L244) sets the `force` flag of `absolutize_path_in_str` to `True`.  However, [`get_env_vars`](https://github.com/bazelbuild/rules_foreign_cc/blob/bae11c9a508953c1ec3a564102630878737de99d/foreign_cc/private/make_script.bzl#L44) used by [configure_script.bzl](https://github.com/bazelbuild/rules_foreign_cc/blob/main/foreign_cc/private/configure_script.bzl) does not set the `force` flag of `absolutize_path_in_str`.

Would I be correct in stating that a solution to the issue is to just set the `force` flag to True in the `_absolutize` function of [make_script.bzl](https://github.com/bazelbuild/rules_foreign_cc/blob/bae11c9a508953c1ec3a564102630878737de99d/foreign_cc/private/make_script.bzl#L163).

**Comment by UebelAndre** [comment]
> Would I be correct in stating that a solution to the issue is to just set the `force` flag to True in the `_absolutize` function of [make_script.bzl](https://github.com/bazelbuild/rules_foreign_cc/blob/bae11c9a508953c1ec3a564102630878737de99d/foreign_cc/private/make_script.bzl#L163).

That's a good question, I think that'd be the correct thing to do. Given that we don't use the default exec root (instead we make a new directory and `cd` into it), all traditional `$(execroot foo)` paths will be wrong so we'd always want to prepend the path to the original exec root. I can't think of why we wouldn't always do this. Perhaps this creates an issue with caching? I don't believe so though... Give it a shot and open a PR? We'll see if the build reveal anything.

**Comment by jheaff1** [comment]
I too did wonder why all non-absolute paths shouldn’t be absolutized. Changing the implementation of `absolutize_path_in_str` as such could cause wider issues though.

I’ll submit a PR to simply change the `_absolutize` method in `make_script.bzl` to set the `force` flag to `True`

**Comment by jheaff1** [comment]
Resolved by https://github.com/bazelbuild/rules_foreign_cc/pull/601
