### ISSUE TITLE
build with specific openssl

### ISSUE THREAD

**Issue by walkanywhere** [bazelbuild/rules_foreign_cc#621]
Hi guys, 

In my project, I build a configure archive for getting dev libraries, but I want to use the specific openssl I compiled before hand. So I set this in configure_make
```
deps = ["//thirdparty:openssl"]
```

Then rules_foreign_cc links a lib directory to build the archive, but the problem is its EXT_BUILD_ROOT is ${REAL_ROOT}/"sandbox/processwrapper-sandbox/18/${XXX}" which actually doesn't have my openssl libraries and headers.  I mean my openssl files are in ${REAL_ROOT}/${XXX} without the extra part of ""sandbox/processwrapper-sandbox/18"

May I know how I could let rules_foreign_cc have the correct root path? If using a sandbox is its way of building, how could I let my openssl files to be in places it likes (I mean, in the path with the extra part)?

Regards

**Comment by UebelAndre** [comment]
Hi, I'm not sure I understand what the goal is. You want to use a specific version of OpenSSL? We have an example of exactly this at https://github.com/bazelbuild/rules_foreign_cc/blob/main/examples/third_party/libssh2/BUILD.libssh2.bazel

Is that related to what you want to do?

**Comment by walkanywhere** [comment]
> Hi, I'm not sure I understand what the goal is. You want to use a specific version of OpenSSL? We have an example of exactly this at https://github.com/bazelbuild/rules_foreign_cc/blob/main/examples/third_party/libssh2/BUILD.libssh2.bazel
> 
> Is that related to what you want to do?

Hi Uebel,

I checked that but found it's a bit different. 

From my understanding(maybe wrong), rules_foreign_cc builds in sandbox. So if everything get built by rules_foreign_cc, it should be fine as they are all in a sandbox. 

My case is there's already an openssl built years ago and my new library project(configure-based, not cmake-based) has to use it. So I use "deps" parameter to introduce the dependency with configure_make. But since rules_foreign_cc works in a sandbox, it creates a symbolic link of my openssl directory in its sandbox, so the links are wrong, technically. that's what I meant it is supposed to be in "${REAL_ROOT}/${XXX}" instead of being in "${REAL_ROOT}/"sandbox/processwrapper-sandbox/18/${XXX}"".

kind of like this (https://github.com/bazelbuild/rules_foreign_cc/issues/13#issuecomment-412146904)

**Comment by UebelAndre** [comment]
Sounds like you might be able to use [cc_import](https://docs.bazel.build/versions/master/be/c-cpp.html#cc_import) to define your version of openssl which you might be able to wire up using the [deps](https://github.com/bazelbuild/rules_foreign_cc/tree/main/docs#configure_make-deps) attribute or if that doesn't work for you you could probably use one of the env variables ([configure_env_vars](https://github.com/bazelbuild/rules_foreign_cc/tree/98c88de5e0f57dd2a896dd595469ccd6bf97ceab/docs#configure_make-configure_env_vars) or [env](https://github.com/bazelbuild/rules_foreign_cc/tree/98c88de5e0f57dd2a896dd595469ccd6bf97ceab/docs#configure_make-env)) to `$EXT_BUILD_ROOT/$(execpath //thirdparty:openssl)`. Does that help?

**Comment by walkanywhere** [comment]
> Sounds like you might be able to use [cc_import](https://docs.bazel.build/versions/master/be/c-cpp.html#cc_import) to define your version of openssl which you might be able to wire up using the [deps](https://github.com/bazelbuild/rules_foreign_cc/tree/main/docs#configure_make-deps) attribute or if that doesn't work for you you could probably use one of the env variables ([configure_env_vars](https://github.com/bazelbuild/rules_foreign_cc/tree/98c88de5e0f57dd2a896dd595469ccd6bf97ceab/docs#configure_make-configure_env_vars) or [env](https://github.com/bazelbuild/rules_foreign_cc/tree/98c88de5e0f57dd2a896dd595469ccd6bf97ceab/docs#configure_make-env)) to `$EXT_BUILD_ROOT/$(execpath //thirdparty:openssl)`. Does that help?

seems not, thanks u, anyway. Could you guys please have some examples showing how to use third-party binary libraries since being limited to some specific/binary libraries is more common in reality as most of the time we can't build them from source codes being limited by organization rules? Thanks!

**Comment by UebelAndre** [comment]
I'm happy to add examples but I don't understand what exactly you're trying to do if it's not what I [last described](https://github.com/bazelbuild/rules_foreign_cc/issues/621#issuecomment-827337020). If you could maybe send a mock workspace, I might be able to give you better advise 😅

**Comment by walkanywhere** [comment]
Hi Uebel, 

To be honest, I am compiling PostgreSQL with a specific version of Openssl. 

PostgreSQL is famous for its tough building. It requires to set CFLAGS which has dynamic values, for me, they are CFLAGS="-Dredacted='redacted' -Wl,-rpath, $$EXT_BUILD_DEPS$$/lib", with wrong quotes(' or "), $$EXT_BUILD_DEPS$$ won't be replaced or something wrong else happened.

I have "deps=[":openssl"]" which uses a library from cc_library. also "--with-libraries=$$EXT_BUILD_DEPS$$/lib" needs to be set, etc.

Thanks.
Walk
