### ISSUE TITLE
"make: *** No rule to make target `install'.  Stop."

### ISSUE THREAD

**Issue by walkanywhere** [bazelbuild/rules_foreign_cc#623]
Hi guys, 

Thanks for your work in advance! I used cmake_external( limited to the old version) to integrate a CMake-based thirdparty libraryt and Bazel got an error: 
```
make: *** No rule to make target `install'.  Stop.
```

In the temporary directory, I ran "make" without any issues though "make install" did fail as there is no installing at all. 

May I know how to disable this installing step in cmake_external? Thanks.

Regards

**Comment by UebelAndre** [comment]
what version of of the rules are you using?

**Comment by walkanywhere** [comment]
> what version of of the rules are you using?

I am using 594bf4d7731e606a705f3ad787dd0a70c5a28b30, thanks, Uebel! I will add install for it

**Comment by UebelAndre** [comment]
If you upgrade to at least `0.2.0` then there's a [targets](https://github.com/bazelbuild/rules_foreign_cc/tree/0.2.0/docs#cmake-targets) attribute you could use to specify what targets you want to build. An empty string `""` would be the same thing as all targets. Though, I thought cmake always generated an install target for you. Either way, the older version has some bad patterns built into it that make things more difficult to debug than they need to be. Try upgrading and let me know if that helps 😄

**Comment by walkanywhere** [comment]
> If you upgrade to at least `0.2.0` then there's a [targets](https://github.com/bazelbuild/rules_foreign_cc/tree/0.2.0/docs#cmake-targets) attribute you could use to specify what targets you want to build. An empty string `""` would be the same thing as all targets. Though, I thought cmake always generated an install target for you. Either way, the older version has some bad patterns built into it that make things more difficult to debug than they need to be. Try upgrading and let me know if that helps 😄

Thanks, buddy! The old one was used by a few teams so upgrading is not easy. You guys' work is fantastic!

**Comment by UebelAndre** [comment]
😄 I'm happy to help advise on any upgrade efforts. There should be deprecation messages in `0.2.0` which tell you what to do for upgrading. And I don't think we added a lot of breaking changes so the biggest blocker would maybe be the version of Bazel 😞 .
