### ISSUE TITLE
/XcodeDefault.xctoolchain/usr/bin/libtool: no files specified

### ISSUE THREAD

**Issue by CrazySnail-LLLL** [bazelbuild/rules_foreign_cc#624]
I want to use Bazel to compile the IOS version of Yoga, but there is an exception that I can't understand.

------------------------

Yoga/BUILD:35:21: Linking Yoga/YogaCoreFramework.apple_static_library-fl.a failed: (Exit 1): libtool failed: error executing command external/local_config_cc/libtool @bazel-out/ios-x86_64-min9.0-applebin_ios-ios_x86_64-fastbuild-ST-538b10a9975d/bin/TheirdParty/Yoga/YogaCoreFramework.apple_static_library-fl.a-2.params

**Comment by CrazySnail-LLLL** [comment]
[YogaTest.zip](https://github.com/bazelbuild/rules_foreign_cc/files/6395834/YogaTest.zip)
This is my project file .

**Comment by UebelAndre** [comment]
It doesn't look like you're using `rules_foreign_cc` in your example. Maybe this would be a better question for [rules_apple](https://github.com/bazelbuild/rules_apple) or [rules_swift](https://github.com/bazelbuild/rules_swift)? Or maybe I missed something...

**Comment by CrazySnail-LLLL** [comment]
> It doesn't look like you're using `rules_foreign_cc` in your example. Maybe this would be a better question for [rules_apple](https://github.com/bazelbuild/rules_apple) or [rules_swift](https://github.com/bazelbuild/rules_swift)? Or maybe I missed something...

Is there any other way I can compile C++ code into Framework

**Comment by UebelAndre** [comment]
I'd imagine you could use the standard [rules_cc](https://docs.bazel.build/versions/master/be/c-cpp.html) rules. But you'd definitely want to either check with those repositories or maybe ask around on the [slack channel](https://bazelbuild.slack.com/archives/CA31HN1T3)
