### ISSUE TITLE
configure_make non-explanatory error message

### ISSUE THREAD

**Issue by thymbahutymba** [bazelbuild/rules_foreign_cc#625]
Hi guys, I'm trying to build [ADOL-C](https://github.com/coin-or/ADOL-C) with bazel without success. I get an error but cannot debug it to see what I'm doing wrong.

`WORKSPACE`
```
http_archive(
    name = "adolc",
    url = "https://github.com/coin-or/ADOL-C/archive/refs/tags/releases/2.7.2.tar.gz",
    strip_prefix = "ADOL-C-releases-2.7.2",
    #sha256 = "",
    build_file = "@//:third_party/adolc.BUILD",
)
```
`adolc.BUILD`
```
package(default_visibility = ["//visibility:public"])
load("@rules_foreign_cc//foreign_cc:defs.bzl", "configure_make")

filegroup(
    name = "all_srcs",
    srcs = glob(["**"]),
    visibility = ["//visibility:public"],
)

configure_make(
    name = "adolc",
    lib_source = ":all_srcs",
    #args = [
    #    "-j8"
    #],
    install_prefix = "install",
    configure_in_place = True,
    autoreconf = True,
    autoreconf_options = ["-fi"],
    out_shared_libs = [
        "libadolc.so"
    ],
)
```

What I get is just this:
```
(08:58:03) ERROR: /root/bazel/540135163923dd7d5820f3ee4b306b32/external/adolc/BUILD.bazel:19:15: output 'external/adolc/adolc/lib/libadolc.so' was not created
(08:58:03) ERROR: /root/bazel/540135163923dd7d5820f3ee4b306b32/external/adolc/BUILD.bazel:19:15: not all outputs were created or valid
```
I tried to use the `--verbose_failures` flag as well as `-s` option. How can I solve this?

**Comment by UebelAndre** [comment]
In situations like these you probably want to use `--sandbox_debug` and inspect the build results. It seems like your artifacts aren't being installed in the correct locations. Can you explain why you added [install_prefix](https://github.com/bazelbuild/rules_foreign_cc/tree/98c88de5e0f57dd2a896dd595469ccd6bf97ceab/docs#configure_make-install_prefix)?

**Comment by tsarevfs** [comment]
Agree that documentation and output are not clear about what is a correct output location.
By default it assumes that make should create output files in install path: lib_name/out_lib_dir
It would be nice if docs for out_static_libs and out_shared_libs mention that paths must be relative to the install path.
