### ISSUE TITLE
Consuming the output of configure_make in cc_library

### ISSUE THREAD

**Issue by samirkut** [bazelbuild/rules_foreign_cc#626]
I am trying to build kerberos library and consume the output in a cc_library

the BUILD file roughly looks like this
```
configure_make(
  name = "krb5"
  configure_options = ["--without-libedit"],
  lib_source = "@krb5//:all",
  out_shared_libs = [ "libgssapi_krb5.so", "libkrb5.so"],
)
```

This works fine and I can see the libs being built correctly

When I try to consume this as dep in cc_library, I get into trouble

BUILD
```
cc_library(
  name = "auth-svc",
  srcs = [ ...],
  deps = ["@krb5//:krb5"],
)
```

building this throws the error
```
ld: cannot find -lkrb5
ld: cannot find -lgssapi_krb5

collect2: error: ld resturned 1 exit status
```
-----------
I have been stumped on what's happening here. Any ideas would be appreciated. Thanks.

**Comment by djmarcin** [comment]
I'm not sure the `out_shared_libs` are directly usable as deps in a cc_library. You may need to use `cc_import` first:
```
cc_import(name = "libkrb5", shared_library = ":libkrb5.so")
cc_import(name = "libgssapi_krb5", shared_library = ":libgssapi_krb5.so")
```
