### ISSUE TITLE
Support for `layering_check`

### ISSUE THREAD

**Issue by fmeum** [bazelbuild/rules_foreign_cc#630]
Enabling the Bazel feature `--features=layering_check` breaks any build with the `cmake` rule provided by `rules_foreign_cc` with this error message already in the analysis phase (this example builds `libjpeg_turbo`, but the particular target does not seem to matter):

```
ERROR: /home/runner/.cache/bazel/_bazel_runner/6bc610921f14939de4c55cf170d55a62/external/libjpeg_turbo/BUILD.bazel:22:6: in cmake rule @libjpeg_turbo//:libjpeg_turbo: 
Traceback (most recent call last):
	File "/home/runner/.cache/bazel/_bazel_runner/6bc610921f14939de4c55cf170d55a62/external/rules_foreign_cc/foreign_cc/cmake.bzl", line 58, column 33, in _cmake_impl
		return cc_external_rule_impl(ctx, attrs)
	File "/home/runner/.cache/bazel/_bazel_runner/6bc610921f14939de4c55cf170d55a62/external/rules_foreign_cc/foreign_cc/private/framework.bzl", line 371, column 38, in cc_external_rule_impl
		] + attrs.create_configure_script(ConfigureParameters(ctx = ctx, attrs = attrs, inputs = inputs)) + make_commands + postfix_script + [
	File "/home/runner/.cache/bazel/_bazel_runner/6bc610921f14939de4c55cf170d55a62/external/rules_foreign_cc/foreign_cc/cmake.bzl", line 72, column 27, in _create_configure_script
		flags = get_flags_info(ctx, "<TARGET>")
	File "/home/runner/.cache/bazel/_bazel_runner/6bc610921f14939de4c55cf170d55a62/external/rules_foreign_cc/foreign_cc/private/cc_toolchain_util.bzl", line 303, column 59, in get_flags_info
		cc = cc_common.get_memory_inefficient_command_line(
Error in get_memory_inefficient_command_line: Invalid toolchain configuration: Cannot find variable named 'module_name'.
```

It would be great if `cmake` would at least not fail in the analysis phase.

**Comment by jsharpe** [comment]
Thanks for the report @fmeum - can you see if #631 resolves this issue for you; I'm struggling to reproduce a toolchain locally that supports the `layering_check` feature to reproduce this.

**Comment by fmeum** [comment]
Thanks for the quick response!

The build:
* fails with 24ac3157f156d06509bab7bc7bdc97a2a41783a9, both with and without `layering_check`: all the output files (shared libraries) are "dangling symbolic link"s
* passes with https://github.com/CodeIntelligenceTesting/rules_foreign_cc/tree/layering_check_fix, which is a cherry-pick of 24ac3157f156d06509bab7bc7bdc97a2a41783a9 on top of the `0.2.0` release, both with and without `layering_check`.

So yes, it seems that the commit fixes the issue, but some other commit between it and `0.2.0` breaks my build or at least introduced a backwards incompatible change.

**Comment by UebelAndre** [comment]
Reopening to investigate what's broken from `0.2.0` to now.

**Comment by fmeum** [comment]
@UebelAndre The breaking commit is 46047ae15ccae935b756451ed09647201cf0ca4b. I don't have a minimal example, but https://github.com/CodeIntelligenceTesting/jazzer at f1c4bb507733710bbf292e474e173fcd0d6e8ff5 gives the following error if you update the `rules_foreign_cc` reference to 46047ae15ccae935b756451ed09647201cf0ca4b, but builds fine with v0.2.0 (`layering_check` is not enabled by default, so the fix in #631 is not relevant here):
```
~/git/jazzer (main)$ bazel build @libjpeg_turbo//...
...
INFO: Analyzed 8 targets (35 packages loaded, 7916 targets configured).
INFO: Found 8 targets...
ERROR: /home/fhenneke/.cache/bazel/_bazel_fhenneke/4b646345d108d26eb716dacf5ef06e11/external/libjpeg_turbo/BUILD.bazel:23:6: output 'external/libjpeg_turbo/libjpeg_turbo/lib/libjpeg.so' is a dangling symbolic link
ERROR: /home/fhenneke/.cache/bazel/_bazel_fhenneke/4b646345d108d26eb716dacf5ef06e11/external/libjpeg_turbo/BUILD.bazel:23:6: output 'external/libjpeg_turbo/libjpeg_turbo/lib/libturbojpeg.so' is a dangling symbolic link
ERROR: /home/fhenneke/.cache/bazel/_bazel_fhenneke/4b646345d108d26eb716dacf5ef06e11/external/libjpeg_turbo/BUILD.bazel:23:6: CcCmakeMakeRule external/libjpeg_turbo/libjpeg_turbo/include failed: not all outputs were created or valid
INFO: Elapsed time: 145.188s, Critical Path: 133.11s
INFO: 5 processes: 3 internal, 2 linux-sandbox.
FAILED: Build did NOT complete successfully
```

I'm not good with CMake, so this may be very well due to a mistake on my side.

**Comment by UebelAndre** [comment]
@fmeum Hey, sorry for the deplay here. Do you know if https://github.com/bazelbuild/rules_foreign_cc/pull/656 would fix the dangling symlinks you're running into?

**Comment by fmeum** [comment]
Unfortunately not. With cb7b094014f04292e8e4db29616f6f6984632fc7, I still get the same error on the target linked above:
```
~/git/jazzer (main *)$ bazel build @libjpeg_turbo//:libjpeg_turbo
INFO: Analyzed target @libjpeg_turbo//:libjpeg_turbo (31 packages loaded, 7746 targets configured).
INFO: Found 1 target...
ERROR: /home/fabian/.cache/bazel/_bazel_fabian/3821989c4a000f3a0c8be3e30c90c4f7/external/libjpeg_turbo/BUILD.bazel:23:6: output 'external/libjpeg_turbo/libjpeg_turbo/lib/libjpeg.so' is a dangling symbolic link
ERROR: /home/fabian/.cache/bazel/_bazel_fabian/3821989c4a000f3a0c8be3e30c90c4f7/external/libjpeg_turbo/BUILD.bazel:23:6: output 'external/libjpeg_turbo/libjpeg_turbo/lib/libturbojpeg.so' is a dangling symbolic link
ERROR: /home/fabian/.cache/bazel/_bazel_fabian/3821989c4a000f3a0c8be3e30c90c4f7/external/libjpeg_turbo/BUILD.bazel:23:6: CcCmakeMakeRule external/libjpeg_turbo/libjpeg_turbo/include failed: not all outputs were created or valid
Target @libjpeg_turbo//:libjpeg_turbo failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 121.108s, Critical Path: 120.16s
INFO: 11 processes: 7 internal, 4 linux-sandbox.
FAILED: Build did NOT complete successfully
```

Can I help you debug this? You should be able to reproduce it locally as described above.

**Comment by UebelAndre** [comment]
I tried running the steps above but ran into some issues. Maybe I don't have my machine setup properly for the java rules? I've never used them before 😅 but I'd like to resolve this issue ASAP. If you were able to break out a minimal repro for this I could iterate on that and get to the bottom of this.

**Comment by fmeum** [comment]
The following example should not require Java build tools:

```bazel
$ touch BUILD.bazel
$ cat WORKSPACE.bazel
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

LAST_WORKING_COMMIT = "0a0f8fd6db8cadc95d968f984729edccce77f4d5"

FIRST_BROKEN_COMMIT = "46047ae15ccae935b756451ed09647201cf0ca4b"

STILL_BROKEN_COMMIT = "cb7b094014f04292e8e4db29616f6f6984632fc7"

FOREIGN_CC_COMMIT = # Choose one of the commits above

http_archive(
    name = "rules_foreign_cc",
    strip_prefix = "rules_foreign_cc-%s" % FOREIGN_CC_COMMIT,
    url = "https://github.com/bazelbuild/rules_foreign_cc/archive/%s.tar.gz" % FOREIGN_CC_COMMIT,
)

load("@rules_foreign_cc//foreign_cc:repositories.bzl", "rules_foreign_cc_dependencies")

rules_foreign_cc_dependencies()

http_archive(
    name = "libjpeg_turbo",
    build_file = "//:libjpeg_turbo.BUILD",
    sha256 = "6a965adb02ad898b2ae48214244618fe342baea79db97157fdc70d8844ac6f09",
    strip_prefix = "libjpeg-turbo-2.0.90",
    url = "https://github.com/libjpeg-turbo/libjpeg-turbo/archive/2.0.90.tar.gz",
)

$ cat libjpeg_turbo.BUILD
load("@rules_foreign_cc//foreign_cc:defs.bzl", "cmake")

filegroup(
    name = "all_files",
    srcs = glob(["**"]),
)

cmake(
    name = "libjpeg_turbo",
    cache_entries = {
        "CMAKE_BUILD_TYPE": "Release",
        "WITH_JAVA": "0",
    },
    lib_source = ":all_files",
    out_shared_libs = [
        "libjpeg.so",
    ],
)

$ bazel build @libjpeg_turbo//:libjpeg_turbo
```

**Comment by UebelAndre** [comment]
So, I think the issue here is that the file `libjpeg.so` is really a symlink so the failure is expected. CMake is installing the library to the correct location but `libjpeg.0.2.0.so` is the real file and `libjpeg.0.so` and `libjpeg.so` are symlinks to that file.
```python
load("@rules_foreign_cc//foreign_cc:defs.bzl", "cmake")

filegroup(
    name = "all_files",
    srcs = glob(["**"]),
)

cmake(
    name = "libjpeg_turbo",
    cache_entries = {
        "CMAKE_BUILD_TYPE": "Release",
        "WITH_JAVA": "0",
    },
    lib_source = ":all_files",
    out_shared_libs = select({
        "@platforms//os:macos": [
            "libturbojpeg.0.2.0.dylib",
            "libturbojpeg.0.dylib",
            "libturbojpeg.dylib",
        ],
        "@platforms//os:linux": [
            "libjpeg.0.2.0.so",
            "libjpeg.0.so",
            "libjpeg.so",
        ],
        "@platforms//os:windows": [
            "libjpeg.0.2.0.dll",
            "libjpeg.0.dll",
            "libjpeg.dll",
        ],
    }),
)
```

I was able to successfully build with that BUILD file.

Perhaps it'd be a good idea to add a new attribute `preserve_symlinks` to the core framework to ensure any files specified in the `out_*` attributes are explicitly resolved. But at least we now know what's going on. Give that BUILD file a shot?

**Comment by UebelAndre** [comment]
I took a stab at adding a `preserve_symlinks` attribute and couldn't find a good solution. It's *super* annoying that `readlink` on macos doesn't have a `-f` option to follow all symlinks. If anyone has a suggestion there I'd love to hear it but I'll be trying to find a solution there so when users specify an output directory that they don't get stuck with symlinks as the files they're looking to consume as outputs to this action.

**Comment by UebelAndre** [comment]
@fmeum can you check to see if https://github.com/bazelbuild/rules_foreign_cc/pull/656 fixed the issue for you?

**Comment by fmeum** [comment]
@UebelAndre Sorry for the late response. While the BUILD file you posted earlier produced the same error (maybe the filenames for Linux were off?), I can confirm that #656 fixes the issues without any changes required on my part. Thanks, will now update to master.

**Comment by UebelAndre** [comment]
I *did* only test it on macos, so definitely possible I messed up those select blocks. But glad to hear this issue is resolved for you! 😄
