### ISSUE TITLE
Provide a public interface for get_flags_info()

### ISSUE THREAD

**Issue by attilaolah** [bazelbuild/rules_foreign_cc#651]
Since the recent reshuffle of `.bzl` files (which is very neat btw), some functions are marked private now. Namely, `get_flags_info()`, which I've been used before and would like to continue using.

My use case looks something like this:

```
     # Append C/C++ compiler flags:                                                                                      
     flags = get_flags_info(ctx)                                                                                         
     args.add_all(flags.cc)                                                                                              
     args.add_all([                                                                                                      
         flag                                                                                                            
         for flag in flags.cxx_linker_executable                                                                         
         if flag not in WASM_LD_UNSUPPORTED_FLAGS                                                                        
     ])                                                                                                                  
```

Would it be possible to introduce some sort of CC utils Starlark module asd shove it there? (I can also cargo-cult the function, but it would be nice to keep using it from your library.)

**Comment by UebelAndre** [comment]
Can you expand a bit on the use case? I'd like to know of there's something that can be done to solve for the use case by making the rules more intelligent or expressive (yet still maintaining potential hermetic builds).

**Comment by attilaolah** [comment]
Actually, this might not be necessary in the long run. I use the function here:

https://github.com/attilaolah/wasm/blob/main/tools/wasm_library.bzl#L89-L96

But I think I should probably start using the toolchain provided by the emsdk repo, and then just use `cc_library()` rules instead of my home-grown `wasm_library()`.

For now I'll just use the function from the `private` package as-is, and I'll try to improve things at some point.
