### ISSUE TITLE
Docs are out of date

### ISSUE THREAD

**Issue by aapeliv** [bazelbuild/rules_foreign_cc#664]
Docs at https://docs.aspect.dev/rules_foreign_cc/ seem to be out of date and some things seem to have changed between 0.2.0 and 0.3.0.

**Comment by UebelAndre** [comment]
Thanks for the heads up! I'll see if I can get this resolved soon.

**Comment by UebelAndre** [comment]
The docs are now updated.

Note that the setup instructions are unfortunately outdated in this release (referencing `0.2.0`) but we'll be updating the release process to ensure that doesn't happen again.

Thanks again!

**Comment by aapeliv** [comment]
@UebelAndre: now the index page is working <https://docs.aspect.dev/bazelbuild/rules_foreign_cc/0.3.0/docs/> but all links are leading to 404s!

**Comment by UebelAndre** [comment]
Ah yeah, that will be fixed in the coming days. It's an issue with the site itself. For now, the links in the site are the only way to navigate from page to page (not the links rendered in the documentation). 😞

**Comment by aapeliv** [comment]
Alright, thanks!

**Comment by UebelAndre** [comment]
All I did was phone a friend 😅 . Alex Eagle deserves all the credit! Thanks again!
