### ISSUE TITLE
Do tool paths that contain the string "build" get rewritten with "$EXT_BUILD_ROOT"

### ISSUE THREAD

**Issue by jpeach** [bazelbuild/rules_foreign_cc#665]
I have a directory called `envoy-build` that has some script wrappers for the compilers that I want to use. It seems like the foreign rules rewrite the `CC` and `CXX` paths in a strange way that breaks the build (cmake can't find the compiler)"

```
CC="/home/jpeach/src/envoy-$EXT_BUILD_ROOT/build/bazel/llamacc" CXX="/home/jpeach/src/envoy-$EXT_BUILD_ROOT/build/bazel/llamacc" CFLAGS="-U_FORTIFY_SOURCE -fstack-protector -Wall -fno-omit-frame-pointer -g0 -O2 -D_FORTIFY_SOURCE=1 -DNDEBUG -ffunction-sections -fdata-sections -Wno-builtin-macro-redefined -D__DATE__=\"redacted\" -D__TIMESTAMP__=\"redacted\" -D__TIME__=\"redacted\"" CXXFLAGS="-U_FORTIFY_SOURCE -fstack-protector -Wall -fno-omit-frame-pointer -g0 -O2 -D_FORTIFY_SOURCE=1 -DNDEBUG -ffunction-sections -fdata-sections -std=c++0x -Wno-builtin-macro-redefined -D__DATE__=\"redacted\" -D__TIMESTAMP__=\"redacted\" -D__TIME__=\"redacted\"" ASMFLAGS="-U_FORTIFY_SOURCE -fstack-protector -Wall -fno-omit-frame-pointer -g0 -O2 -D_FORTIFY_SOURCE=1 -DNDEBUG -ffunction-sections -fdata-sections -Wno-builtin-macro-redefined -D__DATE__=\"redacted\" -D__TIMESTAMP__=\"redacted\" -D__TIME__=\"redacted\"" cmake -DCMAKE_AR="/usr/bin/ar" -DCMAKE_SHARED_LINKER_FLAGS="-shared -fuse-ld=gold -B/home/jpeach/src/envoy-$EXT_BUILD_ROOT/build/bazel -lm -l:libstdc++.a" -DCMAKE_EXE_LINKER_FLAGS="-fuse-ld=gold -B/home/jpeach/src/envoy-$EXT_BUILD_ROOT/build/bazel -lm -l:libstdc++.a" -DCMAKE_CXX_COMPILER_FORCED="on" -DCMAKE_C_COMPILER_FORCED="on" -DSKIP_BUILD_EXAMPLES="on" -DBUILD_SHARED_LIBS="off" -DZLIB_COMPAT="on" -DZLIB_ENABLE_TESTS="off" -DWITH_OPTIM="on" -DWITH_SSE4="off" -DWITH_NEW_STRATEGIES="off" -DUNALIGNED_OK="off" -DCMAKE_BUILD_TYPE="Bazel" -DCMAKE_PREFIX_PATH="$EXT_BUILD_DEPS" -DCMAKE_INSTALL_PREFIX="$INSTALL_PREFIX" -DCMAKE_RANLIB="" -GNinja $EXT_BUILD_ROOT/external/net_zlib
```

Full build log: https://gist.github.com/jpeach/df375048ff7feedd706e79d1d1f0d713

**Comment by UebelAndre** [comment]
Hi! Sorry for the delay, can you share the `BUILD` file as well?

**Comment by jpeach** [comment]
> Hi! Sorry for the delay, can you share the `BUILD` file as well?

I'm building envoy, so it's a fairly complex Bazel build. I have my own workspace [here](https://github.com/jpeach/envoy-build), and if I set CC and CXX to a path that contains the string "build", this happens.

**Comment by jsharpe** [comment]
I've just stumbled across the code that is causing this.
This looks like its due to the logic in `absolutize_path_in_str` in `cc_toolchain_util.bzl`. Because the `WORKSPACE` is called `build` then it is used as part of the path to replace when generating the absolute path.

**Comment by jpeach** [comment]
> I've just stumbled across the code that is causing this.
> This looks like its due to the logic in [absolutize_path_in_str](https://github.com/bazelbuild/rules_foreign_cc/blob/c95d769e30395ecea0f1ef801fa0d159cde41531/foreign_cc/private/cc_toolchain_util.bzl#L390-L419) in `cc_toolchain_util.bzl`. Because the `WORKSPACE` is called `build` then it is used as part of the path to replace when generating the absolute path.

Wow, that's a great find!
