### ISSUE TITLE
configure_make() seems to ignore the targets attribute

### ISSUE THREAD

**Issue by attilaolah** [bazelbuild/rules_foreign_cc#670]
It looks like passing `targets = […]` to `configure_make()` has no effect.

I think the `make_commands` arg should be removed from `configure_make`, similarly how it was removed from `make()` and `cmake()`, and replaced with `targets`. Then, if anyone needs a "special" make command, they could still pass in an empty list and have other commands executed in the `postfix_script`, which is more aligned with other rules in this repo.

**Comment by UebelAndre** [comment]
Thanks for opening the issue! I'll have this fixed soon
