### ISSUE TITLE
always use darwin_arm64 when remote_executor,  It should use ubuntu

### ISSUE THREAD

**Issue by kekxv** [bazelbuild/rules_foreign_cc#673]
.bazelrc
```.bazelrc
build                 --remote_executor=grpc://localhost:8980
build                 --remote_cache=grpc://localhost:8980
```

log
```log
make[1]: Entering directory '/tmp/worker/default_memory_instance/operations/6793b760-65b3-4396-ab8a-7c64db23faf0/bazel-out/darwin_arm64-opt-exec-2B5CBBC6/bin/external/rules_foreign_cc/toolchains/make.build_tmpdir/doc'
```

**always use `darwin_arm64` when remote_executor,**

**It should use ubuntu**

**Comment by UebelAndre** [comment]
I'm unfortunately not super familiar with remote execution. What needs to be done to resolve this issue? Would this have to do with config transitions?

**Comment by kekxv** [comment]
> I'm unfortunately not super familiar with remote execution. What needs to be done to resolve this issue? Would this have to do with config transitions?

I try to get a demo for you

**Comment by jsharpe** [comment]
I suspect this is a toolchain or platforms configuration error. You likely need to check what toolchain is setup for your `host` configuration you probably need to point it at a toolchain that is valid for the remote platform.
