### ISSUE TITLE
Flaky builds in CI

### ISSUE THREAD

**Issue by UebelAndre** [bazelbuild/rules_foreign_cc#684]
I've noticed in a few builds now that something would fail only to succeed again with either no change to the failed build/test

https://buildkite.com/bazel/rules-foreign-cc/builds/2884 failed only to have https://github.com/bazelbuild/rules_foreign_cc/pull/622#discussion_r652779479 fix it in https://buildkite.com/bazel/rules-foreign-cc/builds/2887

I'm not sure how best to investigate this problem but this issue will track that adventure.

cc @jsharpe for visibility.

**Comment by UebelAndre** [comment]
@philwo sorry to ping but is there any reason to believe [--spawn_strategy](https://docs.bazel.build/versions/main/command-line-reference.html#flag--spawn_strategy) set to `standalone` might run into issues in Bazel CI? We've been seeing some odd behavior ever since we enabled it. It could very likely be an issue somewhere within these rules but wanted to cross this off the list if possible.

**Comment by philwo** [comment]
Hi,

do you see this flakyness only ever on one specific platform (e.g. only on macOS) or is it random?

It's easier to hit accidental flakyness or race conditions in rules or tools when using `--spawn_strategy=standalone` than when using sandboxed execution, although that wouldn't be specific to Bazel CI.

**Comment by UebelAndre** [comment]
> do you see this flakyness only ever on one specific platform (e.g. only on macOS) or is it random?

To my recollection it's exclusively macOS builds that experience flakiness.

**Comment by philwo** [comment]
Mhm. In the original log, the output of the failing step was not uploaded ("stdout (/private/var/tmp/_bazel_buildkite/3caab95e48b31e8eefc2ef3fc495033d/execroot/rules_foreign_cc_examples/bazel-out/_tmp/actions/stdout-35) exceeds maximum size of --experimental_ui_max_stdouterr_bytes=1048576 bytes; skipping") - do we have a failing job where we have the log? I wonder what's causing it to fail.

**Comment by UebelAndre** [comment]
I think https://github.com/bazelbuild/rules_foreign_cc/pull/687 might have been the source of the issue here. There are some other builds I can go dig up but we were doing something different on MacOS so I'll see if things are still flaky after this change

**Comment by UebelAndre** [comment]
I don't think we've seen any more flaky builds so I'll close this for now 😄
