### ISSUE TITLE
not all outputs were created or valid

### ISSUE THREAD

**Issue by bbarnes52** [bazelbuild/rules_foreign_cc#69]
```
Writing /tmp/tmp.MbivBdIFdS/catkin/lib/python2.7/dist-packages/catkin-0.7.14.egg-info
/home/brian/.cache/bazel/_bazel_brian/19fc196dfacab0a373352db9ae53e0f1/sandbox/linux-sandbox/1/execroot/__main__
ERROR: /home/brian/git/cloud/third_party/cmake/catkin/BUILD:7:1: output 'third_party/cmake/catkin/catkin/lib/catkin.a' was not created
ERROR: /home/brian/git/cloud/third_party/cmake/catkin/BUILD:7:1: not all outputs were created or valid
```

building catkin (https://github.com/ros/catkin/blob/kinetic-devel/CMakeLists.txt)

this is a question not an issue, not sure if there is a better forum to post. what are the cmake_external arguments I might need to set to resolve this issue?

thank you for your assistance

**Comment by irengrig** [comment]
Hi, there is several arguments for specifying the names of the expected output libraries.
For static libraries, you should specify `static_libraries = ["real-name-of-catkin.a", "some-other-name.a"]`.
You are welcome :)

**Comment by bbarnes52** [comment]
So it appears that this rule should actually not generate any libraries (running `cmake` followed by `make && make install` yields no .a or .so files). Is there anything else that could cause this error message?

**Comment by bbarnes52** [comment]
this is WAI, can just set `headers_only = True`

**Comment by irengrig** [comment]
Yep, you can either specify the list of names or headers_only. If you do not specify anything, the rule assumes it is the default name = lib_name.a (or name.a, if lib_name is not specified)
