### ISSUE TITLE
Bazel build fails on MacOS starting from version 4.0.0.

### ISSUE THREAD

**Issue by junniest** [bazelbuild/rules_foreign_cc#699]
### Description of the problem / feature request:

Bazel build fails on MacOS starting from version 4.0.0.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

The bug can be reproduced on https://github.com/yarcat/bazel-experiments by running:
`bazel build --sandbox_debug :all `
on MacOS BigSur with any version of Bazel >= 4.0.0.

```
The build fails when trying to link the compiled library, as the "rpath" value is not replaced properly:
[ 41%] Linking CXX shared library libbpp-core.dylib
/private/var/tmp/_bazel_pece/1aaea46e77017e4bf999057d24a482e7/sandbox/darwin-sandbox/1/execroot/bpp_yarcat/external/local_config_cc/cc_wrapper.sh: line 54: rpath/libbpp-core.4.dylib: No such file or directory
```

### What operating system are you running Bazel on?

MacOS Big Sur 11.4

### What's the output of `bazel info release`?

Same thing happens for the following versions:
release 5.0.0-pre.20210604.6
release 4.1.0
release 4.0.0

###  Have you found anything relevant by searching the web?

Unfortunately not.

### Any other information, logs, or outputs that you want to share?

The bug appears in version 4.0.0 and higher, the exact same configuration compiles perfectly fine with bazel 3.7.1.

The build log from bazel 5.0.0-pre:
[bazelbuild.log](https://github.com/bazelbuild/bazel/files/6715997/bazelbuild.log)

**Comment by UebelAndre** [comment]
Hi! Sorry about the issue you're running into, what was the last working version of this code?

**Comment by UebelAndre** [comment]
Odd, I'm able to build without an issue
```
bpp % bazel build --sandbox_debug :all
```
```
INFO: Invocation ID: 72bbb2cf-54ab-49c3-a4b3-5f63b52c3aae
DEBUG: Rule 'rules_foreign_cc' indicated that a canonical reproducible form can be obtained by modifying arguments sha256 = "b263601a377dc2e7b255670928c98dcd21ed8fcc69a6cfe7be8b550ef7f9de07"
DEBUG: Repository rules_foreign_cc instantiated at:
  /Users/user/code/bazel-experiments/bpp/WORKSPACE:11:13: in <toplevel>
Repository rule http_archive defined at:
  /private/var/tmp/_bazel_user/145c4293989811676682bb532b27c51b/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
DEBUG: Rule 'bpp_core' indicated that a canonical reproducible form can be obtained by modifying arguments sha256 = "e98db6695c36c63eeaf42da04776c81eb0f8bf3247b681ee0bfbbd691944f4b6"
DEBUG: Repository bpp_core instantiated at:
  /Users/user/code/bazel-experiments/bpp/WORKSPACE:17:13: in <toplevel>
Repository rule http_archive defined at:
  /private/var/tmp/_bazel_user/145c4293989811676682bb532b27c51b/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
DEBUG: Rule 'bpp_seq' indicated that a canonical reproducible form can be obtained by modifying arguments sha256 = "74389a51ad25a787ee872fb2f24f7eac2023cfe72ec6168400dee912822df9ae"
DEBUG: Repository bpp_seq instantiated at:
  /Users/user/code/bazel-experiments/bpp/WORKSPACE:24:13: in <toplevel>
Repository rule http_archive defined at:
  /private/var/tmp/_bazel_user/145c4293989811676682bb532b27c51b/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
INFO: Analyzed 2 targets (0 packages loaded, 0 targets configured).
INFO: Found 2 targets...
INFO: Elapsed time: 0.480s, Critical Path: 0.08s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action
```
```
bazel version
```
Bazelisk version: development
Build label: 4.1.0
Build target: bazel-out/darwin-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Fri May 21 11:16:55 2021 (1621595815)
Build timestamp: 1621595815
Build timestamp as int: 1621595815
```

Perhaps there's something in a `.bazelrc` file triggering different behavior?

**Comment by junniest** [comment]
Are you building on MacOS or on a system that makes more sense? :D The same stuff actually builds perfectly fine on Linux, it's just MaxOS that is being difficult.

I am on MacOS 11.4 and I don't have a bazelrc file at all.

If I run the same command as you did, this is what I get:

`bpp git:(master) ✗ bazel build --sandbox_debug :all
Starting local Bazel server and connecting to it...
INFO: Analyzed 2 targets (25 packages loaded, 7650 targets configured).
INFO: Found 2 targets...
ERROR: /Users/pece/Repositories/bazel-experiments/bpp/BUILD:3:6: CcCmakeMakeRule libbpp-core/include failed: (Exit 2): sandbox-exec failed: error executing command 
  (cd /private/var/tmp/_bazel_pece/1aaea46e77017e4bf999057d24a482e7/sandbox/darwin-sandbox/1/execroot/bpp_yarcat && \
  exec env - \
    TMPDIR=/var/folders/r0/k06ykh3d5xz3tpx7cys09yld0280vt/T/ \
  /usr/bin/sandbox-exec -f /private/var/tmp/_bazel_pece/1aaea46e77017e4bf999057d24a482e7/sandbox/darwin-sandbox/1/sandbox.sb /var/tmp/_bazel_pece/install/d07238c5957d0addf241b6be07f3c14b/process-wrapper '--timeout=0' '--kill_delay=15' /bin/bash -c bazel-out/darwin-fastbuild/bin/libbpp-core_foreign_cc/wrapper_build_script.sh)
rules_foreign_cc: Build failed!
rules_foreign_cc: Keeping temp build directory and dependencies directory for debug.
rules_foreign_cc: Please note that the directories inside a sandbox are still cleaned unless you specify --sandbox_debug Bazel command line flag.
rules_foreign_cc: Printing build logs:
_____ BEGIN BUILD LOGS _____

Bazel external C/C++ Rules. Building library libbpp-core

Environment:______________
TMPDIR=/var/folders/r0/k06ykh3d5xz3tpx7cys09yld0280vt/T/
BUILD_WRAPPER_SCRIPT=bazel-out/darwin-fastbuild/bin/libbpp-core_foreign_cc/wrapper_build_script.sh
EXT_BUILD_ROOT=/private/var/tmp/_bazel_pece/1aaea46e77017e4bf999057d24a482e7/sandbox/darwin-sandbox/1/execroot/bpp_yarcat
INSTALLDIR=/private/var/tmp/_bazel_pece/1aaea46e77017e4bf999057d24a482e7/sandbox/darwin-sandbox/1/execroot/bpp_yarcat/bazel-out/darwin-fastbuild/bin/libbpp-core
__CF_USER_TEXT_ENCODING=0x4024037A:0x0:0x2
PATH=/private/var/tmp/_bazel_pece/1aaea46e77017e4bf999057d24a482e7/sandbox/darwin-sandbox/1/execroot/bpp_yarcat:/usr/gnu/bin:/usr/local/bin:/bin:/usr/bin:.
BUILD_TMPDIR=/private/var/tmp/_bazel_pece/1aaea46e77017e4bf999057d24a482e7/sandbox/darwin-sandbox/1/execroot/bpp_yarcat/bazel-out/darwin-fastbuild/bin/libbpp-core.build_tmpdir
PWD=/private/var/tmp/_bazel_pece/1aaea46e77017e4bf999057d24a482e7/sandbox/darwin-sandbox/1/execroot/bpp_yarcat
EXT_BUILD_DEPS=/private/var/tmp/_bazel_pece/1aaea46e77017e4bf999057d24a482e7/sandbox/darwin-sandbox/1/execroot/bpp_yarcat/bazel-out/darwin-fastbuild/bin/libbpp-core.ext_build_deps
SHLVL=3
BUILD_LOG=bazel-out/darwin-fastbuild/bin/libbpp-core_foreign_cc/CMake.log
BUILD_SCRIPT=bazel-out/darwin-fastbuild/bin/libbpp-core_foreign_cc/build_script.sh
_=/usr/bin/env
__________________________
+ /private/var/tmp/_bazel_pece/1aaea46e77017e4bf999057d24a482e7/sandbox/darwin-sandbox/1/execroot/bpp_yarcat/external/cmake-3.20.2-macos-universal/bin/cmake -DCMAKE_TOOLCHAIN_FILE=crosstool_bazel.cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/private/var/tmp/_bazel_pece/1aaea46e77017e4bf999057d24a482e7/sandbox/darwin-sandbox/1/execroot/bpp_yarcat/bazel-out/darwin-fastbuild/bin/libbpp-core -DCMAKE_PREFIX_PATH=/private/var/tmp/_bazel_pece/1aaea46e77017e4bf999057d24a482e7/sandbox/darwin-sandbox/1/execroot/bpp_yarcat/bazel-out/darwin-fastbuild/bin/libbpp-core.ext_build_deps -DCMAKE_RANLIB= -DCMAKE_MAKE_PROGRAM=/private/var/tmp/_bazel_pece/1aaea46e77017e4bf999057d24a482e7/sandbox/darwin-sandbox/1/execroot/bpp_yarcat/bazel-out/darwin-opt-exec-2B5CBBC6/bin/external/rules_foreign_cc/toolchains/make/bin/make -G 'Unix Makefiles' /private/var/tmp/_bazel_pece/1aaea46e77017e4bf999057d24a482e7/sandbox/darwin-sandbox/1/execroot/bpp_yarcat/external/bpp_core
CMake Deprecation Warning at CMakeLists.txt:8 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


sh: /bin/ps: Operation not permitted
-- The CXX compiler identification is AppleClang 12.0.5.12050022
-- Detecting CXX compiler ABI info
sh: /bin/ps: Operation not permitted
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /private/var/tmp/_bazel_pece/1aaea46e77017e4bf999057d24a482e7/sandbox/darwin-sandbox/1/execroot/bpp_yarcat/external/local_config_cc/cc_wrapper.sh - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE) 
-- Configuring done
-- Generating done
-- Build files have been written to: /private/var/tmp/_bazel_pece/1aaea46e77017e4bf999057d24a482e7/sandbox/darwin-sandbox/1/execroot/bpp_yarcat/bazel-out/darwin-fastbuild/bin/libbpp-core.build_tmpdir
+ /private/var/tmp/_bazel_pece/1aaea46e77017e4bf999057d24a482e7/sandbox/darwin-sandbox/1/execroot/bpp_yarcat/external/cmake-3.20.2-macos-universal/bin/cmake --build . --config Release
[  0%] Building CXX object src/CMakeFiles/bpp-core-shared.dir/Bpp/App/ApplicationTools.cpp.o
[  0%] Building CXX object src/CMakeFiles/bpp-core-shared.dir/Bpp/App/BppApplication.cpp.o
[  1%] Building CXX object src/CMakeFiles/bpp-core-shared.dir/Bpp/App/NumCalcApplicationTools.cpp.o
[  1%] Building CXX object src/CMakeFiles/bpp-core-shared.dir/Bpp/BppString.cpp.o
[  2%] Building CXX object src/CMakeFiles/bpp-core-shared.dir/Bpp/Exceptions.cpp.o
[  2%] Building CXX object src/CMakeFiles/bpp-core-shared.dir/Bpp/Graph/GlobalGraph.cpp.o
[  3%] Building CXX object src/CMakeFiles/bpp-core-shared.dir/Bpp/Graphics/ColorTools.cpp.o
[  3%] Building CXX object src/CMakeFiles/bpp-core-shared.dir/Bpp/Graphics/Fig/XFigGraphicDevice.cpp.o
[  4%] Building CXX object src/CMakeFiles/bpp-core-shared.dir/Bpp/Graphics/Fig/XFigLaTeXFontManager.cpp.o
[  4%] Building CXX object src/CMakeFiles/bpp-core-shared.dir/Bpp/Graphics/Fig/XFigPostscriptFontManager.cpp.o
[  5%] Building CXX object src/CMakeFiles/bpp-core-shared.dir/Bpp/Graphics/Font/Font.cpp.o
[  5%] Building CXX object src/CMakeFiles/bpp-core-shared.dir/Bpp/Graphics/GraphicDevice.cpp.o
[  6%] Building CXX object src/CMakeFiles/bpp-core-shared.dir/Bpp/Graphics/Latex/DvipsColorSet.cpp.o
[  6%] Building CXX object src/CMakeFiles/bpp-core-shared.dir/Bpp/Graphics/Latex/PgfGraphicDevice.cpp.o
[  7%] Building CXX object src/CMakeFiles/bpp-core-shared.dir/Bpp/Graphics/Molscript/MolscriptColorSet.cpp.o
[  7%] Building CXX object src/CMakeFiles/bpp-core-shared.dir/Bpp/Graphics/R/RColorSet.cpp.o
[  7%] Building CXX object src/CMakeFiles/bpp-core-shared.dir/Bpp/Graphics/Svg/SvgGraphicDevice.cpp.o
[  8%] Building CXX object src/CMakeFiles/bpp-core-shared.dir/Bpp/Io/BppODiscreteDistributionFormat.cpp.o
[  8%] Building CXX object src/CMakeFiles/bpp-core-shared.dir/Bpp/Io/BppOParametrizableFormat.cpp.o
[  9%] Building CXX object src/CMakeFiles/bpp-core-shared.dir/Bpp/Io/FileTools.cpp.o
[  9%] Building CXX object src/CMakeFiles/bpp-core-shared.dir/Bpp/Io/IoDiscreteDistributionFactory.cpp.o
[ 10%] Building CXX object src/CMakeFiles/bpp-core-shared.dir/Bpp/Numeric/AbstractParameterAliasable.cpp.o
[ 10%] Building CXX object src/CMakeFiles/bpp-core-shared.dir/Bpp/Numeric/AbstractParametrizable.cpp.o
[ 11%] Building CXX object src/CMakeFiles/bpp-core-shared.dir/Bpp/Numeric/AdaptiveKernelDensityEstimation.cpp.o
[ 11%] Building CXX object src/CMakeFiles/bpp-core-shared.dir/Bpp/Numeric/AutoParameter.cpp.o
[ 12%] Building CXX object src/CMakeFiles/bpp-core-shared.dir/Bpp/Numeric/DataTable.cpp.o
[ 12%] Building CXX object src/CMakeFiles/bpp-core-shared.dir/Bpp/Numeric/Function/AbstractOptimizer.cpp.o
[ 13%] Building CXX object src/CMakeFiles/bpp-core-shared.dir/Bpp/Numeric/Function/BfgsMultiDimensions.cpp.o
[ 13%] Building CXX object src/CMakeFiles/bpp-core-shared.dir/Bpp/Numeric/Function/BrentOneDimension.cpp.o
[ 14%] Building CXX object src/CMakeFiles/bpp-core-shared.dir/Bpp/Numeric/Function/ConjugateGradientMultiDimensions.cpp.o
[ 14%] Building CXX object src/CMakeFiles/bpp-core-shared.dir/Bpp/Numeric/Function/DirectionFunction.cpp.o
[ 14%] Building CXX object src/CMakeFiles/bpp-core-shared.dir/Bpp/Numeric/Function/DownhillSimplexMethod.cpp.o
[ 15%] Building CXX object src/CMakeFiles/bpp-core-shared.dir/Bpp/Numeric/Function/FivePointsNumericalDerivative.cpp.o
[ 15%] Building CXX object src/CMakeFiles/bpp-core-shared.dir/Bpp/Numeric/Function/FunctionTools.cpp.o
[ 16%] Building CXX object src/CMakeFiles/bpp-core-shared.dir/Bpp/Numeric/Function/GoldenSectionSearch.cpp.o
[ 16%] Building CXX object src/CMakeFiles/bpp-core-shared.dir/Bpp/Numeric/Function/MetaOptimizer.cpp.o
[ 17%] Building CXX object src/CMakeFiles/bpp-core-shared.dir/Bpp/Numeric/Function/NewtonBacktrackOneDimension.cpp.o
[ 17%] Building CXX object src/CMakeFiles/bpp-core-shared.dir/Bpp/Numeric/Function/NewtonOneDimension.cpp.o
[ 18%] Building CXX object src/CMakeFiles/bpp-core-shared.dir/Bpp/Numeric/Function/OneDimensionOptimizationTools.cpp.o
[ 18%] Building CXX object src/CMakeFiles/bpp-core-shared.dir/Bpp/Numeric/Function/Operators/ComputationTree.cpp.o
[ 19%] Building CXX object src/CMakeFiles/bpp-core-shared.dir/Bpp/Numeric/Function/OptimizationStopCondition.cpp.o
[ 19%] Building CXX object src/CMakeFiles/bpp-core-shared.dir/Bpp/Numeric/Function/PowellMultiDimensions.cpp.o
[ 20%] Building CXX object src/CMakeFiles/bpp-core-shared.dir/Bpp/Numeric/Function/ReparametrizationFunctionWrapper.cpp.o
[ 20%] Building CXX object src/CMakeFiles/bpp-core-shared.dir/Bpp/Numeric/Function/SimpleMultiDimensions.cpp.o
[ 21%] Building CXX object src/CMakeFiles/bpp-core-shared.dir/Bpp/Numeric/Function/SimpleNewtonMultiDimensions.cpp.o
[ 21%] Building CXX object src/CMakeFiles/bpp-core-shared.dir/Bpp/Numeric/Function/ThreePointsNumericalDerivative.cpp.o
[ 21%] Building CXX object src/CMakeFiles/bpp-core-shared.dir/Bpp/Numeric/Function/TwoPointsNumericalDerivative.cpp.o
[ 22%] Building CXX object src/CMakeFiles/bpp-core-shared.dir/Bpp/Numeric/Hmm/AbstractHmmTransitionMatrix.cpp.o
[ 22%] Building CXX object src/CMakeFiles/bpp-core-shared.dir/Bpp/Numeric/Hmm/AutoCorrelationTransitionMatrix.cpp.o
[ 23%] Building CXX object src/CMakeFiles/bpp-core-shared.dir/Bpp/Numeric/Hmm/FullHmmTransitionMatrix.cpp.o
[ 23%] Building CXX object src/CMakeFiles/bpp-core-shared.dir/Bpp/Numeric/Hmm/HmmLikelihood.cpp.o
[ 24%] Building CXX object src/CMakeFiles/bpp-core-shared.dir/Bpp/Numeric/Hmm/LogsumHmmLikelihood.cpp.o
[ 24%] Building CXX object src/CMakeFiles/bpp-core-shared.dir/Bpp/Numeric/Hmm/LowMemoryRescaledHmmLikelihood.cpp.o
[ 25%] Building CXX object src/CMakeFiles/bpp-core-shared.dir/Bpp/Numeric/Hmm/RescaledHmmLikelihood.cpp.o
[ 25%] Building CXX object src/CMakeFiles/bpp-core-shared.dir/Bpp/Numeric/NumTools.cpp.o
[ 26%] Building CXX object src/CMakeFiles/bpp-core-shared.dir/Bpp/Numeric/Parameter.cpp.o
[ 26%] Building CXX object src/CMakeFiles/bpp-core-shared.dir/Bpp/Numeric/ParameterExceptions.cpp.o
[ 27%] Building CXX object src/CMakeFiles/bpp-core-shared.dir/Bpp/Numeric/ParameterList.cpp.o
[ 27%] Building CXX object src/CMakeFiles/bpp-core-shared.dir/Bpp/Numeric/Prob/AbstractDiscreteDistribution.cpp.o
[ 28%] Building CXX object src/CMakeFiles/bpp-core-shared.dir/Bpp/Numeric/Prob/BetaDiscreteDistribution.cpp.o
[ 28%] Building CXX object src/CMakeFiles/bpp-core-shared.dir/Bpp/Numeric/Prob/ConstantDistribution.cpp.o
[ 28%] Building CXX object src/CMakeFiles/bpp-core-shared.dir/Bpp/Numeric/Prob/DirichletDiscreteDistribution.cpp.o
[ 29%] Building CXX object src/CMakeFiles/bpp-core-shared.dir/Bpp/Numeric/Prob/ExponentialDiscreteDistribution.cpp.o
[ 29%] Building CXX object src/CMakeFiles/bpp-core-shared.dir/Bpp/Numeric/Prob/GammaDiscreteDistribution.cpp.o
[ 30%] Building CXX object src/CMakeFiles/bpp-core-shared.dir/Bpp/Numeric/Prob/GaussianDiscreteDistribution.cpp.o
[ 30%] Building CXX object src/CMakeFiles/bpp-core-shared.dir/Bpp/Numeric/Prob/InvariantMixedDiscreteDistribution.cpp.o
[ 31%] Building CXX object src/CMakeFiles/bpp-core-shared.dir/Bpp/Numeric/Prob/MixtureOfDiscreteDistributions.cpp.o
[ 31%] Building CXX object src/CMakeFiles/bpp-core-shared.dir/Bpp/Numeric/Prob/SimpleDiscreteDistribution.cpp.o
[ 32%] Building CXX object src/CMakeFiles/bpp-core-shared.dir/Bpp/Numeric/Prob/Simplex.cpp.o
[ 32%] Building CXX object src/CMakeFiles/bpp-core-shared.dir/Bpp/Numeric/Prob/TruncatedExponentialDiscreteDistribution.cpp.o
[ 33%] Building CXX object src/CMakeFiles/bpp-core-shared.dir/Bpp/Numeric/Prob/UniformDiscreteDistribution.cpp.o
[ 33%] Building CXX object src/CMakeFiles/bpp-core-shared.dir/Bpp/Numeric/Random/ContingencyTableGenerator.cpp.o
[ 34%] Building CXX object src/CMakeFiles/bpp-core-shared.dir/Bpp/Numeric/Random/RandomTools.cpp.o
[ 34%] Building CXX object src/CMakeFiles/bpp-core-shared.dir/Bpp/Numeric/Random/Uniform01K.cpp.o
[ 35%] Building CXX object src/CMakeFiles/bpp-core-shared.dir/Bpp/Numeric/Random/Uniform01QD.cpp.o
[ 35%] Building CXX object src/CMakeFiles/bpp-core-shared.dir/Bpp/Numeric/Random/Uniform01WH.cpp.o
[ 35%] Building CXX object src/CMakeFiles/bpp-core-shared.dir/Bpp/Numeric/Stat/ContingencyTableTest.cpp.o
[ 36%] Building CXX object src/CMakeFiles/bpp-core-shared.dir/Bpp/Numeric/Stat/Mva/CorrespondenceAnalysis.cpp.o
[ 36%] Building CXX object src/CMakeFiles/bpp-core-shared.dir/Bpp/Numeric/Stat/Mva/DualityDiagram.cpp.o
[ 37%] Building CXX object src/CMakeFiles/bpp-core-shared.dir/Bpp/Numeric/Stat/Mva/PrincipalComponentAnalysis.cpp.o
[ 37%] Building CXX object src/CMakeFiles/bpp-core-shared.dir/Bpp/Numeric/Stat/StatTools.cpp.o
[ 38%] Building CXX object src/CMakeFiles/bpp-core-shared.dir/Bpp/Numeric/VectorTools.cpp.o
[ 38%] Building CXX object src/CMakeFiles/bpp-core-shared.dir/Bpp/Text/KeyvalTools.cpp.o
[ 39%] Building CXX object src/CMakeFiles/bpp-core-shared.dir/Bpp/Text/NestedStringTokenizer.cpp.o
[ 39%] Building CXX object src/CMakeFiles/bpp-core-shared.dir/Bpp/Text/StringTokenizer.cpp.o
[ 40%] Building CXX object src/CMakeFiles/bpp-core-shared.dir/Bpp/Text/TextTools.cpp.o
[ 40%] Building CXX object src/CMakeFiles/bpp-core-shared.dir/Bpp/Utils/AttributesTools.cpp.o
[ 41%] Linking CXX shared library libbpp-core.dylib
/private/var/tmp/_bazel_pece/1aaea46e77017e4bf999057d24a482e7/sandbox/darwin-sandbox/1/execroot/bpp_yarcat/external/local_config_cc/cc_wrapper.sh: line 54: rpath/libbpp-core.4.dylib: No such file or directory
make[2]: *** [src/CMakeFiles/bpp-core-shared.dir/build.make:1473: src/libbpp-core.4.1.0.dylib] Error 1
make[1]: *** [CMakeFiles/Makefile2:964: src/CMakeFiles/bpp-core-shared.dir/all] Error 2
make: *** [Makefile:166: all] Error 2
_____ END BUILD LOGS _____
rules_foreign_cc: Build wrapper script location: bazel-out/darwin-fastbuild/bin/libbpp-core_foreign_cc/wrapper_build_script.sh
rules_foreign_cc: Build script location: bazel-out/darwin-fastbuild/bin/libbpp-core_foreign_cc/build_script.sh
rules_foreign_cc: Build log location: bazel-out/darwin-fastbuild/bin/libbpp-core_foreign_cc/CMake.log

INFO: Elapsed time: 288.137s, Critical Path: 246.74s
INFO: 2 processes: 2 internal.
FAILED: Build did NOT complete successfully
`

**Comment by UebelAndre** [comment]
> Are you building on MacOS or on a system that makes more sense? :D The same stuff actually builds perfectly fine on Linux, it's just MaxOS that is being difficult.

I'm on MacOS 11.4

**Comment by junniest** [comment]
Ok, now I am absolutely confused....

I ran `bazel version`, this is what I get:

```
Build label: 4.1.0
Build target: bazel-out/darwin-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Fri May 21 11:16:55 2021 (1621595815)
Build timestamp: 1621595815
Build timestamp as int: 1621595815
```

**Comment by junniest** [comment]
One final idea that I have is whether this could be due to the cmake version that I have?

This is is output of `cmake --version`:
```
cmake version 3.20.2

CMake suite maintained and supported by Kitware (kitware.com/cmake).

```

**Comment by UebelAndre** [comment]
```
bpp % bazel build //... --noremote_accept_cached
```
```
INFO: Invocation ID: 9d841cf8-4eff-4fc2-ade7-6ffa57a7b747
INFO: Analyzed 2 targets (26 packages loaded, 7782 targets configured).
INFO: Found 2 targets...
INFO: Elapsed time: 559.076s, Critical Path: 556.91s
INFO: 10 processes: 7 internal, 3 darwin-sandbox.
INFO: Build completed successfully, 10 total actions
```
```
bpp % cmake --version
```
```
cmake version 3.20.5

CMake suite maintained and supported by Kitware (kitware.com/cmake).
```

Perhaps the issue comes from the cc_toolchain? I believe most of my cc_toolchain comes from Xcode (I'm on `Version 12.5.1 (12E507)`). Aside from that, what do your build scripts look like?
[libbpp-seq_foreign_cc_build_script.txt](https://github.com/bazelbuild/rules_foreign_cc/files/6765077/libbpp-seq_foreign_cc_build_script.txt)
[libbpp-core_foreign_cc_build_script.txt](https://github.com/bazelbuild/rules_foreign_cc/files/6765078/libbpp-core_foreign_cc_build_script.txt)

**Comment by kekxv** [comment]
> [ 37%] Building CXX object src/CMakeFiles/bpp-core-shared.dir/Bpp/Numeric/Stat/StatTools.cpp.o
> [ 38%] Building CXX object src/CMakeFiles/bpp-core-shared.dir/Bpp/Numeric/VectorTools.cpp.o
> [ 38%] Building CXX object src/CMakeFiles/bpp-core-shared.dir/Bpp/Text/KeyvalTools.cpp.o
> [ 39%] Building CXX object src/CMakeFiles/bpp-core-shared.dir/Bpp/Text/NestedStringTokenizer.cpp.o
> [ 39%] Building CXX object src/CMakeFiles/bpp-core-shared.dir/Bpp/Text/StringTokenizer.cpp.o
> [ 40%] Building CXX object src/CMakeFiles/bpp-core-shared.dir/Bpp/Text/TextTools.cpp.o
> [ 40%] Building CXX object src/CMakeFiles/bpp-core-shared.dir/Bpp/Utils/AttributesTools.cpp.o
> [ 41%] Linking CXX shared library libbpp-core.dylib
> /private/var/tmp/_bazel_pece/1aaea46e77017e4bf999057d24a482e7/sandbox/darwin-sandbox/1/execroot/bpp_yarcat/external/local_config_cc/cc_wrapper.sh: line 54: rpath/libbpp-core.4.dylib: No such file or directory
> make[2]: *** [src/CMakeFiles/bpp-core-shared.dir/build.make:1473: src/libbpp-core.4.1.0.dylib] Error 1
> make[1]: *** [CMakeFiles/Makefile2:964: src/CMakeFiles/bpp-core-shared.dir/all] Error 2
> make: *** [Makefile:166: all] Error 2
> _____ END BUILD LOGS _____
> rules_foreign_cc: Build wrapper script location: bazel-out/darwin-fastbuild/bin/libbpp-core_foreign_cc/wrapper_build_script.sh
> rules_foreign_cc: Build script location: bazel-out/darwin-fastbuild/bin/libbpp-core_foreign_cc/build_script.sh
> rules_foreign_cc: Build log location: bazel-out/darwin-fastbuild/bin/libbpp-core_foreign_cc/CMake.log
> 
> INFO: Elapsed time: 288.137s, Critical Path: 246.74s
> INFO: 2 processes: 2 internal.
> FAILED: Build did NOT complete successfully
> ```

how fix this ? 😭 @junniest 
 
build opencv on macos
```
[ 65%] Building CXX object modules/core/CMakeFiles/opencv_core.dir/src/va_intel.cpp.o
[ 66%] Building CXX object modules/core/CMakeFiles/opencv_core.dir/opencl_kernels_core.cpp.o
[ 66%] Linking CXX shared library ../../lib/libopencv_core.dylib
/private/var/tmp/_bazel_caesar/70ee8c04188240ae82aa4f6ef5494dd3/sandbox/darwin-sandbox/388/execroot/TerminalService/external/local_config_cc/cc_wrapper.sh: line 54: rpath/libopencv_core.4.5.dylib: No such file or directory
make[2]: *** [lib/libopencv_core.4.5.3.dylib] Error 1
make[1]: *** [modules/core/CMakeFiles/opencv_core.dir/all] Error 2
make: *** [all] Error 2
```
- opencv_verison.cpp
- BUILD.bazel
- opencv_repositories.bzl

[opencv.zip](https://github.com/bazelbuild/rules_foreign_cc/files/6891127/opencv.zip)

**Comment by UebelAndre** [comment]
@kekxv Sorry, I'm not sure why this would be failing. In both cases here, it seems the build is non hermetic and configurations on the host are affecting the builds (yours and mine included). I do know that support for for shared libraries is currently "questionable". I'm happy to collaborate on pull requests to improve this. But for this case, I think finding ways to lock down the build to ensure no untracked files on the host are making it into the build would quickly reveal the issue.

**Comment by jsharpe** [comment]
@junniest - I note that you have `/usr/gnu/bin` in your PATH environment before the default macos tools. I suspect that one of the tools that is in there is confusing the ruleset as they are designed to use the BSD variants of the standard tools when building on macos.
Does it build if you add `--incompatible_strict_action_env` to your build line? 
https://docs.bazel.build/versions/main/command-line-reference.html#flag--incompatible_strict_action_env
