### ISSUE TITLE
Using cmake rule for projects that only build in-tree

### ISSUE THREAD

**Issue by joe-polin** [bazelbuild/rules_foreign_cc#714]
I'm attempting to pull and build a repository that explicitly puts its build artifacts (eg generated headers, libs, etc) into the `PROJECT_DIR` and/or `xxxx_SOURCE_DIR`, and I have no means of redirecting it with things like LIBRARY_OUTPUT_DIRECTORY. Of course, when it tries to write the new files in the source tree, I get a permissions error.

Has anyone else found a good solution to this? Currently I'm hacking up the imported project (will make my "modifications" into a patch) so that everything writes to (and reads) the `CMAKE_CURRENT_BINARY_DIR`. Doesn't feel like a great solution...

Thanks all!

**Comment by UebelAndre** [comment]
I thought cmake, by default, generated an `install` target for most things. Could have that wrong. But I'd recommend patching the repo to actually utilize cmake's [install](https://cmake.org/cmake/help/latest/command/install.html) command if one isn't available. If that doesn't work, there's a `postfix_script` attribute you can use to write raw bash code to do whatever you want. Let me know if that helps!

**Comment by joe-polin** [comment]
Thanks for the quick look @UebelAndre!

Here's the [line](https://github.com/raulmur/ORB_SLAM2/blob/master/Thirdparty/DBoW2/CMakeLists.txt#L35) from one project I'm trying to build:
```
set(LIBRARY_OUTPUT_PATH ${PROJECT_SOURCE_DIR}/lib)
```

As far as I can tell, this will put it right into the source tree (which isn't writable, so it fails). My cmake is pretty rusty though, so perhaps there's a flag I can pass into redirect?

**Comment by UebelAndre** [comment]
Hmmm, yeah, I'm not sure what the behavior is there. I wonder if you can patch the repo and comment that out to see the better behavior.

I've found it to be bad practice to try and force cmake to write things to a specific location in your workspace. Instead, just rely on the `install` functionality and you can set [CMAKE_INSTALL_PREFIX](https://cmake.org/cmake/help/latest/variable/CMAKE_INSTALL_PREFIX.html#variable:CMAKE_INSTALL_PREFIX) to get cmake to write to the destination you want with a well formed structure with far less effort.

**Comment by jsharpe** [comment]
I guess this is pointing towards a need for the equivalent of `configure_in_place` from `configure_make` for the cmake rules for the case where the cmake build modifies the source tree (or requires an in-tree build)

**Comment by joe-polin** [comment]
Thanks for the advice @UebelAndre -- will keep that in mind as I debug further. I commented that (and about 20 other things) out, and it seems to be working. Definitely building up tech debt though.

@jsharpe -- I saw that while browsing the repo, and was disappointed not to find it in the cmake command. I also considered copying the entire source directory into the output directory, and then building there. I'm not sure of the bazel commands to do that, though.

**Comment by chutsu** [comment]
I usually leave those untouched ```set(LIBRARY_OUTPUT_PATH ${PROJECT_SOURCE_DIR}/lib)```, by default cmake knows where to put them already so you don't technically need to override it.

**Comment by UebelAndre** [comment]
> I guess this is pointing towards a need for the equivalent of `configure_in_place` from `configure_make` for the cmake rules for the case where the cmake build modifies the source tree (or requires an in-tree build)

Not a bad idea! Maybe that'd be something to promote from `configure_make` to the common framework?
