### ISSUE TITLE
Deprecation of make_commands removes solution for complex build processes.

### ISSUE THREAD

**Issue by garrettkajmowicz-sophos** [bazelbuild/rules_foreign_cc#715]
I'm attempting to build netmap (see: https://github.com/luigirizzo/netmap) with bazel. This has several issues which make it incompatible with the configure_make() rule. The first is that the configure script isn't in the root of the repository. The second (specific to our local implementation) is that we need to run a few commands between the configure and the make step.

I've managed to get things working using the make_commands feature in rules_foreign_cc version 0.2.0, but that leaves us trapped at an older version. This was found using the guidance from someone with similar requirements working on a different project:

https://stackoverflow.com/questions/60048460/bazel-for-packages-with-a-bootstrap-configure-make-build

I would request that the make_commands() feature be re-introduced, or that another solution which addresses these 2 needs be provided.

**Comment by UebelAndre** [comment]
Hi, sorry you're having trouble, can you show an example of what you're trying to do? There's a [configure_in_place](https://bazelbuild.github.io/rules_foreign_cc/0.4.0/configure_make.html#configure_make-configure_in_place) attribute which I believe would solve for your first problem but for running commands before configure, this is a feature request still under discussion (https://github.com/bazelbuild/rules_foreign_cc/pull/429).

Some history, the `make_commands` attribute was removed in favor of the `targets` + `args` command to try and avoid users writing raw bash to solve their problems and instead use a well formed API. The problem before was there were many issues about very specific uses of the rules which was commonly an issue with the bash that was written. By having a well formed API and avoiding raw bash, the rules can be updated to fix common issues and make things easier for everyone by solving a core gap in functionality vs fixing a specific line of bash.

**Comment by garrettkajmowicz-sophos** [comment]
I tried the configure_in_place attribute and was able to make some amount of progress. I'll try switching to using the configure script at the root of the repository rather than the one in the LINUX directory which is what we usually use.

The set of instructions I am running is adapted from a scons wrapper which does work. Basically, we have to do some slightly strange things to the build process because the netmap code makes some invalid assumptions about our build environment. The changes we would need to upstream are unlikely to benefit others. The set of commands I'm currently running are:
>    make_commands = [
>        "cd LINUX",
>        "./configure " +
>            " --prefix=${INSTALLDIR}  --install-mod-path=${INSTALLDIR} " +
>            " --disable-monitor --no-drivers=mlx5,veth.c,forcedeth.c " +
>            " --no-ext-drivers --with-counters --without-dmasync " +
>            " --no-apps=bridge,lb,nmreplay,dedup,tlem " +
>            " --kernel-sources=/storage/infra/kernel_release/linux-4.14.173-src/ " +
>            " --kernel-dir=/storage/infra/kernel_release/linux-4.14.173-src/ " +
>            " --driver-suffix=_nm ",
>        "sed -i.bak 's/S_DRIVERS =/S_DRIVERS = igb ixgbe/' netmap.mak",
>        "sed -i.bak 's/vanilla--ixgbe--40900--41000/intel--ixgbe--5.5.1/' drivers.mak",
>        "sed -i.bak 's/vanilla--igb--40400--99999/intel--igb--5.3.5.20/' drivers.mak",
>        "cd netmap-tmpdir",
>        "rm -f get-igb",
>        "rm -f get-ixgbe",
>        "rm -rf igb",
>        "rm -rf ixgbe",
>        "make build-igb",
>        "make build-ixgbe",
>        "make tests -ik",
>        "cd ..",
>        "make get-igb",
>        "make get-ixgbe",
>        "mv igb/orig.mak igb/Makefile",
>        "mv ixgbe/orig.mak ixgbe/Makefile",
>        "sed -i.bak 's/E_DRIVERS =/E_DRIVERS = igb ixgbe/' netmap.mak",
>        "make V=1",
>        "make V=1 BUILD_KERNEL=linux-4.14.173-src install",
>    ],

**Comment by fwingerter-Ocient** [comment]
The hacky workaround I've found for this is to set `args = ["--eval", "all:\n\techo anything you'd like"]` and `targets = [""]`, and then you can run your actual `make` steps in `postfix_script`.

**Comment by garrettkajmowicz-sophos** [comment]
> The hacky workaround I've found for this is to set `args = ["--eval", "all:\n\techo anything you'd like"]` and `targets = [""]`, and then you can run your actual `make` steps in `postfix_script`.

I'm attempting this and running into issues with newlines and other parsing issues. Can you point to any example BUILD files online where this has been done?

**Comment by garrettkajmowicz-sophos** [comment]
My workaround for these types of issues is to create an extra Makefile.bazel which wraps the underlying makefile. This allows additional operations to be done before and after any configuration and make calls.
