### ISSUE TITLE
make install prefix: bug or incorrect documentation

### ISSUE THREAD

**Issue by jheaff1** [bazelbuild/rules_foreign_cc#736]
Hi,

The documentation of the `make` rule states the following:

https://github.com/bazelbuild/rules_foreign_cc/blob/b51f25ee6289f72031ae203c5c6ad917fbb3d5d1/foreign_cc/make.bzl#L92

Before [these](https://github.com/bazelbuild/rules_foreign_cc/commit/e4399415b806938ef4179dd9c72f76cdfe102478#diff-4a65571d1835d240c82a2c62d7550f8b537ebe729a68f63f6a9598f2a591997aL52-R63) changes in commit e4399415b806938ef4179dd9c72f76cdfe102478, `make` was indeed invoked with `PREFIX=<install dir>`. Commit e4399415b806938ef4179dd9c72f76cdfe102478 removed the `PREFIX=<install dir>` args to the `make` invocation.

Was this change intentional? If so, the documentation for the `make` rule should be updated. If it wasn't intentional, then the change has introduced a bug and should be resolved. I'm happy to submit a PR to update the documentation or fix the issue, if is indeed an issue :)

**Comment by fwingerter-Ocient** [comment]
+1, either the docs or the implementation here seems wrong.

**Comment by UebelAndre** [comment]
I'm of the opinion that the docs are wrong. I don't think the rules should be passing args without the user requesting them but this is one I could be convinced otherwise on. What do others think?

**Comment by jheaff1** [comment]
I think it depends on whether providing a `INSTALL=` flag when invoking `make` is deemed the standard way of setting the install directory.

If it is, then it makes sense for the `make()` rule to set the installation prefix as it does for `configure_make()` and `cmake()`.

I’m not too bothered either way as this issue wouldn’t block anyone as they can simply set the `INSTALL` flags themselves.

**Comment by UebelAndre** [comment]
My initial thought was that the rules would set no flags so that the behavior of each build would be determined by whatever the user defined, but I'm not currently aware of an issue in setting `INSTALL=` or `PREFIX=`. Could I tempt someone into opening a PR to restore the behavior or update the docs? 😅
