### ISSUE TITLE
Building AWS SDK

### ISSUE THREAD

**Issue by aksh0001** [bazelbuild/rules_foreign_cc#756]
Hi,

I am new to Bazel and would like to integrate the [AWS C++ SDK](https://github.com/aws/aws-sdk-cpp) for use in a Bazel project, but I'm having problems with the build, where the output shared library cannot be created. Could I get some guidance on building this project with the `cmake` rule?

`WORKSPACE` file:
```
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")
load("@bazel_tools//tools/build_defs/repo:git.bzl", "new_git_repository")

http_archive(
    name = "rules_foreign_cc",
    sha256 = "5470b22db8974824a1994593f117b0ef8c2e5fb474fd30a7473fcfd77d8d1ed7",
    strip_prefix = "rules_foreign_cc-f01fd353ee2adcd55aab899c12fa2733223228a1",
    url = "https://github.com/bazelbuild/rules_foreign_cc/archive/f01fd353ee2adcd55aab899c12fa2733223228a1.tar.gz",
)

load("@rules_foreign_cc//foreign_cc:repositories.bzl", "rules_foreign_cc_dependencies")

rules_foreign_cc_dependencies()

_ALL_CONTENT = """\
filegroup(
    name = "all_srcs",
    srcs = glob(["**"]),
    visibility = ["//visibility:public"],
)
"""

new_git_repository(
    name = "aws_sdk_cpp",
    build_file_content = _ALL_CONTENT,
    commit = "472a4e54cef8039ac7e65560f169cfd848951009",
    recursive_init_submodules = True,
    remote = "https://github.com/aws/aws-sdk-cpp",
    shallow_since = "1628277923 +0000",
)
```

`BUILD` file:
```
load("@rules_foreign_cc//foreign_cc:defs.bzl", "cmake")

cc_binary(
    name = "main",
    srcs = ["main.cc"],
    deps = [":aws_sdk_cpp"],
)

cmake(
    name = "aws_sdk_cpp",
    cache_entries = {
        "CMAKE_BUILD_TYPE": "Release",
        "BUILD_ONLY": "s3;rds",
        "BUILD_SHARED_LIBS": "OFF",
        "ENABLE_TESTING": "OFF",
    },
    install = False,
    lib_source = "@aws_sdk_cpp//:all_srcs",
)
```
Command used to build: `bazel build //:main --sandbox_writable_path=/home/<username>/.cache`
(`--sandbox_writable_path` needed as there is some modification to the file system by the SDK)

Output:
```
username@hostname:~/projects/aws-sdk-cpp-bazel$ bazel build //:main --sandbox_writable_path=/home/username/.cache
INFO: Analyzed target //:main (26 packages loaded, 96355 targets configured).
INFO: Found 1 target...
ERROR: /home/username/projects/aws-sdk-cpp-bazel/BUILD.bazel:9:6: output 'aws_sdk_cpp/lib/aws_sdk_cpp.a' was not created
ERROR: /home/username/projects/aws-sdk-cpp-bazel/BUILD.bazel:9:6: Foreign Cc - CMake: Building aws_sdk_cpp failed: not all outputs were created or valid
Target //:main failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 865.193s, Critical Path: 583.32s
INFO: 10 processes: 8 internal, 2 linux-sandbox.
FAILED: Build did NOT complete successfully
```

**Comment by jheaff1** [comment]
I think you need to set the [`out_static_libs`](https://bazelbuild.github.io/rules_foreign_cc/main/cmake.html#cmake-out_static_libs)     attribute of the `cmake()` target. Otherwise, the `cmake()` target will expect that a static library called `<target_name>.a` will be created by the build, in this case `aws_sdk_cpp.a`.

Let’s say that the build of AWS SDK generates a static library named `libaws.a`, your `cmake()` target should look like:

```
cmake(
    name = "aws_sdk_cpp",
    cache_entries = {
        "CMAKE_BUILD_TYPE": "Release",
        "BUILD_ONLY": "s3;rds",
        "BUILD_SHARED_LIBS": "OFF",
        "ENABLE_TESTING": "OFF",
    },
    install = False,
    lib_source = "@aws_sdk_cpp//:all_srcs",
    out_static_libs = [“libaws.a”],
)
```
Hope that made sense

**Comment by aksh0001** [comment]
> I think you need to set the [`out_static_libs`](https://bazelbuild.github.io/rules_foreign_cc/main/cmake.html#cmake-out_static_libs) attribute of the `cmake()` target. Otherwise, the `cmake()` target will expect that a static library called `<target_name>.a` will be created by the build, in this case `aws_sdk_cpp.a`.
> 
> Let’s say that the build of AWS SDK generates a static library named `libaws.a`, your `cmake()` target should look like:
> 
> ```
> cmake(
>     name = "aws_sdk_cpp",
>     cache_entries = {
>         "CMAKE_BUILD_TYPE": "Release",
>         "BUILD_ONLY": "s3;rds",
>         "BUILD_SHARED_LIBS": "OFF",
>         "ENABLE_TESTING": "OFF",
>     },
>     install = False,
>     lib_source = "@aws_sdk_cpp//:all_srcs",
>     out_static_libs = [“libaws.a”],
> )
> ```
> 
> Hope that made sense

Thanks!
