### ISSUE TITLE
Avoid rebuild when change workspace `.bazelrc`

### ISSUE THREAD

**Issue by hiberabyss** [bazelbuild/rules_foreign_cc#772]
Now, the external package with `rules_foreign_cc` will be rebuilt when change something like `copt`, could this be avoid?

**Comment by jsharpe** [comment]
This is by design - `rules_foreign_cc` makes the foreign build system use as much of the configured cc toolchain as it can and so inherently if you make a change to `copt` then it is going to force a rebuild.

**Comment by hiberabyss** [comment]
> This is by design - `rules_foreign_cc` makes the foreign build system use as much of the configured cc toolchain as it can and so inherently if you make a change to `copt` then it is going to force a rebuild.

Could this behavior be controlled via an option?

In many cases, the `copts` only want to affect my own codes, and keep the external package unchanged. The external 
package building may be very slow and don't want build many times.

**Comment by hiberabyss** [comment]
> This is by design - `rules_foreign_cc` makes the foreign build system use as much of the configured cc toolchain as it can and so inherently if you make a change to `copt` then it is going to force a rebuild.

Currently, if change options like `-O2`, could this also take effect in external package?

**Comment by jsharpe** [comment]
There are a few approaches you can take to this - you could create a transition where you empty or set to a known value the `copt` flag or you can define your own cc_toolchain and use `features` to define the custom set of `copt` flags that you want to apply to your own code.

**Comment by jheaff1** [comment]
Would [per_file_copt](https://docs.bazel.build/versions/main/command-line-reference.html#flag--per_file_copt) help?

**Comment by hiberabyss** [comment]
> There are a few approaches you can take to this - you could create a transition where you empty or set to a known value the `copt` flag or you can define your own cc_toolchain and use `features` to define the custom set of `copt` flags that you want to apply to your own code.

Thanks for your reply!

In fact, what I want to change is the `--compilation_mode` option, how could I use transition to set the `compilation_mode` for external package?

**Comment by hiberabyss** [comment]
> Would [per_file_copt](https://docs.bazel.build/versions/main/command-line-reference.html#flag--per_file_copt) help?



> Would [per_file_copt](https://docs.bazel.build/versions/main/command-line-reference.html#flag--per_file_copt) help?



> Would [per_file_copt](https://docs.bazel.build/versions/main/command-line-reference.html#flag--per_file_copt) help?

Thanks for your replay! Seems it's difficult to set this option for external package.
