### ISSUE TITLE
import_dll Library **.dll (which is needed by L"**.exe") not found

### ISSUE THREAD

**Issue by kekxv** [bazelbuild/rules_foreign_cc#779]
bazel test exe will show this when remote mingw:
```
exec ${PAGER:-/usr/bin/less} "$0" || exit 1
Executing tests from //**:**
-----------------------------------------------------------------------------
0009:err:module:import_dll Library **.dll (which is needed by L"**.exe") not found
0009:err:module:LdrInitializeThunk Importing dlls for L"**.exe" failed, status c0000135
```

I think the dll should not be found,windows find dll only PATH or local.

<img width="713" alt="image" src="https://user-images.githubusercontent.com/15551108/131251857-75a860a6-7e00-4b2e-bf21-a38ef8f9747d.png">

**Comment by jsharpe** [comment]
Would you be able to put together an example in the examples directory that demonstrates this issue?
