### ISSUE TITLE
output_group "bin_dir_name" or "lib_dir_name" is empty

### ISSUE THREAD

**Issue by kekxv** [bazelbuild/rules_foreign_cc#780]
i want get lib or bin file to pkg_tar,but only empty.
and  output_group = "gen_dir" is not empty.

https://github.com/bazelbuild/rules_foreign_cc/blob/main/docs/README.md#foreignccartifact

<img width="1002" alt="image" src="https://user-images.githubusercontent.com/15551108/131501482-c5d3843b-552f-4fcb-8a6e-feeec737a1d6.png">

**Comment by alexeagle** [comment]
I think I have a similar problem with the `gen_dir` output_group, it doesn't contain the shared_libs from a configure_make rule. Will post a repro on another issue.
