### ISSUE TITLE
Documentation does not include `load` paths or examples

### ISSUE THREAD

**Issue by psigen** [bazelbuild/rules_foreign_cc#782]
In the new documentation site: https://bazelbuild.github.io/rules_foreign_cc/

When looking up a function e.g. `configure_make`, the documentation is missing any reference to where the `configure_make` script is defined (i.e. a command like `load("@rules_foreign_cc//foreign_cc:defs.bzl", "configure_make")`).  This makes it hard to determine how to actually use the function in practice.

For example, the current entry for `configure_make` only includes the following function signature:

![bazel_docs](https://user-images.githubusercontent.com/2805291/132263223-3410f940-3b53-4bf0-9b0c-c00541e7bc0c.png)

Please consider adding brief example snippets or _at least_ the required `load` directive so that when looking at a particular function entry, it is possible to figure out how to use it without referring to the source code.

e.g.:
```
load("@rules_foreign_cc//foreign_cc:defs.bzl", "configure_make")

configure_make(
    name = "mylibrary",
    configure_in_place = True,
    lib_source = ":all",
    out_static_libs = ["libmylibrary.a"],
)
```

The two points in the documentation referring to `configure_make`:
- https://bazelbuild.github.io/rules_foreign_cc/main/configure_make.html
- https://bazelbuild.github.io/rules_foreign_cc/main/flatten.html#configure_make

**Comment by UebelAndre** [comment]
Hey, good call out 😄 Would you be willing to open a PR with updated docs for how you think it should look? 🙏 

Also, I'm a bit hazy on how this looked before. Is this a regression?

**Comment by psigen** [comment]
Umm, how should I do that?  The docs appear to be autogenerated now-- should I make a PR into the markdown showing how I would like it to look?

The actual rule containing the docstring doesn't seem to support complex formatting:
https://github.com/bazelbuild/rules_foreign_cc/blob/2e61d9588a36c1184eafde79f8307cdf95e6a469/foreign_cc/configure.bzl#L214-L220

**Comment by UebelAndre** [comment]
It does support complex formatting. You can update the doc attribute to a docstring and write markdown in it.
