### ISSUE TITLE
How can a cmake library depend on a configure_make library?

### ISSUE THREAD

**Issue by photex** [bazelbuild/rules_foreign_cc#787]
Howdy!

I'm trying to setup IceOryx as a third party library in my bazel build. On Linux it requires libacl which also requires libattr. It's possible to just install these libraries using the system package manager, but I wanted to try bundling these in my repo so that I can support cross compilation.

libattr and libacl appear to be building just fine but I'm getting stuck trying to explain to iceoryx where to find them.

What should the approach generally be when there are various libraries with different external builds?

Thanks!
Chip

**Comment by pqn** [comment]
@photex just wondering if you had any code or tips to share as I'm also interested in setting up iceoryx for bazel.

**Comment by photex** [comment]
I ended up being happier with a pure bazel build. I could put the BUILD files in a gist possibly, or on a fork of IceOryx if it'd help you out.

**Comment by pqn** [comment]
That would be greatly appreciated, thank you! Whichever is more convenient.

**Comment by LiyouZhou** [comment]
@photex I would be interested in this as well. would you be able to share?

**Comment by photex** [comment]
Hi everyone. Before I was able to put that together I ended up switching jobs. I no longer have access to this. My apologies.
