### ISSUE TITLE
There is no '-W' option for pwd

### ISSUE THREAD

**Issue by soulxu** [bazelbuild/rules_foreign_cc#791]
I try to compile Envoy on Windows.

Got the error
`
bazel-out/x64_windows-fastbuild/bin/external/envoy/bazel/foreign_cc/nghttp2_foreign_cc/build_script.sh: line 50: pwd: -W: invalid option
pwd: usage: pwd [-LP]
mkdir: cannot create directory 鈥?bazel-out鈥? Permission denied
`

As the output there is no -W parameter.

https://github.com/bazelbuild/rules_foreign_cc/blob/4ee863c1fc88b554b9b185f192eaadd2e44c011e/foreign_cc/private/framework/toolchains/windows_commands.bzl#L11-L12

is there anyway I can workaround with this?

**Comment by dhmemi** [comment]
`pwd -W` only work in mingw bash, which will print `$PWD` path as windows style. maybe you installed WSL, and your bash is from linux in WSL.

**Comment by mikejack07** [comment]
Hi,

Facing the same problem:

```
C:\Users\mikejack>where bash
C:\Windows\System32\bash.exe
```

opened in bash.

```
/mnt/c/Users/mikejack/BazelCMake/Build$ bazel build //Source:pcre
bazel: command not found
```

Is there any way to resolve the error? You can have a look at the [original threads here](https://github.com/bazelbuild/rules_foreign_cc/issues/969) .
