### ISSUE TITLE
Could you make a leveldb example?

### ISSUE THREAD

**Issue by ericuni** [bazelbuild/rules_foreign_cc#825]

**Comment by jsharpe** [comment]
We only really add examples that are specifically to test a feature that is used in the ruleset and as such we probably won't be adding leveldb as an example. If you need help building leveldb I'd suggest either posting on stackoverflow, the bazel mailing list or bazel slack.

**Comment by ericuni** [comment]
Those examples are too simple, if the purpose of this project is to make people use it, I think it's worthy to give an relatively sophisticated example. leveldb is very common used, and it's source code are relatively small.

**Comment by ericuni** [comment]
> We only really add examples that are specifically to test a feature that is used in the ruleset and as such we probably won't be adding leveldb as an example. If you need help building leveldb I'd suggest either posting on stackoverflow, the bazel mailing list or bazel slack.

Those examples are too simple, if the purpose of this project is to make people use it, I think it's worthy to give an relatively sophisticated example.
leveldb is very common used, and it's source code are relatively small. I think it's a good start.
