### ISSUE TITLE
action_env do not have effect on rules_foreign_cc

### ISSUE THREAD

**Issue by kkpattern** [bazelbuild/rules_foreign_cc#878]
Currently, the `action_env` do not have effect on `rule_foreign_cc`. We use bazelisk as the bazel launcher. It will prepend the actual bazel path to `PATH` env. Since bazelisk install bazel in user cache directory, this will cause different developer have different `PATH` env, cause remote cache miss.

We can solve this probelm by using `--action_env=PATH=/usr/bin:/bin`. However, `action_env` do not have effect on `rule_foreign_cc`. So targets build with `rules_foreign_cc` will still have remote cache miss.

Following is the output of bazel excetion json log:

```json
{     
   "environmentVariables": [{
     "name": "PATH",
     "value": "/home/username/.cache/bazelisk/downloads/bazelbuild/bazel-4.2.2-linux-x86_64/bin:/usr/local/bin:/usr/local/sbin:/usr/sbin:/usr/bin:/sbin:/bin"
   }],
   ...
}
```

**Comment by jheaff1** [comment]
Will this be of any use?

https://docs.bazel.build/versions/main/command-line-reference.html#flag--incompatible_strict_action_env

**Comment by kkpattern** [comment]
> Will this be of any use?
> 
> https://docs.bazel.build/versions/main/command-line-reference.html#flag--incompatible_strict_action_env

Yes. But on MacOS `--incompatible_strict_action_env` seems not ideal:

[https://github.com/bazelbuild/bazelisk/issues/111#issuecomment-771847027](https://github.com/bazelbuild/bazelisk/issues/111#issuecomment-771847027)
