### ISSUE TITLE
can pass a script file path to postfix_script parameter in cmake rule?

### ISSUE THREAD

**Issue by xiedeacc** [bazelbuild/rules_foreign_cc#883]
as title, if cannot pass a file path, request for implement it

**Comment by attilaolah** [comment]
I think you can pass a script file path. There is nothing special about the `postfix_script`, you can even inline an entire script there (multi-line string are fine), which is what I've been doing. Alternatively, you can call your script there.

You might need to reference it as `"${BUILD_TMPDIR}/myscript.sh"` or similar unless you're building in-place.

**Comment by xiedeacc** [comment]
> I think you can pass a script file path. There is nothing special about the `postfix_script`, you can even inline an entire script there (multi-line string are fine), which is what I've been doing. Alternatively, you can call your script there.
> 
> You might need to reference it as `"${BUILD_TMPDIR}/myscript.sh"` or similar unless you're building in-place.

will rule copy script to BUID_TMPDIR?

**Comment by xiedeacc** [comment]
first use filegroup rule add script file, then use cmake build_data attr copy file to build directory, then use postfix_script execute that script

**Comment by attilaolah** [comment]
I think it will actually symlink the script instead of copying, but yes. I thought you already had the script in the repo, but i f you don't, then you can use `build_data` as you said, and you might need to use `$(execpath :script)` to locate it, or maybe `$(rootpath script)`, I'm never sure which one works where.
