### ISSUE TITLE
cmake install occur error in cmake rule when bazel build or test not use sandbox

### ISSUE THREAD

**Issue by xiedeacc** [bazelbuild/rules_foreign_cc#886]
include and lib out directory will create first when build or test, but build not use sandbox, like use --spawn_strategy=standalone, cmake install will create these diretory again use same path,  so errors ocurred, I think it need rules_foreign_cc to made compatible with other strategy.

here is log:
CMake Error: failed to create symbolic link '/root/.cache/bazel/_bazel_root/212dd51f8d897b720cf9b65a010c79c8/execroot/tbox/bazel-out/k8-fastbuild/bin/external/smhasher/smhasher/include': File exists
CMake Error at cmake_install.cmake:46 (file):
  file INSTALL cannot duplicate symlink
  "/root/.cache/bazel/_bazel_root/212dd51f8d897b720cf9b65a010c79c8/execroot/tbox/external/smhasher"
  at
  "/root/.cache/bazel/_bazel_root/212dd51f8d897b720cf9b65a010c79c8/execroot/tbox/bazel-out/k8-fastbuild/bin/external/smhasher/smhasher/include":
  File exists.

**Comment by attilaolah** [comment]
For reference, here is the [execution strategy](https://bazel.build/docs/user-manual#execution-strategy) section of the manual, the following values are documented:

- ~`standalone`~ → deprecated, use `local`
- `sandboxed`
- `local`
- `worker`
- `docker`
- `remote`

I don't think I ever tried using any of these explicitly, but I'm mostly building my things inside a Docker container anyway, and it would indeed be nice fi instead I could use the `docker` strategy to let Bazel manage the container for me.

Looks like `standalone` is deprecated though, have you also tried with `--spawn_strategy=local`? Does it give you the same error?

**Comment by jsharpe** [comment]
For what its worth we do try to test the standalone spawn_strategy: https://github.com/bazelbuild/rules_foreign_cc/blob/9fc3411bb506de1e0d1fa91db0dbf7712d1028ae/.bazelci/config.yaml#L31
However the testing is a bit problematic in that it can hit the build cache and share the results with the sandboxed execution and so it can be a bit fragile at catching regressions.
I personally only make use of sandboxed and remote execution so this won't be a priority for me to look at. PRs to fix this are welcome though!

To understand more aboiut your use case is there a particular reason for not wanting to use the sandboxed strategy?

**Comment by xiedeacc** [comment]
> 

yes, for some reason, some test case cannot use sandboxed strategy
