### ISSUE TITLE
Have an option to propagate `CMAKE_PREFIX_PATH`

### ISSUE THREAD

**Issue by attilaolah** [bazelbuild/rules_foreign_cc#887]
I see that in the `libgit2` example, we pass along `CMAKE_PREFIX_PATH` manually. This is nice for one or two packages, but can be an annoyance when there is a large tree of dependencies.

It would be awesome if the `cmake()` rule could preserve its output (the `copy_:rule_name/:rule_name` directory) in the provider it returns, and then (optionally) pass them on to the dependent `cmake()` builds.

Adding the info to the provider seems simple enough, but we might want to control how or which dependencies are added to the cache entries. We could introduce an optional `prefix_path` command, with the following logic:

- If `None` (the default), then copy from all transitive `cmake` dependencies.
- If provided, it must be a list of labels that are (a) a direct or transitive dependency, and (b) also `cmake()` rules, or at least rules that provide the same provider that holds the prefix path info.

Then aggregate all the prefix path variables, `;`-join them and optionally append to an existing `CMAKE_PREFIX_PATH` from the `cache_entries`, or else generate a new entry.

This should make it so that by default CMake dependencies can find each other by default.

**Comment by attilaolah** [comment]
I think this could be done in a similar way we handle `PKG_CONFIG_PATH`.

**Comment by matt-sm** [comment]
> but can be an annoyance when there is a large tree of dependencies

+1 

Just trying to picture how the provider would work.  

We could start with cmake rules. The end result I assume is `CMAKE_PREFIX_PATH`s equivalent of `${EXT_BUILD_DEPS}/<package>`, for the package and each transitive dep, similar to the `libgit2` example.

The paths could be read and passed to [_merge_prefix_paths](https://github.com/bazel-contrib/rules_foreign_cc/blob/e67c45c8db19f13b681fff0d608117308c1bfd4c/foreign_cc/private/cmake_script.bzl#L174) where they'd be merged with user-defined paths.

The dep cmake rule could output the new provider (or perhaps update `ForeignCcDepsInfo`?) and automatically add the `CMAKE_PREFIX_PATH`s.
