### ISSUE TITLE
docs repository not found in release 0.7.1?

### ISSUE THREAD

**Issue by jayeye** [bazelbuild/rules_foreign_cc#888]
I just updated my WORKSPACE to use rules_foreign 0.7.1, and now I am getting the following error:
```
ERROR: error loading package 'bazel-main/external/rules_foreign_cc/docs': Unable to find package for @io_bazel_stardoc//stardoc:stardoc.bzl: The repository '@io_bazel_stardoc' could not be resolved: Repository '@io_bazel_stardoc' is not defined.
```

I am still at bazel-4.2.2.

**Comment by UebelAndre** [comment]
The `docs` package is considered a separate workspace not for user consumption. Could you elaborate on why you're trying to access targets there?
