### ISSUE TITLE
Ninja build should depend on python3 toolchain

### ISSUE THREAD

**Issue by jsharpe** [bazelbuild/rules_foreign_cc#901]
I'm not sure there is prior art on how to achieve this but I guess we'd need some way to convert a `py_runtime_pair` into something that returns `platform_common.TemplateVariables` that defines a `PYTHON` variable to be able to call the correct python but I don't know how to do that as the python toolchains is all native Java AFAIK and so I'm not sure how to extract the appropriate information in starlark (if its even currently possible).

Lets be pragmatic and go with the assumption that python3 is available on the path for now as we previously did for py2. I'll open another issue to track the fact that we should technically depend on a toolchain.

_Originally posted by @jsharpe in https://github.com/bazelbuild/rules_foreign_cc/issues/900#issuecomment-1104516729_

**Comment by jheaff1** [comment]
Given that python toolchains return `PyRuntimeInfo`, see [here](https://github.com/bazelbuild/bazel/blob/394ddb82b311ea7edbe2522736b0b0202903ddb6/tools/python/toolchain.bzl#L75), perhaps all that is needed to to implement a `current_py_toolchain` rule, similar to [these](https://github.com/bazelbuild/rules_foreign_cc/blob/c57b55f2f6207c0c44c2b4a51dc235955d4f47b2/toolchains/toolchains.bzl#L38) , to return  `platform_common.TemplateVariables`

**Comment by jheaff1** [comment]
Actually perhaps all that is required is for the `[ninja_tool](https://github.com/bazelbuild/rules_foreign_cc/blob/c57b55f2f6207c0c44c2b4a51dc235955d4f47b2/foreign_cc/built_tools/ninja_build.bzl#L29) `  rule to include `@bazel_tools//python:toolchain_type` and to extract the path to the python interpreter using `ctx.toolchains[@bazel_tools//python:toolchain_type].py3_runtime.interpreter_path`

**Comment by jheaff1** [comment]
This was resolved in #935
