### ISSUE TITLE
Conflict with local ccache install

### ISSUE THREAD

**Issue by CareF** [bazelbuild/rules_foreign_cc#981]
The tool fails with `ccache: error: Failed to create directory /home/user/.ccache/tmp: Read-only file system` `ccache` is installed locally.

For exampl: 
https://github.com/CareF/bazel_camke_opencv

if `ccache` is not installed, `bazel build @opencv//:opencv ` can finish without a problem, otherwise it will fail.

Tested under bazel 5.1.0 and Ubuntu 20.04. 

It may be related with https://github.com/bazelbuild/rules_foreign_cc/issues/947

**Comment by CareF** [comment]
> Are you configuring bazel's toolchain with ccache's symlinks in your path i.e. setting the bazel compiler to be ccache? 

No. I didn't configure bazel toolchain other than its default configuration (as you can see from my example). Though system ccache naturally comes into `PATH` when it is installed, but I would assume being environment independent should be part of the design goal?

> Or is this due to cmake searching and finding ccache on the host?

I think so from what I see. 

> What spawn strategy are you using when this occurs?

I'm using the default setting. According to the document (https://bazel.build/docs/user-manual) it should be sandboxed I would assume.

**Comment by jsharpe** [comment]
Ok; this isn't a rules_foreign_cc issue then; its the issue I linked above from bazel core. But in general the fix is to explicitly set `CC=/usr/bin/gcc` before invoking bazel for the first time. You may need to run `bazel shutdown` to pick up the change in CC and force a reconfigure of the cc toolchain.

**Comment by CareF** [comment]
> Ok; this isn't a rules_foreign_cc issue then; its the issue I linked above from bazel core. But in general the fix is to explicitly set `CC=/usr/bin/gcc` before invoking bazel for the first time. You may need to run `bazel shutdown` to pick up the change in CC and force a reconfigure of the cc toolchain.

I tried for the same repo, `bazel clean && bazel shutdown`，then `CC=/usr/bin/gcc bazel build @opencv//:opencv`, there is exactly the same error message

**Comment by tangbom** [comment]
Is this problem solved? I had the same problem and tried the method mentioned above and it didn't work. 
thanks
